//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testorm.MiniUiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServiceWcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UCLEnum", Namespace="http://schemas.datacontract.org/2004/07/ServiceCommon.Enum")]
    public enum UCLEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Import = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Upload = 20,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiniUiService.IServiceWcfService")]
    public interface IServiceWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/GetData", ReplyAction="http://tempuri.org/IServiceWcfService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceWcfService/GetDataUsingDataContractResponse")]
        testorm.MiniUiService.CompositeType GetDataUsingDataContract(testorm.MiniUiService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/fnH2000ToCDSystem", ReplyAction="http://tempuri.org/IServiceWcfService/fnH2000ToCDSystemResponse")]
        bool fnH2000ToCDSystem(string sJson, string customercd, ref string errorstr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/ImportRequest", ReplyAction="http://tempuri.org/IServiceWcfService/ImportRequestResponse")]
        string[] ImportRequest(string customerCd, string ids, bool isSingle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/exportDF", ReplyAction="http://tempuri.org/IServiceWcfService/exportDFResponse")]
        bool exportDF(string sJson, string Syscustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/getuploadFile", ReplyAction="http://tempuri.org/IServiceWcfService/getuploadFileResponse")]
        string getuploadFile(string Number, string SysCd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/SaveUclLog", ReplyAction="http://tempuri.org/IServiceWcfService/SaveUclLogResponse")]
        void SaveUclLog(string EdiNo, testorm.MiniUiService.UCLEnum enumtype, string ep, string customercd, string ex, bool status, string UclOperator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/exportEntryList", ReplyAction="http://tempuri.org/IServiceWcfService/exportEntryListResponse")]
        bool exportEntryList(string sJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/importManual", ReplyAction="http://tempuri.org/IServiceWcfService/importManualResponse")]
        bool importManual(string tableName, string Json, string customercd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/H2000ImportDeclare", ReplyAction="http://tempuri.org/IServiceWcfService/H2000ImportDeclareResponse")]
        string[] H2000ImportDeclare(string sJson, string customercd, int days, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/importManualSingle", ReplyAction="http://tempuri.org/IServiceWcfService/importManualSingleResponse")]
        string importManualSingle(string json, string customercd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/getStatus", ReplyAction="http://tempuri.org/IServiceWcfService/getStatusResponse")]
        void getStatus(string json, string customercd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/updateEntryId", ReplyAction="http://tempuri.org/IServiceWcfService/updateEntryIdResponse")]
        void updateEntryId(string[] strList, string customercd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/updateHeadDtl", ReplyAction="http://tempuri.org/IServiceWcfService/updateHeadDtlResponse")]
        bool updateHeadDtl(string id, string type, long DEH_ID, string Deh_Trade_Name, string Deh_Owner_Name, string Deh_Agent_Name, string Deh_Note_s, long Ded_Id, string Ded_g_Name, string Ded_g_Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcfService/testUi", ReplyAction="http://tempuri.org/IServiceWcfService/testUiResponse")]
        string testUi();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWcfServiceChannel : testorm.MiniUiService.IServiceWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWcfServiceClient : System.ServiceModel.ClientBase<testorm.MiniUiService.IServiceWcfService>, testorm.MiniUiService.IServiceWcfService {
        
        public ServiceWcfServiceClient() {
        }
        
        public ServiceWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public testorm.MiniUiService.CompositeType GetDataUsingDataContract(testorm.MiniUiService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public bool fnH2000ToCDSystem(string sJson, string customercd, ref string errorstr) {
            return base.Channel.fnH2000ToCDSystem(sJson, customercd, ref errorstr);
        }
        
        public string[] ImportRequest(string customerCd, string ids, bool isSingle) {
            return base.Channel.ImportRequest(customerCd, ids, isSingle);
        }
        
        public bool exportDF(string sJson, string Syscustomer) {
            return base.Channel.exportDF(sJson, Syscustomer);
        }
        
        public string getuploadFile(string Number, string SysCd) {
            return base.Channel.getuploadFile(Number, SysCd);
        }
        
        public void SaveUclLog(string EdiNo, testorm.MiniUiService.UCLEnum enumtype, string ep, string customercd, string ex, bool status, string UclOperator) {
            base.Channel.SaveUclLog(EdiNo, enumtype, ep, customercd, ex, status, UclOperator);
        }
        
        public bool exportEntryList(string sJson) {
            return base.Channel.exportEntryList(sJson);
        }
        
        public bool importManual(string tableName, string Json, string customercd) {
            return base.Channel.importManual(tableName, Json, customercd);
        }
        
        public string[] H2000ImportDeclare(string sJson, string customercd, int days, string date) {
            return base.Channel.H2000ImportDeclare(sJson, customercd, days, date);
        }
        
        public string importManualSingle(string json, string customercd) {
            return base.Channel.importManualSingle(json, customercd);
        }
        
        public void getStatus(string json, string customercd) {
            base.Channel.getStatus(json, customercd);
        }
        
        public void updateEntryId(string[] strList, string customercd) {
            base.Channel.updateEntryId(strList, customercd);
        }
        
        public bool updateHeadDtl(string id, string type, long DEH_ID, string Deh_Trade_Name, string Deh_Owner_Name, string Deh_Agent_Name, string Deh_Note_s, long Ded_Id, string Ded_g_Name, string Ded_g_Model) {
            return base.Channel.updateHeadDtl(id, type, DEH_ID, Deh_Trade_Name, Deh_Owner_Name, Deh_Agent_Name, Deh_Note_s, Ded_Id, Ded_g_Name, Ded_g_Model);
        }
        
        public string testUi() {
            return base.Channel.testUi();
        }
    }
}
