//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类BAS_PUBLIC_DETAILS。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("BAS_PUBLIC_DETAILS")]
    [Serializable]
    public partial class BAS_PUBLIC_DETAILS : Entity
    {
        #region Model
		private int _BPD_ID;
		private string _BPD_PBT_CD;
		private string _BPD_CD;
		private string _BPD_NM;
		private string _BPD_REMARK;
		private int? _BPD_SERIAL_NO;
		private string _BPD_AREA_DM;
		private string _SYS_CUSTOMER_CD;
		private string _INPUTER;
		private DateTime _INPUT_TM;
		private string _UPDATER;
		private DateTime? _UPDATE_TM;

		/// <summary>
		/// 系统代码
		/// </summary>
		[Field("BPD_ID")]
		public int BPD_ID
		{
			get{ return _BPD_ID; }
			set
			{
				this.OnPropertyValueChange("BPD_ID");
				this._BPD_ID = value;
			}
		}
		/// <summary>
		/// 类型
		/// </summary>
		[Field("BPD_PBT_CD")]
		public string BPD_PBT_CD
		{
			get{ return _BPD_PBT_CD; }
			set
			{
				this.OnPropertyValueChange("BPD_PBT_CD");
				this._BPD_PBT_CD = value;
			}
		}
		/// <summary>
		/// 代码
		/// </summary>
		[Field("BPD_CD")]
		public string BPD_CD
		{
			get{ return _BPD_CD; }
			set
			{
				this.OnPropertyValueChange("BPD_CD");
				this._BPD_CD = value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		[Field("BPD_NM")]
		public string BPD_NM
		{
			get{ return _BPD_NM; }
			set
			{
				this.OnPropertyValueChange("BPD_NM");
				this._BPD_NM = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("BPD_REMARK")]
		public string BPD_REMARK
		{
			get{ return _BPD_REMARK; }
			set
			{
				this.OnPropertyValueChange("BPD_REMARK");
				this._BPD_REMARK = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("BPD_SERIAL_NO")]
		public int? BPD_SERIAL_NO
		{
			get{ return _BPD_SERIAL_NO; }
			set
			{
				this.OnPropertyValueChange("BPD_SERIAL_NO");
				this._BPD_SERIAL_NO = value;
			}
		}
		/// <summary>
		/// 区域
		/// </summary>
		[Field("BPD_AREA_DM")]
		public string BPD_AREA_DM
		{
			get{ return _BPD_AREA_DM; }
			set
			{
				this.OnPropertyValueChange("BPD_AREA_DM");
				this._BPD_AREA_DM = value;
			}
		}
		/// <summary>
		/// 系统客户
		/// </summary>
		[Field("SYS_CUSTOMER_CD")]
		public string SYS_CUSTOMER_CD
		{
			get{ return _SYS_CUSTOMER_CD; }
			set
			{
				this.OnPropertyValueChange("SYS_CUSTOMER_CD");
				this._SYS_CUSTOMER_CD = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("INPUTER")]
		public string INPUTER
		{
			get{ return _INPUTER; }
			set
			{
				this.OnPropertyValueChange("INPUTER");
				this._INPUTER = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("INPUT_TM")]
		public DateTime INPUT_TM
		{
			get{ return _INPUT_TM; }
			set
			{
				this.OnPropertyValueChange("INPUT_TM");
				this._INPUT_TM = value;
			}
		}
		/// <summary>
		/// 更新人
		/// </summary>
		[Field("UPDATER")]
		public string UPDATER
		{
			get{ return _UPDATER; }
			set
			{
				this.OnPropertyValueChange("UPDATER");
				this._UPDATER = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("UPDATE_TM")]
		public DateTime? UPDATE_TM
		{
			get{ return _UPDATE_TM; }
			set
			{
				this.OnPropertyValueChange("UPDATE_TM");
				this._UPDATE_TM = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.BPD_ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.BPD_ID,
				_.BPD_PBT_CD,
				_.BPD_CD,
				_.BPD_NM,
				_.BPD_REMARK,
				_.BPD_SERIAL_NO,
				_.BPD_AREA_DM,
				_.SYS_CUSTOMER_CD,
				_.INPUTER,
				_.INPUT_TM,
				_.UPDATER,
				_.UPDATE_TM,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._BPD_ID,
				this._BPD_PBT_CD,
				this._BPD_CD,
				this._BPD_NM,
				this._BPD_REMARK,
				this._BPD_SERIAL_NO,
				this._BPD_AREA_DM,
				this._SYS_CUSTOMER_CD,
				this._INPUTER,
				this._INPUT_TM,
				this._UPDATER,
				this._UPDATE_TM,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "BAS_PUBLIC_DETAILS");
            /// <summary>
			/// 系统代码
			/// </summary>
			public readonly static Field BPD_ID = new Field("BPD_ID", "BAS_PUBLIC_DETAILS", "系统代码");
            /// <summary>
			/// 类型
			/// </summary>
			public readonly static Field BPD_PBT_CD = new Field("BPD_PBT_CD", "BAS_PUBLIC_DETAILS", "类型");
            /// <summary>
			/// 代码
			/// </summary>
			public readonly static Field BPD_CD = new Field("BPD_CD", "BAS_PUBLIC_DETAILS", "代码");
            /// <summary>
			/// 名称
			/// </summary>
			public readonly static Field BPD_NM = new Field("BPD_NM", "BAS_PUBLIC_DETAILS", "名称");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field BPD_REMARK = new Field("BPD_REMARK", "BAS_PUBLIC_DETAILS", "备注");
            /// <summary>
			/// 序号
			/// </summary>
			public readonly static Field BPD_SERIAL_NO = new Field("BPD_SERIAL_NO", "BAS_PUBLIC_DETAILS", "序号");
            /// <summary>
			/// 区域
			/// </summary>
			public readonly static Field BPD_AREA_DM = new Field("BPD_AREA_DM", "BAS_PUBLIC_DETAILS", "区域");
            /// <summary>
			/// 系统客户
			/// </summary>
			public readonly static Field SYS_CUSTOMER_CD = new Field("SYS_CUSTOMER_CD", "BAS_PUBLIC_DETAILS", "系统客户");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field INPUTER = new Field("INPUTER", "BAS_PUBLIC_DETAILS", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field INPUT_TM = new Field("INPUT_TM", "BAS_PUBLIC_DETAILS", "录入时间");
            /// <summary>
			/// 更新人
			/// </summary>
			public readonly static Field UPDATER = new Field("UPDATER", "BAS_PUBLIC_DETAILS", "更新人");
            /// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UPDATE_TM = new Field("UPDATE_TM", "BAS_PUBLIC_DETAILS", "更新时间");
        }
        #endregion
	}
}