//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类DC_EP_DEC_DTL。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("DC_EP_DEC_DTL")]
    [Serializable]
    public partial class DC_EP_DEC_DTL : Entity
    {
        #region Model
		private double _DED_ID;
		private double _DED_DEH_ID;
		private double? _DED_G_NO;
		private double? _DED_CONTR_ITEM;
		private string _DED_CODE_TT;
		private string _DED_CODE_S;
		private string _DED_G_NAME;
		private string _DED_G_MODEL;
		private string _DED_ORIGIN_COUNTRY;
		private double? _DED_G_QTY;
		private string _DED_G_UNIT;
		private double? _DED_QTY_1;
		private string _DED_UNIT_1;
		private double? _DED_QTY_2;
		private string _DED_UNIT_2;
		private string _DED_TRADE_CURR;
		private double? _DED_DECL_PRICE;
		private double? _DED_TRADE_TOTAL;
		private string _DED_DUTY_MODE;
		private string _DED_USE_TO;
		private string _DED_PRDT_NO;
		private string _DED_GOODS_NO;
		private double? _DED_GROSS_WT;
		private double? _DED_NET_WT;
		private double? _DED_WORK_USD;
		private string _INPUTER;
		private DateTime _INPUT_TM;
		private string _UPDATER;
		private DateTime? _UPDATE_TM;
		private string _SYS_CUSTOMER_CD;
		private string _DED_INGREDIENTS;
		private string _DED_DESTINATION_COUNTRY;
		private string _DED_GOOD_NO;
		private double? _DED_X_NO;

		/// <summary>
		/// 主键
		/// </summary>
		[Field("DED_ID")]
		public double DED_ID
		{
			get{ return _DED_ID; }
			set
			{
				this.OnPropertyValueChange("DED_ID");
				this._DED_ID = value;
			}
		}
		/// <summary>
		/// 报关表ID
		/// </summary>
		[Field("DED_DEH_ID")]
		public double DED_DEH_ID
		{
			get{ return _DED_DEH_ID; }
			set
			{
				this.OnPropertyValueChange("DED_DEH_ID");
				this._DED_DEH_ID = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("DED_G_NO")]
		public double? DED_G_NO
		{
			get{ return _DED_G_NO; }
			set
			{
				this.OnPropertyValueChange("DED_G_NO");
				this._DED_G_NO = value;
			}
		}
		/// <summary>
		/// 新贸序号,EDI客户端界面上的新贸序号
		/// </summary>
		[Field("DED_CONTR_ITEM")]
		public double? DED_CONTR_ITEM
		{
			get{ return _DED_CONTR_ITEM; }
			set
			{
				this.OnPropertyValueChange("DED_CONTR_ITEM");
				this._DED_CONTR_ITEM = value;
			}
		}
		/// <summary>
		/// 商品编号
		/// </summary>
		[Field("DED_CODE_TT")]
		public string DED_CODE_TT
		{
			get{ return _DED_CODE_TT; }
			set
			{
				this.OnPropertyValueChange("DED_CODE_TT");
				this._DED_CODE_TT = value;
			}
		}
		/// <summary>
		/// 附加编号
		/// </summary>
		[Field("DED_CODE_S")]
		public string DED_CODE_S
		{
			get{ return _DED_CODE_S; }
			set
			{
				this.OnPropertyValueChange("DED_CODE_S");
				this._DED_CODE_S = value;
			}
		}
		/// <summary>
		/// 商品名称
		/// </summary>
		[Field("DED_G_NAME")]
		public string DED_G_NAME
		{
			get{ return _DED_G_NAME; }
			set
			{
				this.OnPropertyValueChange("DED_G_NAME");
				this._DED_G_NAME = value;
			}
		}
		/// <summary>
		/// 商品规格型号
		/// </summary>
		[Field("DED_G_MODEL")]
		public string DED_G_MODEL
		{
			get{ return _DED_G_MODEL; }
			set
			{
				this.OnPropertyValueChange("DED_G_MODEL");
				this._DED_G_MODEL = value;
			}
		}
		/// <summary>
		/// 原产国/目的国,对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段
		/// </summary>
		[Field("DED_ORIGIN_COUNTRY")]
		public string DED_ORIGIN_COUNTRY
		{
			get{ return _DED_ORIGIN_COUNTRY; }
			set
			{
				this.OnPropertyValueChange("DED_ORIGIN_COUNTRY");
				this._DED_ORIGIN_COUNTRY = value;
			}
		}
		/// <summary>
		/// 申报数量
		/// </summary>
		[Field("DED_G_QTY")]
		public double? DED_G_QTY
		{
			get{ return _DED_G_QTY; }
			set
			{
				this.OnPropertyValueChange("DED_G_QTY");
				this._DED_G_QTY = value;
			}
		}
		/// <summary>
		/// 申报计量单位,对应海关参数库中UNIT中的UNIT_CODE字段
		/// </summary>
		[Field("DED_G_UNIT")]
		public string DED_G_UNIT
		{
			get{ return _DED_G_UNIT; }
			set
			{
				this.OnPropertyValueChange("DED_G_UNIT");
				this._DED_G_UNIT = value;
			}
		}
		/// <summary>
		/// 法定数量
		/// </summary>
		[Field("DED_QTY_1")]
		public double? DED_QTY_1
		{
			get{ return _DED_QTY_1; }
			set
			{
				this.OnPropertyValueChange("DED_QTY_1");
				this._DED_QTY_1 = value;
			}
		}
		/// <summary>
		/// 法定计量单位(第一计量单位),对应海关参数库中UNIT中的UNIT_CODE字段
		/// </summary>
		[Field("DED_UNIT_1")]
		public string DED_UNIT_1
		{
			get{ return _DED_UNIT_1; }
			set
			{
				this.OnPropertyValueChange("DED_UNIT_1");
				this._DED_UNIT_1 = value;
			}
		}
		/// <summary>
		/// 第二数量
		/// </summary>
		[Field("DED_QTY_2")]
		public double? DED_QTY_2
		{
			get{ return _DED_QTY_2; }
			set
			{
				this.OnPropertyValueChange("DED_QTY_2");
				this._DED_QTY_2 = value;
			}
		}
		/// <summary>
		/// 第二计量单位,对应海关参数库中UNIT中的UNIT_CODE字段
		/// </summary>
		[Field("DED_UNIT_2")]
		public string DED_UNIT_2
		{
			get{ return _DED_UNIT_2; }
			set
			{
				this.OnPropertyValueChange("DED_UNIT_2");
				this._DED_UNIT_2 = value;
			}
		}
		/// <summary>
		/// 成交币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
		/// </summary>
		[Field("DED_TRADE_CURR")]
		public string DED_TRADE_CURR
		{
			get{ return _DED_TRADE_CURR; }
			set
			{
				this.OnPropertyValueChange("DED_TRADE_CURR");
				this._DED_TRADE_CURR = value;
			}
		}
		/// <summary>
		/// 申报单价
		/// </summary>
		[Field("DED_DECL_PRICE")]
		public double? DED_DECL_PRICE
		{
			get{ return _DED_DECL_PRICE; }
			set
			{
				this.OnPropertyValueChange("DED_DECL_PRICE");
				this._DED_DECL_PRICE = value;
			}
		}
		/// <summary>
		/// 成交总价
		/// </summary>
		[Field("DED_TRADE_TOTAL")]
		public double? DED_TRADE_TOTAL
		{
			get{ return _DED_TRADE_TOTAL; }
			set
			{
				this.OnPropertyValueChange("DED_TRADE_TOTAL");
				this._DED_TRADE_TOTAL = value;
			}
		}
		/// <summary>
		/// 征减免税方式
		/// </summary>
		[Field("DED_DUTY_MODE")]
		public string DED_DUTY_MODE
		{
			get{ return _DED_DUTY_MODE; }
			set
			{
				this.OnPropertyValueChange("DED_DUTY_MODE");
				this._DED_DUTY_MODE = value;
			}
		}
		/// <summary>
		/// 用途,对应海关参数库中商品用途代码表(USER_TO)中的USE_TO_COD字段
		/// </summary>
		[Field("DED_USE_TO")]
		public string DED_USE_TO
		{
			get{ return _DED_USE_TO; }
			set
			{
				this.OnPropertyValueChange("DED_USE_TO");
				this._DED_USE_TO = value;
			}
		}
		/// <summary>
		/// 加工成品版本号
		/// </summary>
		[Field("DED_PRDT_NO")]
		public string DED_PRDT_NO
		{
			get{ return _DED_PRDT_NO; }
			set
			{
				this.OnPropertyValueChange("DED_PRDT_NO");
				this._DED_PRDT_NO = value;
			}
		}
		/// <summary>
		/// 加工料件/成品货号
		/// </summary>
		[Field("DED_GOODS_NO")]
		public string DED_GOODS_NO
		{
			get{ return _DED_GOODS_NO; }
			set
			{
				this.OnPropertyValueChange("DED_GOODS_NO");
				this._DED_GOODS_NO = value;
			}
		}
		/// <summary>
		/// 毛重
		/// </summary>
		[Field("DED_GROSS_WT")]
		public double? DED_GROSS_WT
		{
			get{ return _DED_GROSS_WT; }
			set
			{
				this.OnPropertyValueChange("DED_GROSS_WT");
				this._DED_GROSS_WT = value;
			}
		}
		/// <summary>
		/// 净重
		/// </summary>
		[Field("DED_NET_WT")]
		public double? DED_NET_WT
		{
			get{ return _DED_NET_WT; }
			set
			{
				this.OnPropertyValueChange("DED_NET_WT");
				this._DED_NET_WT = value;
			}
		}
		/// <summary>
		/// 工缴费
		/// </summary>
		[Field("DED_WORK_USD")]
		public double? DED_WORK_USD
		{
			get{ return _DED_WORK_USD; }
			set
			{
				this.OnPropertyValueChange("DED_WORK_USD");
				this._DED_WORK_USD = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("INPUTER")]
		public string INPUTER
		{
			get{ return _INPUTER; }
			set
			{
				this.OnPropertyValueChange("INPUTER");
				this._INPUTER = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("INPUT_TM")]
		public DateTime INPUT_TM
		{
			get{ return _INPUT_TM; }
			set
			{
				this.OnPropertyValueChange("INPUT_TM");
				this._INPUT_TM = value;
			}
		}
		/// <summary>
		/// 更新人
		/// </summary>
		[Field("UPDATER")]
		public string UPDATER
		{
			get{ return _UPDATER; }
			set
			{
				this.OnPropertyValueChange("UPDATER");
				this._UPDATER = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("UPDATE_TM")]
		public DateTime? UPDATE_TM
		{
			get{ return _UPDATE_TM; }
			set
			{
				this.OnPropertyValueChange("UPDATE_TM");
				this._UPDATE_TM = value;
			}
		}
		/// <summary>
		/// 系统代码
		/// </summary>
		[Field("SYS_CUSTOMER_CD")]
		public string SYS_CUSTOMER_CD
		{
			get{ return _SYS_CUSTOMER_CD; }
			set
			{
				this.OnPropertyValueChange("SYS_CUSTOMER_CD");
				this._SYS_CUSTOMER_CD = value;
			}
		}
		/// <summary>
		/// 申报要素
		/// </summary>
		[Field("DED_INGREDIENTS")]
		public string DED_INGREDIENTS
		{
			get{ return _DED_INGREDIENTS; }
			set
			{
				this.OnPropertyValueChange("DED_INGREDIENTS");
				this._DED_INGREDIENTS = value;
			}
		}
		/// <summary>
		/// 原产国/目的国(进口对应目的国,出口对应原产国对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段)
		/// </summary>
		[Field("DED_DESTINATION_COUNTRY")]
		public string DED_DESTINATION_COUNTRY
		{
			get{ return _DED_DESTINATION_COUNTRY; }
			set
			{
				this.OnPropertyValueChange("DED_DESTINATION_COUNTRY");
				this._DED_DESTINATION_COUNTRY = value;
			}
		}
		/// <summary>
		/// 关联编号(同商品维护表里的dbc_good_no)
		/// </summary>
		[Field("DED_GOOD_NO")]
		public string DED_GOOD_NO
		{
			get{ return _DED_GOOD_NO; }
			set
			{
				this.OnPropertyValueChange("DED_GOOD_NO");
				this._DED_GOOD_NO = value;
			}
		}
		/// <summary>
		/// 序列号
		/// </summary>
		[Field("DED_X_NO")]
		public double? DED_X_NO
		{
			get{ return _DED_X_NO; }
			set
			{
				this.OnPropertyValueChange("DED_X_NO");
				this._DED_X_NO = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.DED_ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.DED_ID,
				_.DED_DEH_ID,
				_.DED_G_NO,
				_.DED_CONTR_ITEM,
				_.DED_CODE_TT,
				_.DED_CODE_S,
				_.DED_G_NAME,
				_.DED_G_MODEL,
				_.DED_ORIGIN_COUNTRY,
				_.DED_G_QTY,
				_.DED_G_UNIT,
				_.DED_QTY_1,
				_.DED_UNIT_1,
				_.DED_QTY_2,
				_.DED_UNIT_2,
				_.DED_TRADE_CURR,
				_.DED_DECL_PRICE,
				_.DED_TRADE_TOTAL,
				_.DED_DUTY_MODE,
				_.DED_USE_TO,
				_.DED_PRDT_NO,
				_.DED_GOODS_NO,
				_.DED_GROSS_WT,
				_.DED_NET_WT,
				_.DED_WORK_USD,
				_.INPUTER,
				_.INPUT_TM,
				_.UPDATER,
				_.UPDATE_TM,
				_.SYS_CUSTOMER_CD,
				_.DED_INGREDIENTS,
				_.DED_DESTINATION_COUNTRY,
				_.DED_GOOD_NO,
				_.DED_X_NO,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._DED_ID,
				this._DED_DEH_ID,
				this._DED_G_NO,
				this._DED_CONTR_ITEM,
				this._DED_CODE_TT,
				this._DED_CODE_S,
				this._DED_G_NAME,
				this._DED_G_MODEL,
				this._DED_ORIGIN_COUNTRY,
				this._DED_G_QTY,
				this._DED_G_UNIT,
				this._DED_QTY_1,
				this._DED_UNIT_1,
				this._DED_QTY_2,
				this._DED_UNIT_2,
				this._DED_TRADE_CURR,
				this._DED_DECL_PRICE,
				this._DED_TRADE_TOTAL,
				this._DED_DUTY_MODE,
				this._DED_USE_TO,
				this._DED_PRDT_NO,
				this._DED_GOODS_NO,
				this._DED_GROSS_WT,
				this._DED_NET_WT,
				this._DED_WORK_USD,
				this._INPUTER,
				this._INPUT_TM,
				this._UPDATER,
				this._UPDATE_TM,
				this._SYS_CUSTOMER_CD,
				this._DED_INGREDIENTS,
				this._DED_DESTINATION_COUNTRY,
				this._DED_GOOD_NO,
				this._DED_X_NO,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DC_EP_DEC_DTL");
            /// <summary>
			/// 主键
			/// </summary>
			public readonly static Field DED_ID = new Field("DED_ID", "DC_EP_DEC_DTL", "主键");
            /// <summary>
			/// 报关表ID
			/// </summary>
			public readonly static Field DED_DEH_ID = new Field("DED_DEH_ID", "DC_EP_DEC_DTL", "报关表ID");
            /// <summary>
			/// 序号
			/// </summary>
			public readonly static Field DED_G_NO = new Field("DED_G_NO", "DC_EP_DEC_DTL", "序号");
            /// <summary>
			/// 新贸序号,EDI客户端界面上的新贸序号
			/// </summary>
			public readonly static Field DED_CONTR_ITEM = new Field("DED_CONTR_ITEM", "DC_EP_DEC_DTL", "新贸序号,EDI客户端界面上的新贸序号");
            /// <summary>
			/// 商品编号
			/// </summary>
			public readonly static Field DED_CODE_TT = new Field("DED_CODE_TT", "DC_EP_DEC_DTL", "商品编号");
            /// <summary>
			/// 附加编号
			/// </summary>
			public readonly static Field DED_CODE_S = new Field("DED_CODE_S", "DC_EP_DEC_DTL", "附加编号");
            /// <summary>
			/// 商品名称
			/// </summary>
			public readonly static Field DED_G_NAME = new Field("DED_G_NAME", "DC_EP_DEC_DTL", "商品名称");
            /// <summary>
			/// 商品规格型号
			/// </summary>
			public readonly static Field DED_G_MODEL = new Field("DED_G_MODEL", "DC_EP_DEC_DTL", "商品规格型号");
            /// <summary>
			/// 原产国/目的国,对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段
			/// </summary>
			public readonly static Field DED_ORIGIN_COUNTRY = new Field("DED_ORIGIN_COUNTRY", "DC_EP_DEC_DTL", "原产国/目的国,对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段");
            /// <summary>
			/// 申报数量
			/// </summary>
			public readonly static Field DED_G_QTY = new Field("DED_G_QTY", "DC_EP_DEC_DTL", "申报数量");
            /// <summary>
			/// 申报计量单位,对应海关参数库中UNIT中的UNIT_CODE字段
			/// </summary>
			public readonly static Field DED_G_UNIT = new Field("DED_G_UNIT", "DC_EP_DEC_DTL", "申报计量单位,对应海关参数库中UNIT中的UNIT_CODE字段");
            /// <summary>
			/// 法定数量
			/// </summary>
			public readonly static Field DED_QTY_1 = new Field("DED_QTY_1", "DC_EP_DEC_DTL", "法定数量");
            /// <summary>
			/// 法定计量单位(第一计量单位),对应海关参数库中UNIT中的UNIT_CODE字段
			/// </summary>
			public readonly static Field DED_UNIT_1 = new Field("DED_UNIT_1", "DC_EP_DEC_DTL", "法定计量单位(第一计量单位),对应海关参数库中UNIT中的UNIT_CODE字段");
            /// <summary>
			/// 第二数量
			/// </summary>
			public readonly static Field DED_QTY_2 = new Field("DED_QTY_2", "DC_EP_DEC_DTL", "第二数量");
            /// <summary>
			/// 第二计量单位,对应海关参数库中UNIT中的UNIT_CODE字段
			/// </summary>
			public readonly static Field DED_UNIT_2 = new Field("DED_UNIT_2", "DC_EP_DEC_DTL", "第二计量单位,对应海关参数库中UNIT中的UNIT_CODE字段");
            /// <summary>
			/// 成交币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
			/// </summary>
			public readonly static Field DED_TRADE_CURR = new Field("DED_TRADE_CURR", "DC_EP_DEC_DTL", "成交币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段");
            /// <summary>
			/// 申报单价
			/// </summary>
			public readonly static Field DED_DECL_PRICE = new Field("DED_DECL_PRICE", "DC_EP_DEC_DTL", "申报单价");
            /// <summary>
			/// 成交总价
			/// </summary>
			public readonly static Field DED_TRADE_TOTAL = new Field("DED_TRADE_TOTAL", "DC_EP_DEC_DTL", "成交总价");
            /// <summary>
			/// 征减免税方式
			/// </summary>
			public readonly static Field DED_DUTY_MODE = new Field("DED_DUTY_MODE", "DC_EP_DEC_DTL", "征减免税方式");
            /// <summary>
			/// 用途,对应海关参数库中商品用途代码表(USER_TO)中的USE_TO_COD字段
			/// </summary>
			public readonly static Field DED_USE_TO = new Field("DED_USE_TO", "DC_EP_DEC_DTL", "用途,对应海关参数库中商品用途代码表(USER_TO)中的USE_TO_COD字段");
            /// <summary>
			/// 加工成品版本号
			/// </summary>
			public readonly static Field DED_PRDT_NO = new Field("DED_PRDT_NO", "DC_EP_DEC_DTL", "加工成品版本号");
            /// <summary>
			/// 加工料件/成品货号
			/// </summary>
			public readonly static Field DED_GOODS_NO = new Field("DED_GOODS_NO", "DC_EP_DEC_DTL", "加工料件/成品货号");
            /// <summary>
			/// 毛重
			/// </summary>
			public readonly static Field DED_GROSS_WT = new Field("DED_GROSS_WT", "DC_EP_DEC_DTL", "毛重");
            /// <summary>
			/// 净重
			/// </summary>
			public readonly static Field DED_NET_WT = new Field("DED_NET_WT", "DC_EP_DEC_DTL", "净重");
            /// <summary>
			/// 工缴费
			/// </summary>
			public readonly static Field DED_WORK_USD = new Field("DED_WORK_USD", "DC_EP_DEC_DTL", "工缴费");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field INPUTER = new Field("INPUTER", "DC_EP_DEC_DTL", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field INPUT_TM = new Field("INPUT_TM", "DC_EP_DEC_DTL", "录入时间");
            /// <summary>
			/// 更新人
			/// </summary>
			public readonly static Field UPDATER = new Field("UPDATER", "DC_EP_DEC_DTL", "更新人");
            /// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UPDATE_TM = new Field("UPDATE_TM", "DC_EP_DEC_DTL", "更新时间");
            /// <summary>
			/// 系统代码
			/// </summary>
			public readonly static Field SYS_CUSTOMER_CD = new Field("SYS_CUSTOMER_CD", "DC_EP_DEC_DTL", "系统代码");
            /// <summary>
			/// 申报要素
			/// </summary>
			public readonly static Field DED_INGREDIENTS = new Field("DED_INGREDIENTS", "DC_EP_DEC_DTL", "申报要素");
            /// <summary>
			/// 原产国/目的国(进口对应目的国,出口对应原产国对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段)
			/// </summary>
			public readonly static Field DED_DESTINATION_COUNTRY = new Field("DED_DESTINATION_COUNTRY", "DC_EP_DEC_DTL", "原产国/目的国(进口对应目的国,出口对应原产国对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段)");
            /// <summary>
			/// 关联编号(同商品维护表里的dbc_good_no)
			/// </summary>
			public readonly static Field DED_GOOD_NO = new Field("DED_GOOD_NO", "DC_EP_DEC_DTL", "关联编号(同商品维护表里的dbc_good_no)");
            /// <summary>
			/// 序列号
			/// </summary>
			public readonly static Field DED_X_NO = new Field("DED_X_NO", "DC_EP_DEC_DTL", "序列号");
        }
        #endregion
	}
}