//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类DC_EP_DEC_EDOCRELATION。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("DC_EP_DEC_EDOCRELATION")]
    [Serializable]
    public partial class DC_EP_DEC_EDOCRELATION : Entity
    {
        #region Model
		private int _DDE_ID;
		private int _DDE_DEH_ID;
		private string _DDE_FILE_TYPE;
		private string _DDE_FILE_NAME;
		private string _DDE_EDOCOWNERCODE;
		private string _DDE_EDOCOWNERNAME;
		private string _DDE_OPNOTE;
		private string _INPUTER;
		private DateTime _INPUT_TM;
		private string _UPDATER;
		private DateTime? _UPDATE_TM;
		private string _SYS_CUSTOMER_CD;

		/// <summary>
		/// 主键
		/// </summary>
		[Field("DDE_ID")]
		public int DDE_ID
		{
			get{ return _DDE_ID; }
			set
			{
				this.OnPropertyValueChange("DDE_ID");
				this._DDE_ID = value;
			}
		}
		/// <summary>
		/// 报关表ID
		/// </summary>
		[Field("DDE_DEH_ID")]
		public int DDE_DEH_ID
		{
			get{ return _DDE_DEH_ID; }
			set
			{
				this.OnPropertyValueChange("DDE_DEH_ID");
				this._DDE_DEH_ID = value;
			}
		}
		/// <summary>
		/// 单据类型:1:发票2:装箱单3:提运单4:合同5:其他16:其他27:其他38:代理报关委托协议A:电子代理委托协议B:减免税货物税款担保证明C:减免税货物税款担保延期证明
		/// </summary>
		[Field("DDE_FILE_TYPE")]
		public string DDE_FILE_TYPE
		{
			get{ return _DDE_FILE_TYPE; }
			set
			{
				this.OnPropertyValueChange("DDE_FILE_TYPE");
				this._DDE_FILE_TYPE = value;
			}
		}
		/// <summary>
		/// 随附单据编号,如果单据类型为A或B或C,那么必填;否则不填
		/// </summary>
		[Field("DDE_FILE_NAME")]
		public string DDE_FILE_NAME
		{
			get{ return _DDE_FILE_NAME; }
			set
			{
				this.OnPropertyValueChange("DDE_FILE_NAME");
				this._DDE_FILE_NAME = value;
			}
		}
		/// <summary>
		/// 所属单位代码,10位经营单位代码
		/// </summary>
		[Field("DDE_EDOCOWNERCODE")]
		public string DDE_EDOCOWNERCODE
		{
			get{ return _DDE_EDOCOWNERCODE; }
			set
			{
				this.OnPropertyValueChange("DDE_EDOCOWNERCODE");
				this._DDE_EDOCOWNERCODE = value;
			}
		}
		/// <summary>
		/// 所属单位名称,经营单位名称
		/// </summary>
		[Field("DDE_EDOCOWNERNAME")]
		public string DDE_EDOCOWNERNAME
		{
			get{ return _DDE_EDOCOWNERNAME; }
			set
			{
				this.OnPropertyValueChange("DDE_EDOCOWNERNAME");
				this._DDE_EDOCOWNERNAME = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("DDE_OPNOTE")]
		public string DDE_OPNOTE
		{
			get{ return _DDE_OPNOTE; }
			set
			{
				this.OnPropertyValueChange("DDE_OPNOTE");
				this._DDE_OPNOTE = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("INPUTER")]
		public string INPUTER
		{
			get{ return _INPUTER; }
			set
			{
				this.OnPropertyValueChange("INPUTER");
				this._INPUTER = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("INPUT_TM")]
		public DateTime INPUT_TM
		{
			get{ return _INPUT_TM; }
			set
			{
				this.OnPropertyValueChange("INPUT_TM");
				this._INPUT_TM = value;
			}
		}
		/// <summary>
		/// 更新人
		/// </summary>
		[Field("UPDATER")]
		public string UPDATER
		{
			get{ return _UPDATER; }
			set
			{
				this.OnPropertyValueChange("UPDATER");
				this._UPDATER = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("UPDATE_TM")]
		public DateTime? UPDATE_TM
		{
			get{ return _UPDATE_TM; }
			set
			{
				this.OnPropertyValueChange("UPDATE_TM");
				this._UPDATE_TM = value;
			}
		}
		/// <summary>
		/// 系统代码
		/// </summary>
		[Field("SYS_CUSTOMER_CD")]
		public string SYS_CUSTOMER_CD
		{
			get{ return _SYS_CUSTOMER_CD; }
			set
			{
				this.OnPropertyValueChange("SYS_CUSTOMER_CD");
				this._SYS_CUSTOMER_CD = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.DDE_ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.DDE_ID,
				_.DDE_DEH_ID,
				_.DDE_FILE_TYPE,
				_.DDE_FILE_NAME,
				_.DDE_EDOCOWNERCODE,
				_.DDE_EDOCOWNERNAME,
				_.DDE_OPNOTE,
				_.INPUTER,
				_.INPUT_TM,
				_.UPDATER,
				_.UPDATE_TM,
				_.SYS_CUSTOMER_CD,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._DDE_ID,
				this._DDE_DEH_ID,
				this._DDE_FILE_TYPE,
				this._DDE_FILE_NAME,
				this._DDE_EDOCOWNERCODE,
				this._DDE_EDOCOWNERNAME,
				this._DDE_OPNOTE,
				this._INPUTER,
				this._INPUT_TM,
				this._UPDATER,
				this._UPDATE_TM,
				this._SYS_CUSTOMER_CD,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DC_EP_DEC_EDOCRELATION");
            /// <summary>
			/// 主键
			/// </summary>
			public readonly static Field DDE_ID = new Field("DDE_ID", "DC_EP_DEC_EDOCRELATION", "主键");
            /// <summary>
			/// 报关表ID
			/// </summary>
			public readonly static Field DDE_DEH_ID = new Field("DDE_DEH_ID", "DC_EP_DEC_EDOCRELATION", "报关表ID");
            /// <summary>
			/// 单据类型:1:发票2:装箱单3:提运单4:合同5:其他16:其他27:其他38:代理报关委托协议A:电子代理委托协议B:减免税货物税款担保证明C:减免税货物税款担保延期证明
			/// </summary>
			public readonly static Field DDE_FILE_TYPE = new Field("DDE_FILE_TYPE", "DC_EP_DEC_EDOCRELATION", "单据类型:1:发票2:装箱单3:提运单4:合同5:其他16:其他27:其他38:代理报关委托协议A:电子代理委托协议B:减免税货物税款担保证明C:减免税货物税款担保延期证明");
            /// <summary>
			/// 随附单据编号,如果单据类型为A或B或C,那么必填;否则不填
			/// </summary>
			public readonly static Field DDE_FILE_NAME = new Field("DDE_FILE_NAME", "DC_EP_DEC_EDOCRELATION", "随附单据编号,如果单据类型为A或B或C,那么必填;否则不填");
            /// <summary>
			/// 所属单位代码,10位经营单位代码
			/// </summary>
			public readonly static Field DDE_EDOCOWNERCODE = new Field("DDE_EDOCOWNERCODE", "DC_EP_DEC_EDOCRELATION", "所属单位代码,10位经营单位代码");
            /// <summary>
			/// 所属单位名称,经营单位名称
			/// </summary>
			public readonly static Field DDE_EDOCOWNERNAME = new Field("DDE_EDOCOWNERNAME", "DC_EP_DEC_EDOCRELATION", "所属单位名称,经营单位名称");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field DDE_OPNOTE = new Field("DDE_OPNOTE", "DC_EP_DEC_EDOCRELATION", "备注");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field INPUTER = new Field("INPUTER", "DC_EP_DEC_EDOCRELATION", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field INPUT_TM = new Field("INPUT_TM", "DC_EP_DEC_EDOCRELATION", "录入时间");
            /// <summary>
			/// 更新人
			/// </summary>
			public readonly static Field UPDATER = new Field("UPDATER", "DC_EP_DEC_EDOCRELATION", "更新人");
            /// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UPDATE_TM = new Field("UPDATE_TM", "DC_EP_DEC_EDOCRELATION", "更新时间");
            /// <summary>
			/// 系统代码
			/// </summary>
			public readonly static Field SYS_CUSTOMER_CD = new Field("SYS_CUSTOMER_CD", "DC_EP_DEC_EDOCRELATION", "系统代码");
        }
        #endregion
	}
}