//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类DC_EP_DEC_CONTAINER。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("DC_EP_DEC_CONTAINER")]
    [Serializable]
    public partial class DC_EP_DEC_CONTAINER : Entity
    {
        #region Model
		private int _DEC_ID;
		private int _DEC_DEH_ID;
		private string _DEC_CONTAINER_NO;
		private string _DEC_CONTAINER_MODEL;
		private int? _DEC_CONTAINER_WT;
		private string _INPUTER;
		private DateTime _INPUT_TM;
		private string _UPDATER;
		private DateTime? _UPDATE_TM;
		private string _SYS_CUSTOMER_CD;
		private string _DEC_SEAL_NO;
		private string _DEC_CONT_TYPE;
		private string _DEC_CHECK_USER;

		/// <summary>
		/// 主键
		/// </summary>
		[Field("DEC_ID")]
		public int DEC_ID
		{
			get{ return _DEC_ID; }
			set
			{
				this.OnPropertyValueChange("DEC_ID");
				this._DEC_ID = value;
			}
		}
		/// <summary>
		/// 报关表ID
		/// </summary>
		[Field("DEC_DEH_ID")]
		public int DEC_DEH_ID
		{
			get{ return _DEC_DEH_ID; }
			set
			{
				this.OnPropertyValueChange("DEC_DEH_ID");
				this._DEC_DEH_ID = value;
			}
		}
		/// <summary>
		/// 集装箱号
		/// </summary>
		[Field("DEC_CONTAINER_NO")]
		public string DEC_CONTAINER_NO
		{
			get{ return _DEC_CONTAINER_NO; }
			set
			{
				this.OnPropertyValueChange("DEC_CONTAINER_NO");
				this._DEC_CONTAINER_NO = value;
			}
		}
		/// <summary>
		/// 集装箱规格
		/// </summary>
		[Field("DEC_CONTAINER_MODEL")]
		public string DEC_CONTAINER_MODEL
		{
			get{ return _DEC_CONTAINER_MODEL; }
			set
			{
				this.OnPropertyValueChange("DEC_CONTAINER_MODEL");
				this._DEC_CONTAINER_MODEL = value;
			}
		}
		/// <summary>
		/// 集装箱自重
		/// </summary>
		[Field("DEC_CONTAINER_WT")]
		public int? DEC_CONTAINER_WT
		{
			get{ return _DEC_CONTAINER_WT; }
			set
			{
				this.OnPropertyValueChange("DEC_CONTAINER_WT");
				this._DEC_CONTAINER_WT = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("INPUTER")]
		public string INPUTER
		{
			get{ return _INPUTER; }
			set
			{
				this.OnPropertyValueChange("INPUTER");
				this._INPUTER = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("INPUT_TM")]
		public DateTime INPUT_TM
		{
			get{ return _INPUT_TM; }
			set
			{
				this.OnPropertyValueChange("INPUT_TM");
				this._INPUT_TM = value;
			}
		}
		/// <summary>
		/// 更新人
		/// </summary>
		[Field("UPDATER")]
		public string UPDATER
		{
			get{ return _UPDATER; }
			set
			{
				this.OnPropertyValueChange("UPDATER");
				this._UPDATER = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("UPDATE_TM")]
		public DateTime? UPDATE_TM
		{
			get{ return _UPDATE_TM; }
			set
			{
				this.OnPropertyValueChange("UPDATE_TM");
				this._UPDATE_TM = value;
			}
		}
		/// <summary>
		/// 系统代码
		/// </summary>
		[Field("SYS_CUSTOMER_CD")]
		public string SYS_CUSTOMER_CD
		{
			get{ return _SYS_CUSTOMER_CD; }
			set
			{
				this.OnPropertyValueChange("SYS_CUSTOMER_CD");
				this._SYS_CUSTOMER_CD = value;
			}
		}
		/// <summary>
		/// 箱封号
		/// </summary>
		[Field("DEC_SEAL_NO")]
		public string DEC_SEAL_NO
		{
			get{ return _DEC_SEAL_NO; }
			set
			{
				this.OnPropertyValueChange("DEC_SEAL_NO");
				this._DEC_SEAL_NO = value;
			}
		}
		/// <summary>
		/// 箱型
		/// </summary>
		[Field("DEC_CONT_TYPE")]
		public string DEC_CONT_TYPE
		{
			get{ return _DEC_CONT_TYPE; }
			set
			{
				this.OnPropertyValueChange("DEC_CONT_TYPE");
				this._DEC_CONT_TYPE = value;
			}
		}
		/// <summary>
		/// 查验人
		/// </summary>
		[Field("DEC_CHECK_USER")]
		public string DEC_CHECK_USER
		{
			get{ return _DEC_CHECK_USER; }
			set
			{
				this.OnPropertyValueChange("DEC_CHECK_USER");
				this._DEC_CHECK_USER = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.DEC_ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.DEC_ID,
				_.DEC_DEH_ID,
				_.DEC_CONTAINER_NO,
				_.DEC_CONTAINER_MODEL,
				_.DEC_CONTAINER_WT,
				_.INPUTER,
				_.INPUT_TM,
				_.UPDATER,
				_.UPDATE_TM,
				_.SYS_CUSTOMER_CD,
				_.DEC_SEAL_NO,
				_.DEC_CONT_TYPE,
				_.DEC_CHECK_USER,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._DEC_ID,
				this._DEC_DEH_ID,
				this._DEC_CONTAINER_NO,
				this._DEC_CONTAINER_MODEL,
				this._DEC_CONTAINER_WT,
				this._INPUTER,
				this._INPUT_TM,
				this._UPDATER,
				this._UPDATE_TM,
				this._SYS_CUSTOMER_CD,
				this._DEC_SEAL_NO,
				this._DEC_CONT_TYPE,
				this._DEC_CHECK_USER,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DC_EP_DEC_CONTAINER");
            /// <summary>
			/// 主键
			/// </summary>
			public readonly static Field DEC_ID = new Field("DEC_ID", "DC_EP_DEC_CONTAINER", "主键");
            /// <summary>
			/// 报关表ID
			/// </summary>
			public readonly static Field DEC_DEH_ID = new Field("DEC_DEH_ID", "DC_EP_DEC_CONTAINER", "报关表ID");
            /// <summary>
			/// 集装箱号
			/// </summary>
			public readonly static Field DEC_CONTAINER_NO = new Field("DEC_CONTAINER_NO", "DC_EP_DEC_CONTAINER", "集装箱号");
            /// <summary>
			/// 集装箱规格
			/// </summary>
			public readonly static Field DEC_CONTAINER_MODEL = new Field("DEC_CONTAINER_MODEL", "DC_EP_DEC_CONTAINER", "集装箱规格");
            /// <summary>
			/// 集装箱自重
			/// </summary>
			public readonly static Field DEC_CONTAINER_WT = new Field("DEC_CONTAINER_WT", "DC_EP_DEC_CONTAINER", "集装箱自重");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field INPUTER = new Field("INPUTER", "DC_EP_DEC_CONTAINER", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field INPUT_TM = new Field("INPUT_TM", "DC_EP_DEC_CONTAINER", "录入时间");
            /// <summary>
			/// 更新人
			/// </summary>
			public readonly static Field UPDATER = new Field("UPDATER", "DC_EP_DEC_CONTAINER", "更新人");
            /// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UPDATE_TM = new Field("UPDATE_TM", "DC_EP_DEC_CONTAINER", "更新时间");
            /// <summary>
			/// 系统代码
			/// </summary>
			public readonly static Field SYS_CUSTOMER_CD = new Field("SYS_CUSTOMER_CD", "DC_EP_DEC_CONTAINER", "系统代码");
            /// <summary>
			/// 箱封号
			/// </summary>
			public readonly static Field DEC_SEAL_NO = new Field("DEC_SEAL_NO", "DC_EP_DEC_CONTAINER", "箱封号");
            /// <summary>
			/// 箱型
			/// </summary>
			public readonly static Field DEC_CONT_TYPE = new Field("DEC_CONT_TYPE", "DC_EP_DEC_CONTAINER", "箱型");
            /// <summary>
			/// 查验人
			/// </summary>
			public readonly static Field DEC_CHECK_USER = new Field("DEC_CHECK_USER", "DC_EP_DEC_CONTAINER", "查验人");
        }
        #endregion
	}
}