//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类DC_EP_DEC_HEAD_O。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("DC_EP_DEC_HEAD")]
    [Serializable]
    public partial class DC_EP_DEC_HEAD_O : Entity
    {
        #region Model
        private long _DEH_ID;
		private string _DEH_ENTRY_NO;
		private string _DEH_TRADE_CO;
		private string _DEH_TRADE_NAME;
		private string _DEH_DISTRICT_CODE;
		private string _DEH_OWNER_CODE;
		private string _DEH_OWNER_NAME;
		private string _DEH_AGENT_CODE;
		private string _DEH_AGENT_NAME;
		private string _DEH_TRAF_MODE;
		private string _DEH_I_E_PORT;
		private string _DEH_DISTINATE_PORT;
		private string _DEH_TRAF_NAME;
		private string _DEH_CONTR_NO;
		private double? _DEH_IN_RATIO;
		private string _DEH_BILL_NO;
		private string _DEH_TRADE_COUNTRY;
		private string _DEH_TRADE_MODE;
		private string _DEH_CUT_MODE;
		private string _DEH_PAY_MODE;
		private string _DEH_TRANS_MODE;
		private string _DEH_PAY_WAY;
		private string _DEH_FEE_MARK;
		private string _DEH_FEE_CURR;
		private double? _DEH_FEE_RATE;
		private string _DEH_OTHER_MARK;
		private string _DEH_OTHER_CURR;
		private double? _DEH_OTHER_RATE;
		private string _DEH_INSUR_MARK;
		private string _DEH_INSUR_CURR;
		private double? _DEH_INSUR_RATE;
		private double? _DEH_PACK_NO;
		private double? _DEH_GROSS_WT;
		private double? _DEH_NET_WT;
		private string _DEH_LICENSE_NO;
		private string _DEH_APPR_NO;
		private string _DEH_MANUAL_NO;
		private DateTime? _DEH_I_E_DATE;
		private string _DEH_WRAP_TYPE;
		private string _DEH_NOTE_S;
		private DateTime? _DEH_D_DATE;
		private string _DEH_EX_SOURCE;
		private string _DEH_VOYAGE_NO;
		private string _DEH_IE_FLAG;
		private string _DEH_PRDTID;
		private string _DEH_STORENO;
		private string _DEH_RAMANUALNO;
		private string _DEH_RADECLNO;
		private string _DEH_STATUS;
		private string _DEH_MEMO;
		private double? _DEH_DPA_ID;
		private string _INPUTER;
		private DateTime _INPUT_TM;
		private string _UPDATER;
		private DateTime? _UPDATE_TM;
		private string _SYS_CUSTOMER_CD;
		private string _DEH_APPLY_PORT;
		private string _DEH_YEAR;
		private double? _DEH_IE_TYPE;
		private string _DEH_CH_NO;
		private string _DEH_EUROPE;
		private double _DEH_IS_DEL;
		private string _DEH_PRdoubleER;
		private string _DEH_CHECKER;
		private string _DEH_DEC_TYPE;
		private string _DEH_RE_CHECKER;
		private double _DEH_IS_CHECK;
		private double _DEH_IS_RECEIVE;
		private double _DEH_IS_DOCUMENTS;
		private DateTime? _DEH_PASS_TM;
		private double _DEH_SECURITY_CLEARANCE;
		private double _DEH_ELECTRONIC_DECLARATION;
		private double? _DEH_LIST_TYPE;
		private double? _DEH_NOTE_TYPE;
		private string _DEH_TAXATION;
		private double _DEH_PAPERLESS_TAX;
		private double _DEH_SPEC_REL_CONFIR;
		private double _DEH_PRICE_CONFIR;
		private double _DEH_PAY_OF_LICEN_FEES;
		private string _DEH_TRADE_CO_SCC;
		private string _DEH_DECL_PORT;
		private string _DEH_TRADE_AREA_CODE;
		private string _DEH_OWNER_CODE_SCC;
		private string _DEH_AGENT_CODE_SCC;
		private string _DEH_EDI_NO;
		private double? _DEH_CUSTOMS_DECLARATION;
		private string _DEH_TRADE_CO_EI;
		private double? _DEH_SOURCE;
		private double? _DEH_IF_CHECK;
		private DateTime? _DEH_UES_FTP_TM;
		private string _DEH_ENTRY_ID;
		private string _DEH_FIX_NO;
		private double? _DEH_MS_NODERECEIPT_STATUS;
		private double? _DEH_SEND_STATUS;
		private double? _DEH_IMPORT_STATUS;

		/// <summary>
		/// 主键
		/// </summary>
		[Field("DEH_ID")]
		public long DEH_ID
		{
			get{ return _DEH_ID; }
			set
			{
				this.OnPropertyValueChange("DEH_ID");
				this._DEH_ID = value;
			}
		}
		/// <summary>
		/// 预录入编号(与H2000库一致，修改日期2017-03-22)
		/// </summary>
		[Field("DEH_ENTRY_NO")]
		public string DEH_ENTRY_NO
		{
			get{ return _DEH_ENTRY_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_ENTRY_NO");
				this._DEH_ENTRY_NO = value;
			}
		}
		/// <summary>
		/// 收发货人编号,企业10位编码;该报关单的实际经营单位代码
		/// </summary>
		[Field("DEH_TRADE_CO")]
		public string DEH_TRADE_CO
		{
			get{ return _DEH_TRADE_CO; }
			set
			{
				this.OnPropertyValueChange("DEH_TRADE_CO");
				this._DEH_TRADE_CO = value;
			}
		}
		/// <summary>
		/// 收发货人名称
		/// </summary>
		[Field("DEH_TRADE_NAME")]
		public string DEH_TRADE_NAME
		{
			get{ return _DEH_TRADE_NAME; }
			set
			{
				this.OnPropertyValueChange("DEH_TRADE_NAME");
				this._DEH_TRADE_NAME = value;
			}
		}
		/// <summary>
		/// 货主单位地区代码
		/// </summary>
		[Field("DEH_DISTRICT_CODE")]
		public string DEH_DISTRICT_CODE
		{
			get{ return _DEH_DISTRICT_CODE; }
			set
			{
				this.OnPropertyValueChange("DEH_DISTRICT_CODE");
				this._DEH_DISTRICT_CODE = value;
			}
		}
		/// <summary>
		/// 货主单位代码,企业10位编码
		/// </summary>
		[Field("DEH_OWNER_CODE")]
		public string DEH_OWNER_CODE
		{
			get{ return _DEH_OWNER_CODE; }
			set
			{
				this.OnPropertyValueChange("DEH_OWNER_CODE");
				this._DEH_OWNER_CODE = value;
			}
		}
		/// <summary>
		/// 货主单位名称,企业名称
		/// </summary>
		[Field("DEH_OWNER_NAME")]
		public string DEH_OWNER_NAME
		{
			get{ return _DEH_OWNER_NAME; }
			set
			{
				this.OnPropertyValueChange("DEH_OWNER_NAME");
				this._DEH_OWNER_NAME = value;
			}
		}
		/// <summary>
		/// 申报单位代码,企业10位编码
		/// </summary>
		[Field("DEH_AGENT_CODE")]
		public string DEH_AGENT_CODE
		{
			get{ return _DEH_AGENT_CODE; }
			set
			{
				this.OnPropertyValueChange("DEH_AGENT_CODE");
				this._DEH_AGENT_CODE = value;
			}
		}
		/// <summary>
		/// 申报单位名称,企业名称
		/// </summary>
		[Field("DEH_AGENT_NAME")]
		public string DEH_AGENT_NAME
		{
			get{ return _DEH_AGENT_NAME; }
			set
			{
				this.OnPropertyValueChange("DEH_AGENT_NAME");
				this._DEH_AGENT_NAME = value;
			}
		}
		/// <summary>
		/// 运输方式,对应海关参数库中运输方式代码表(TRANSF)中的字段TRAF_CODE
		/// </summary>
		[Field("DEH_TRAF_MODE")]
		public string DEH_TRAF_MODE
		{
			get{ return _DEH_TRAF_MODE; }
			set
			{
				this.OnPropertyValueChange("DEH_TRAF_MODE");
				this._DEH_TRAF_MODE = value;
			}
		}
		/// <summary>
		/// 进出口岸,对应海关参数库中关区代码表(CUSTOMS)中的CUSTOMS_CO字段
		/// </summary>
		[Field("DEH_I_E_PORT")]
		public string DEH_I_E_PORT
		{
			get{ return _DEH_I_E_PORT; }
			set
			{
				this.OnPropertyValueChange("DEH_I_E_PORT");
				this._DEH_I_E_PORT = value;
			}
		}
		/// <summary>
		/// 指运港,对应海关参数库中港口代码表(PORT)中的PORT_CODE字段
		/// </summary>
		[Field("DEH_DISTINATE_PORT")]
		public string DEH_DISTINATE_PORT
		{
			get{ return _DEH_DISTINATE_PORT; }
			set
			{
				this.OnPropertyValueChange("DEH_DISTINATE_PORT");
				this._DEH_DISTINATE_PORT = value;
			}
		}
		/// <summary>
		/// 运输工具代码及名称
		/// </summary>
		[Field("DEH_TRAF_NAME")]
		public string DEH_TRAF_NAME
		{
			get{ return _DEH_TRAF_NAME; }
			set
			{
				this.OnPropertyValueChange("DEH_TRAF_NAME");
				this._DEH_TRAF_NAME = value;
			}
		}
		/// <summary>
		/// 合同号
		/// </summary>
		[Field("DEH_CONTR_NO")]
		public string DEH_CONTR_NO
		{
			get{ return _DEH_CONTR_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_CONTR_NO");
				this._DEH_CONTR_NO = value;
			}
		}
		/// <summary>
		/// 内销比率
		/// </summary>
		[Field("DEH_IN_RATIO")]
		public double? DEH_IN_RATIO
		{
			get{ return _DEH_IN_RATIO; }
			set
			{
				this.OnPropertyValueChange("DEH_IN_RATIO");
				this._DEH_IN_RATIO = value;
			}
		}
		/// <summary>
		/// 提单或运单号
		/// </summary>
		[Field("DEH_BILL_NO")]
		public string DEH_BILL_NO
		{
			get{ return _DEH_BILL_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_BILL_NO");
				this._DEH_BILL_NO = value;
			}
		}
		/// <summary>
		/// 贸易国(地区),对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段
		/// </summary>
		[Field("DEH_TRADE_COUNTRY")]
		public string DEH_TRADE_COUNTRY
		{
			get{ return _DEH_TRADE_COUNTRY; }
			set
			{
				this.OnPropertyValueChange("DEH_TRADE_COUNTRY");
				this._DEH_TRADE_COUNTRY = value;
			}
		}
		/// <summary>
		/// 监管方式,对应海关参数库中贸易方式代码表(TRADE)中的TRADE_MODE字段
		/// </summary>
		[Field("DEH_TRADE_MODE")]
		public string DEH_TRADE_MODE
		{
			get{ return _DEH_TRADE_MODE; }
			set
			{
				this.OnPropertyValueChange("DEH_TRADE_MODE");
				this._DEH_TRADE_MODE = value;
			}
		}
		/// <summary>
		/// 征免性质,对应海关参数库中征免性质代码表(LEVYTYPE)中的CUT_MODE字段
		/// </summary>
		[Field("DEH_CUT_MODE")]
		public string DEH_CUT_MODE
		{
			get{ return _DEH_CUT_MODE; }
			set
			{
				this.OnPropertyValueChange("DEH_CUT_MODE");
				this._DEH_CUT_MODE = value;
			}
		}
		/// <summary>
		/// 纳税方式
		/// </summary>
		[Field("DEH_PAY_MODE")]
		public string DEH_PAY_MODE
		{
			get{ return _DEH_PAY_MODE; }
			set
			{
				this.OnPropertyValueChange("DEH_PAY_MODE");
				this._DEH_PAY_MODE = value;
			}
		}
		/// <summary>
		/// 成交方式
		/// </summary>
		[Field("DEH_TRANS_MODE")]
		public string DEH_TRANS_MODE
		{
			get{ return _DEH_TRANS_MODE; }
			set
			{
				this.OnPropertyValueChange("DEH_TRANS_MODE");
				this._DEH_TRANS_MODE = value;
			}
		}
		/// <summary>
		/// 收结汇方式
		/// </summary>
		[Field("DEH_PAY_WAY")]
		public string DEH_PAY_WAY
		{
			get{ return _DEH_PAY_WAY; }
			set
			{
				this.OnPropertyValueChange("DEH_PAY_WAY");
				this._DEH_PAY_WAY = value;
			}
		}
		/// <summary>
		/// 运费标记1=率(百分比),2=单价,3=总价
		/// </summary>
		[Field("DEH_FEE_MARK")]
		public string DEH_FEE_MARK
		{
			get{ return _DEH_FEE_MARK; }
			set
			{
				this.OnPropertyValueChange("DEH_FEE_MARK");
				this._DEH_FEE_MARK = value;
			}
		}
		/// <summary>
		/// 运费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
		/// </summary>
		[Field("DEH_FEE_CURR")]
		public string DEH_FEE_CURR
		{
			get{ return _DEH_FEE_CURR; }
			set
			{
				this.OnPropertyValueChange("DEH_FEE_CURR");
				this._DEH_FEE_CURR = value;
			}
		}
		/// <summary>
		/// 运费/率
		/// </summary>
		[Field("DEH_FEE_RATE")]
		public double? DEH_FEE_RATE
		{
			get{ return _DEH_FEE_RATE; }
			set
			{
				this.OnPropertyValueChange("DEH_FEE_RATE");
				this._DEH_FEE_RATE = value;
			}
		}
		/// <summary>
		/// 杂费标记,1=率(百分比),2=单价,3=总价
		/// </summary>
		[Field("DEH_OTHER_MARK")]
		public string DEH_OTHER_MARK
		{
			get{ return _DEH_OTHER_MARK; }
			set
			{
				this.OnPropertyValueChange("DEH_OTHER_MARK");
				this._DEH_OTHER_MARK = value;
			}
		}
		/// <summary>
		/// 杂费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
		/// </summary>
		[Field("DEH_OTHER_CURR")]
		public string DEH_OTHER_CURR
		{
			get{ return _DEH_OTHER_CURR; }
			set
			{
				this.OnPropertyValueChange("DEH_OTHER_CURR");
				this._DEH_OTHER_CURR = value;
			}
		}
		/// <summary>
		/// 杂费/率
		/// </summary>
		[Field("DEH_OTHER_RATE")]
		public double? DEH_OTHER_RATE
		{
			get{ return _DEH_OTHER_RATE; }
			set
			{
				this.OnPropertyValueChange("DEH_OTHER_RATE");
				this._DEH_OTHER_RATE = value;
			}
		}
		/// <summary>
		/// 保险费标记,1=率(百分比),2=单价,3=总价
		/// </summary>
		[Field("DEH_INSUR_MARK")]
		public string DEH_INSUR_MARK
		{
			get{ return _DEH_INSUR_MARK; }
			set
			{
				this.OnPropertyValueChange("DEH_INSUR_MARK");
				this._DEH_INSUR_MARK = value;
			}
		}
		/// <summary>
		/// 保险费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
		/// </summary>
		[Field("DEH_INSUR_CURR")]
		public string DEH_INSUR_CURR
		{
			get{ return _DEH_INSUR_CURR; }
			set
			{
				this.OnPropertyValueChange("DEH_INSUR_CURR");
				this._DEH_INSUR_CURR = value;
			}
		}
		/// <summary>
		/// 保险费/率
		/// </summary>
		[Field("DEH_INSUR_RATE")]
		public double? DEH_INSUR_RATE
		{
			get{ return _DEH_INSUR_RATE; }
			set
			{
				this.OnPropertyValueChange("DEH_INSUR_RATE");
				this._DEH_INSUR_RATE = value;
			}
		}
		/// <summary>
		/// 件数
		/// </summary>
		[Field("DEH_PACK_NO")]
		public double? DEH_PACK_NO
		{
			get{ return _DEH_PACK_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_PACK_NO");
				this._DEH_PACK_NO = value;
			}
		}
		/// <summary>
		/// 毛重
		/// </summary>
		[Field("DEH_GROSS_WT")]
		public double? DEH_GROSS_WT
		{
			get{ return _DEH_GROSS_WT; }
			set
			{
				this.OnPropertyValueChange("DEH_GROSS_WT");
				this._DEH_GROSS_WT = value;
			}
		}
		/// <summary>
		/// 净重
		/// </summary>
		[Field("DEH_NET_WT")]
		public double? DEH_NET_WT
		{
			get{ return _DEH_NET_WT; }
			set
			{
				this.OnPropertyValueChange("DEH_NET_WT");
				this._DEH_NET_WT = value;
			}
		}
		/// <summary>
		/// 许可证编号
		/// </summary>
		[Field("DEH_LICENSE_NO")]
		public string DEH_LICENSE_NO
		{
			get{ return _DEH_LICENSE_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_LICENSE_NO");
				this._DEH_LICENSE_NO = value;
			}
		}
		/// <summary>
		/// 批准文号
		/// </summary>
		[Field("DEH_APPR_NO")]
		public string DEH_APPR_NO
		{
			get{ return _DEH_APPR_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_APPR_NO");
				this._DEH_APPR_NO = value;
			}
		}
		/// <summary>
		/// 备案号
		/// </summary>
		[Field("DEH_MANUAL_NO")]
		public string DEH_MANUAL_NO
		{
			get{ return _DEH_MANUAL_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_MANUAL_NO");
				this._DEH_MANUAL_NO = value;
			}
		}
		/// <summary>
		/// 进出日期
		/// </summary>
		[Field("DEH_I_E_DATE")]
		public DateTime? DEH_I_E_DATE
		{
			get{ return _DEH_I_E_DATE; }
			set
			{
				this.OnPropertyValueChange("DEH_I_E_DATE");
				this._DEH_I_E_DATE = value;
			}
		}
		/// <summary>
		/// 包装种类,对应海关参数库中包装类型(Wrap_type)中的WRAP_CODE字段
		/// </summary>
		[Field("DEH_WRAP_TYPE")]
		public string DEH_WRAP_TYPE
		{
			get{ return _DEH_WRAP_TYPE; }
			set
			{
				this.OnPropertyValueChange("DEH_WRAP_TYPE");
				this._DEH_WRAP_TYPE = value;
			}
		}
		/// <summary>
		/// 备注,报关单表头的备注内容+规范申报中商品规格型号剩余的内容
		/// </summary>
		[Field("DEH_NOTE_S")]
		public string DEH_NOTE_S
		{
			get{ return _DEH_NOTE_S; }
			set
			{
				this.OnPropertyValueChange("DEH_NOTE_S");
				this._DEH_NOTE_S = value;
			}
		}
		/// <summary>
		/// 申报日期
		/// </summary>
		[Field("DEH_D_DATE")]
		public DateTime? DEH_D_DATE
		{
			get{ return _DEH_D_DATE; }
			set
			{
				this.OnPropertyValueChange("DEH_D_DATE");
				this._DEH_D_DATE = value;
			}
		}
		/// <summary>
		/// 外汇来源
		/// </summary>
		[Field("DEH_EX_SOURCE")]
		public string DEH_EX_SOURCE
		{
			get{ return _DEH_EX_SOURCE; }
			set
			{
				this.OnPropertyValueChange("DEH_EX_SOURCE");
				this._DEH_EX_SOURCE = value;
			}
		}
		/// <summary>
		/// 航次号
		/// </summary>
		[Field("DEH_VOYAGE_NO")]
		public string DEH_VOYAGE_NO
		{
			get{ return _DEH_VOYAGE_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_VOYAGE_NO");
				this._DEH_VOYAGE_NO = value;
			}
		}
		/// <summary>
		/// 进出口标志
		/// </summary>
		[Field("DEH_IE_FLAG")]
		public string DEH_IE_FLAG
		{
			get{ return _DEH_IE_FLAG; }
			set
			{
				this.OnPropertyValueChange("DEH_IE_FLAG");
				this._DEH_IE_FLAG = value;
			}
		}
		/// <summary>
		/// 货场代码
		/// </summary>
		[Field("DEH_PRDTID")]
		public string DEH_PRDTID
		{
			get{ return _DEH_PRDTID; }
			set
			{
				this.OnPropertyValueChange("DEH_PRDTID");
				this._DEH_PRDTID = value;
			}
		}
		/// <summary>
		/// 保税/监管场所
		/// </summary>
		[Field("DEH_STORENO")]
		public string DEH_STORENO
		{
			get{ return _DEH_STORENO; }
			set
			{
				this.OnPropertyValueChange("DEH_STORENO");
				this._DEH_STORENO = value;
			}
		}
		/// <summary>
		/// 关联备案号
		/// </summary>
		[Field("DEH_RAMANUALNO")]
		public string DEH_RAMANUALNO
		{
			get{ return _DEH_RAMANUALNO; }
			set
			{
				this.OnPropertyValueChange("DEH_RAMANUALNO");
				this._DEH_RAMANUALNO = value;
			}
		}
		/// <summary>
		/// 关联报关单号
		/// </summary>
		[Field("DEH_RADECLNO")]
		public string DEH_RADECLNO
		{
			get{ return _DEH_RADECLNO; }
			set
			{
				this.OnPropertyValueChange("DEH_RADECLNO");
				this._DEH_RADECLNO = value;
			}
		}
		/// <summary>
		/// 报文状态
		/// </summary>
		[Field("DEH_STATUS")]
		public string DEH_STATUS
		{
			get{ return _DEH_STATUS; }
			set
			{
				this.OnPropertyValueChange("DEH_STATUS");
				this._DEH_STATUS = value;
			}
		}
		/// <summary>
		/// 备注,用户自己填写的备注,可为空
		/// </summary>
		[Field("DEH_MEMO")]
		public string DEH_MEMO
		{
			get{ return _DEH_MEMO; }
			set
			{
				this.OnPropertyValueChange("DEH_MEMO");
				this._DEH_MEMO = value;
			}
		}
		/// <summary>
		/// 接单表主键
		/// </summary>
		[Field("DEH_DPA_ID")]
		public double? DEH_DPA_ID
		{
			get{ return _DEH_DPA_ID; }
			set
			{
				this.OnPropertyValueChange("DEH_DPA_ID");
				this._DEH_DPA_ID = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("INPUTER")]
		public string INPUTER
		{
			get{ return _INPUTER; }
			set
			{
				this.OnPropertyValueChange("INPUTER");
				this._INPUTER = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("INPUT_TM")]
		public DateTime INPUT_TM
		{
			get{ return _INPUT_TM; }
			set
			{
				this.OnPropertyValueChange("INPUT_TM");
				this._INPUT_TM = value;
			}
		}
		/// <summary>
		/// 更新人
		/// </summary>
		[Field("UPDATER")]
		public string UPDATER
		{
			get{ return _UPDATER; }
			set
			{
				this.OnPropertyValueChange("UPDATER");
				this._UPDATER = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("UPDATE_TM")]
		public DateTime? UPDATE_TM
		{
			get{ return _UPDATE_TM; }
			set
			{
				this.OnPropertyValueChange("UPDATE_TM");
				this._UPDATE_TM = value;
			}
		}
		/// <summary>
		/// 系统代码
		/// </summary>
		[Field("SYS_CUSTOMER_CD")]
		public string SYS_CUSTOMER_CD
		{
			get{ return _SYS_CUSTOMER_CD; }
			set
			{
				this.OnPropertyValueChange("SYS_CUSTOMER_CD");
				this._SYS_CUSTOMER_CD = value;
			}
		}
		/// <summary>
		/// 申报口岸(同报文decl_port字段对应海关参数库中关区代码表(customs)中的customs_co字段)
		/// </summary>
		[Field("DEH_APPLY_PORT")]
		public string DEH_APPLY_PORT
		{
			get{ return _DEH_APPLY_PORT; }
			set
			{
				this.OnPropertyValueChange("DEH_APPLY_PORT");
				this._DEH_APPLY_PORT = value;
			}
		}
		/// <summary>
		/// 年份
		/// </summary>
		[Field("DEH_YEAR")]
		public string DEH_YEAR
		{
			get{ return _DEH_YEAR; }
			set
			{
				this.OnPropertyValueChange("DEH_YEAR");
				this._DEH_YEAR = value;
			}
		}
		/// <summary>
		/// 进出口标志(1为进口,0为出口)
		/// </summary>
		[Field("DEH_IE_TYPE")]
		public double? DEH_IE_TYPE
		{
			get{ return _DEH_IE_TYPE; }
			set
			{
				this.OnPropertyValueChange("DEH_IE_TYPE");
				this._DEH_IE_TYPE = value;
			}
		}
		/// <summary>
		/// 报关单号/海关编号
		/// </summary>
		[Field("DEH_CH_NO")]
		public string DEH_CH_NO
		{
			get{ return _DEH_CH_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_CH_NO");
				this._DEH_CH_NO = value;
			}
		}
		/// <summary>
		/// 境地内货源地
		/// </summary>
		[Field("DEH_EUROPE")]
		public string DEH_EUROPE
		{
			get{ return _DEH_EUROPE; }
			set
			{
				this.OnPropertyValueChange("DEH_EUROPE");
				this._DEH_EUROPE = value;
			}
		}
		/// <summary>
		/// 删除
		/// </summary>
		[Field("DEH_IS_DEL")]
		public double DEH_IS_DEL
		{
			get{ return _DEH_IS_DEL; }
			set
			{
				this.OnPropertyValueChange("DEH_IS_DEL");
				this._DEH_IS_DEL = value;
			}
		}
		/// <summary>
		/// 打印人
		/// </summary>
		[Field("DEH_PRdoubleER")]
		public string DEH_PRdoubleER
		{
			get{ return _DEH_PRdoubleER; }
			set
			{
				this.OnPropertyValueChange("DEH_PRdoubleER");
				this._DEH_PRdoubleER = value;
			}
		}
		/// <summary>
		/// 审核人
		/// </summary>
		[Field("DEH_CHECKER")]
		public string DEH_CHECKER
		{
			get{ return _DEH_CHECKER; }
			set
			{
				this.OnPropertyValueChange("DEH_CHECKER");
				this._DEH_CHECKER = value;
			}
		}
		/// <summary>
		/// 单证类型
		/// </summary>
		[Field("DEH_DEC_TYPE")]
		public string DEH_DEC_TYPE
		{
			get{ return _DEH_DEC_TYPE; }
			set
			{
				this.OnPropertyValueChange("DEH_DEC_TYPE");
				this._DEH_DEC_TYPE = value;
			}
		}
		/// <summary>
		/// 复核人
		/// </summary>
		[Field("DEH_RE_CHECKER")]
		public string DEH_RE_CHECKER
		{
			get{ return _DEH_RE_CHECKER; }
			set
			{
				this.OnPropertyValueChange("DEH_RE_CHECKER");
				this._DEH_RE_CHECKER = value;
			}
		}
		/// <summary>
		/// 是否审核
		/// </summary>
		[Field("DEH_IS_CHECK")]
		public double DEH_IS_CHECK
		{
			get{ return _DEH_IS_CHECK; }
			set
			{
				this.OnPropertyValueChange("DEH_IS_CHECK");
				this._DEH_IS_CHECK = value;
			}
		}
		/// <summary>
		/// 是否收到提货单
		/// </summary>
		[Field("DEH_IS_RECEIVE")]
		public double DEH_IS_RECEIVE
		{
			get{ return _DEH_IS_RECEIVE; }
			set
			{
				this.OnPropertyValueChange("DEH_IS_RECEIVE");
				this._DEH_IS_RECEIVE = value;
			}
		}
		/// <summary>
		/// 是否集齐单据
		/// </summary>
		[Field("DEH_IS_DOCUMENTS")]
		public double DEH_IS_DOCUMENTS
		{
			get{ return _DEH_IS_DOCUMENTS; }
			set
			{
				this.OnPropertyValueChange("DEH_IS_DOCUMENTS");
				this._DEH_IS_DOCUMENTS = value;
			}
		}
		/// <summary>
		/// 放行日期
		/// </summary>
		[Field("DEH_PASS_TM")]
		public DateTime? DEH_PASS_TM
		{
			get{ return _DEH_PASS_TM; }
			set
			{
				this.OnPropertyValueChange("DEH_PASS_TM");
				this._DEH_PASS_TM = value;
			}
		}
		/// <summary>
		/// 是否担保验放
		/// </summary>
		[Field("DEH_SECURITY_CLEARANCE")]
		public double DEH_SECURITY_CLEARANCE
		{
			get{ return _DEH_SECURITY_CLEARANCE; }
			set
			{
				this.OnPropertyValueChange("DEH_SECURITY_CLEARANCE");
				this._DEH_SECURITY_CLEARANCE = value;
			}
		}
		/// <summary>
		/// 是否电子手册报关申报
		/// </summary>
		[Field("DEH_ELECTRONIC_DECLARATION")]
		public double DEH_ELECTRONIC_DECLARATION
		{
			get{ return _DEH_ELECTRONIC_DECLARATION; }
			set
			{
				this.OnPropertyValueChange("DEH_ELECTRONIC_DECLARATION");
				this._DEH_ELECTRONIC_DECLARATION = value;
			}
		}
		/// <summary>
		/// 清单类型(10:普通备案清单,20:先进区后报关)
		/// </summary>
		[Field("DEH_LIST_TYPE")]
		public double? DEH_LIST_TYPE
		{
			get{ return _DEH_LIST_TYPE; }
			set
			{
				this.OnPropertyValueChange("DEH_LIST_TYPE");
				this._DEH_LIST_TYPE = value;
			}
		}
		/// <summary>
		/// 票据类型(10:汇总征税)
		/// </summary>
		[Field("DEH_NOTE_TYPE")]
		public double? DEH_NOTE_TYPE
		{
			get{ return _DEH_NOTE_TYPE; }
			set
			{
				this.OnPropertyValueChange("DEH_NOTE_TYPE");
				this._DEH_NOTE_TYPE = value;
			}
		}
		/// <summary>
		/// 税费
		/// </summary>
		[Field("DEH_TAXATION")]
		public string DEH_TAXATION
		{
			get{ return _DEH_TAXATION; }
			set
			{
				this.OnPropertyValueChange("DEH_TAXATION");
				this._DEH_TAXATION = value;
			}
		}
		/// <summary>
		/// 是否有税单无纸化
		/// </summary>
		[Field("DEH_PAPERLESS_TAX")]
		public double DEH_PAPERLESS_TAX
		{
			get{ return _DEH_PAPERLESS_TAX; }
			set
			{
				this.OnPropertyValueChange("DEH_PAPERLESS_TAX");
				this._DEH_PAPERLESS_TAX = value;
			}
		}
		/// <summary>
		/// 是否特殊关系确认
		/// </summary>
		[Field("DEH_SPEC_REL_CONFIR")]
		public double DEH_SPEC_REL_CONFIR
		{
			get{ return _DEH_SPEC_REL_CONFIR; }
			set
			{
				this.OnPropertyValueChange("DEH_SPEC_REL_CONFIR");
				this._DEH_SPEC_REL_CONFIR = value;
			}
		}
		/// <summary>
		/// 是否价格影响确认
		/// </summary>
		[Field("DEH_PRICE_CONFIR")]
		public double DEH_PRICE_CONFIR
		{
			get{ return _DEH_PRICE_CONFIR; }
			set
			{
				this.OnPropertyValueChange("DEH_PRICE_CONFIR");
				this._DEH_PRICE_CONFIR = value;
			}
		}
		/// <summary>
		/// 是否支付特许权使用费确认
		/// </summary>
		[Field("DEH_PAY_OF_LICEN_FEES")]
		public double DEH_PAY_OF_LICEN_FEES
		{
			get{ return _DEH_PAY_OF_LICEN_FEES; }
			set
			{
				this.OnPropertyValueChange("DEH_PAY_OF_LICEN_FEES");
				this._DEH_PAY_OF_LICEN_FEES = value;
			}
		}
		/// <summary>
		/// 经营单位统一编码
		/// </summary>
		[Field("DEH_TRADE_CO_SCC")]
		public string DEH_TRADE_CO_SCC
		{
			get{ return _DEH_TRADE_CO_SCC; }
			set
			{
				this.OnPropertyValueChange("DEH_TRADE_CO_SCC");
				this._DEH_TRADE_CO_SCC = value;
			}
		}
		/// <summary>
		/// 申报地海关
		/// </summary>
		[Field("DEH_DECL_PORT")]
		public string DEH_DECL_PORT
		{
			get{ return _DEH_DECL_PORT; }
			set
			{
				this.OnPropertyValueChange("DEH_DECL_PORT");
				this._DEH_DECL_PORT = value;
			}
		}
		/// <summary>
		/// 贸易国别(对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段)
		/// </summary>
		[Field("DEH_TRADE_AREA_CODE")]
		public string DEH_TRADE_AREA_CODE
		{
			get{ return _DEH_TRADE_AREA_CODE; }
			set
			{
				this.OnPropertyValueChange("DEH_TRADE_AREA_CODE");
				this._DEH_TRADE_AREA_CODE = value;
			}
		}
		/// <summary>
		/// 货主单位统一编码
		/// </summary>
		[Field("DEH_OWNER_CODE_SCC")]
		public string DEH_OWNER_CODE_SCC
		{
			get{ return _DEH_OWNER_CODE_SCC; }
			set
			{
				this.OnPropertyValueChange("DEH_OWNER_CODE_SCC");
				this._DEH_OWNER_CODE_SCC = value;
			}
		}
		/// <summary>
		/// 申报代码统一编码
		/// </summary>
		[Field("DEH_AGENT_CODE_SCC")]
		public string DEH_AGENT_CODE_SCC
		{
			get{ return _DEH_AGENT_CODE_SCC; }
			set
			{
				this.OnPropertyValueChange("DEH_AGENT_CODE_SCC");
				this._DEH_AGENT_CODE_SCC = value;
			}
		}
		/// <summary>
		/// EDI单据编号
		/// </summary>
		[Field("DEH_EDI_NO")]
		public string DEH_EDI_NO
		{
			get{ return _DEH_EDI_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_EDI_NO");
				this._DEH_EDI_NO = value;
			}
		}
		/// <summary>
		/// 属地申报(1属地申报口岸验放2属地申报属地验放)
		/// </summary>
		[Field("DEH_CUSTOMS_DECLARATION")]
		public double? DEH_CUSTOMS_DECLARATION
		{
			get{ return _DEH_CUSTOMS_DECLARATION; }
			set
			{
				this.OnPropertyValueChange("DEH_CUSTOMS_DECLARATION");
				this._DEH_CUSTOMS_DECLARATION = value;
			}
		}
		/// <summary>
		/// 收发货人18位编码
		/// </summary>
		[Field("DEH_TRADE_CO_EI")]
		public string DEH_TRADE_CO_EI
		{
			get{ return _DEH_TRADE_CO_EI; }
			set
			{
				this.OnPropertyValueChange("DEH_TRADE_CO_EI");
				this._DEH_TRADE_CO_EI = value;
			}
		}
		/// <summary>
		/// 来源;0:本地1:edi,美设:2
		/// </summary>
		[Field("DEH_SOURCE")]
		public double? DEH_SOURCE
		{
			get{ return _DEH_SOURCE; }
			set
			{
				this.OnPropertyValueChange("DEH_SOURCE");
				this._DEH_SOURCE = value;
			}
		}
		/// <summary>
		/// 校验通过10,校验不通过20
		/// </summary>
		[Field("DEH_IF_CHECK")]
		public double? DEH_IF_CHECK
		{
			get{ return _DEH_IF_CHECK; }
			set
			{
				this.OnPropertyValueChange("DEH_IF_CHECK");
				this._DEH_IF_CHECK = value;
			}
		}
		/// <summary>
		/// 上传时间
		/// </summary>
		[Field("DEH_UES_FTP_TM")]
		public DateTime? DEH_UES_FTP_TM
		{
			get{ return _DEH_UES_FTP_TM; }
			set
			{
				this.OnPropertyValueChange("DEH_UES_FTP_TM");
				this._DEH_UES_FTP_TM = value;
			}
		}
		/// <summary>
		/// 新增字段-报关ID
		/// </summary>
		[Field("DEH_ENTRY_ID")]
		public string DEH_ENTRY_ID
		{
			get{ return _DEH_ENTRY_ID; }
			set
			{
				this.OnPropertyValueChange("DEH_ENTRY_ID");
				this._DEH_ENTRY_ID = value;
			}
		}
		/// <summary>
		/// 新增字段-集箱号
		/// </summary>
		[Field("DEH_FIX_NO")]
		public string DEH_FIX_NO
		{
			get{ return _DEH_FIX_NO; }
			set
			{
				this.OnPropertyValueChange("DEH_FIX_NO");
				this._DEH_FIX_NO = value;
			}
		}
		/// <summary>
		/// 新增字段-0,未发送节点回执;1,已发送节点回执----美设节点回执
		/// </summary>
		[Field("DEH_MS_NODERECEIPT_STATUS")]
		public double? DEH_MS_NODERECEIPT_STATUS
		{
			get{ return _DEH_MS_NODERECEIPT_STATUS; }
			set
			{
				this.OnPropertyValueChange("DEH_MS_NODERECEIPT_STATUS");
				this._DEH_MS_NODERECEIPT_STATUS = value;
			}
		}
		/// <summary>
		/// 新增-H2000发送是否成功;0-未发送,1-已发送,2-发送失败
		/// </summary>
		[Field("DEH_SEND_STATUS")]
		public double? DEH_SEND_STATUS
		{
			get{ return _DEH_SEND_STATUS; }
			set
			{
				this.OnPropertyValueChange("DEH_SEND_STATUS");
				this._DEH_SEND_STATUS = value;
			}
		}
		/// <summary>
		/// 新增-报关数据导入H2000状态;0-未导入;1-已导
		/// </summary>
		[Field("DEH_IMPORT_STATUS")]
		public double? DEH_IMPORT_STATUS
		{
			get{ return _DEH_IMPORT_STATUS; }
			set
			{
				this.OnPropertyValueChange("DEH_IMPORT_STATUS");
				this._DEH_IMPORT_STATUS = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.DEH_ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.DEH_ID,
				_.DEH_ENTRY_NO,
				_.DEH_TRADE_CO,
				_.DEH_TRADE_NAME,
				_.DEH_DISTRICT_CODE,
				_.DEH_OWNER_CODE,
				_.DEH_OWNER_NAME,
				_.DEH_AGENT_CODE,
				_.DEH_AGENT_NAME,
				_.DEH_TRAF_MODE,
				_.DEH_I_E_PORT,
				_.DEH_DISTINATE_PORT,
				_.DEH_TRAF_NAME,
				_.DEH_CONTR_NO,
				_.DEH_IN_RATIO,
				_.DEH_BILL_NO,
				_.DEH_TRADE_COUNTRY,
				_.DEH_TRADE_MODE,
				_.DEH_CUT_MODE,
				_.DEH_PAY_MODE,
				_.DEH_TRANS_MODE,
				_.DEH_PAY_WAY,
				_.DEH_FEE_MARK,
				_.DEH_FEE_CURR,
				_.DEH_FEE_RATE,
				_.DEH_OTHER_MARK,
				_.DEH_OTHER_CURR,
				_.DEH_OTHER_RATE,
				_.DEH_INSUR_MARK,
				_.DEH_INSUR_CURR,
				_.DEH_INSUR_RATE,
				_.DEH_PACK_NO,
				_.DEH_GROSS_WT,
				_.DEH_NET_WT,
				_.DEH_LICENSE_NO,
				_.DEH_APPR_NO,
				_.DEH_MANUAL_NO,
				_.DEH_I_E_DATE,
				_.DEH_WRAP_TYPE,
				_.DEH_NOTE_S,
				_.DEH_D_DATE,
				_.DEH_EX_SOURCE,
				_.DEH_VOYAGE_NO,
				_.DEH_IE_FLAG,
				_.DEH_PRDTID,
				_.DEH_STORENO,
				_.DEH_RAMANUALNO,
				_.DEH_RADECLNO,
				_.DEH_STATUS,
				_.DEH_MEMO,
				_.DEH_DPA_ID,
				_.INPUTER,
				_.INPUT_TM,
				_.UPDATER,
				_.UPDATE_TM,
				_.SYS_CUSTOMER_CD,
				_.DEH_APPLY_PORT,
				_.DEH_YEAR,
				_.DEH_IE_TYPE,
				_.DEH_CH_NO,
				_.DEH_EUROPE,
				_.DEH_IS_DEL,
				_.DEH_PRdoubleER,
				_.DEH_CHECKER,
				_.DEH_DEC_TYPE,
				_.DEH_RE_CHECKER,
				_.DEH_IS_CHECK,
				_.DEH_IS_RECEIVE,
				_.DEH_IS_DOCUMENTS,
				_.DEH_PASS_TM,
				_.DEH_SECURITY_CLEARANCE,
				_.DEH_ELECTRONIC_DECLARATION,
				_.DEH_LIST_TYPE,
				_.DEH_NOTE_TYPE,
				_.DEH_TAXATION,
				_.DEH_PAPERLESS_TAX,
				_.DEH_SPEC_REL_CONFIR,
				_.DEH_PRICE_CONFIR,
				_.DEH_PAY_OF_LICEN_FEES,
				_.DEH_TRADE_CO_SCC,
				_.DEH_DECL_PORT,
				_.DEH_TRADE_AREA_CODE,
				_.DEH_OWNER_CODE_SCC,
				_.DEH_AGENT_CODE_SCC,
				_.DEH_EDI_NO,
				_.DEH_CUSTOMS_DECLARATION,
				_.DEH_TRADE_CO_EI,
				_.DEH_SOURCE,
				_.DEH_IF_CHECK,
				_.DEH_UES_FTP_TM,
				_.DEH_ENTRY_ID,
				_.DEH_FIX_NO,
				_.DEH_MS_NODERECEIPT_STATUS,
				_.DEH_SEND_STATUS,
				_.DEH_IMPORT_STATUS,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._DEH_ID,
				this._DEH_ENTRY_NO,
				this._DEH_TRADE_CO,
				this._DEH_TRADE_NAME,
				this._DEH_DISTRICT_CODE,
				this._DEH_OWNER_CODE,
				this._DEH_OWNER_NAME,
				this._DEH_AGENT_CODE,
				this._DEH_AGENT_NAME,
				this._DEH_TRAF_MODE,
				this._DEH_I_E_PORT,
				this._DEH_DISTINATE_PORT,
				this._DEH_TRAF_NAME,
				this._DEH_CONTR_NO,
				this._DEH_IN_RATIO,
				this._DEH_BILL_NO,
				this._DEH_TRADE_COUNTRY,
				this._DEH_TRADE_MODE,
				this._DEH_CUT_MODE,
				this._DEH_PAY_MODE,
				this._DEH_TRANS_MODE,
				this._DEH_PAY_WAY,
				this._DEH_FEE_MARK,
				this._DEH_FEE_CURR,
				this._DEH_FEE_RATE,
				this._DEH_OTHER_MARK,
				this._DEH_OTHER_CURR,
				this._DEH_OTHER_RATE,
				this._DEH_INSUR_MARK,
				this._DEH_INSUR_CURR,
				this._DEH_INSUR_RATE,
				this._DEH_PACK_NO,
				this._DEH_GROSS_WT,
				this._DEH_NET_WT,
				this._DEH_LICENSE_NO,
				this._DEH_APPR_NO,
				this._DEH_MANUAL_NO,
				this._DEH_I_E_DATE,
				this._DEH_WRAP_TYPE,
				this._DEH_NOTE_S,
				this._DEH_D_DATE,
				this._DEH_EX_SOURCE,
				this._DEH_VOYAGE_NO,
				this._DEH_IE_FLAG,
				this._DEH_PRDTID,
				this._DEH_STORENO,
				this._DEH_RAMANUALNO,
				this._DEH_RADECLNO,
				this._DEH_STATUS,
				this._DEH_MEMO,
				this._DEH_DPA_ID,
				this._INPUTER,
				this._INPUT_TM,
				this._UPDATER,
				this._UPDATE_TM,
				this._SYS_CUSTOMER_CD,
				this._DEH_APPLY_PORT,
				this._DEH_YEAR,
				this._DEH_IE_TYPE,
				this._DEH_CH_NO,
				this._DEH_EUROPE,
				this._DEH_IS_DEL,
				this._DEH_PRdoubleER,
				this._DEH_CHECKER,
				this._DEH_DEC_TYPE,
				this._DEH_RE_CHECKER,
				this._DEH_IS_CHECK,
				this._DEH_IS_RECEIVE,
				this._DEH_IS_DOCUMENTS,
				this._DEH_PASS_TM,
				this._DEH_SECURITY_CLEARANCE,
				this._DEH_ELECTRONIC_DECLARATION,
				this._DEH_LIST_TYPE,
				this._DEH_NOTE_TYPE,
				this._DEH_TAXATION,
				this._DEH_PAPERLESS_TAX,
				this._DEH_SPEC_REL_CONFIR,
				this._DEH_PRICE_CONFIR,
				this._DEH_PAY_OF_LICEN_FEES,
				this._DEH_TRADE_CO_SCC,
				this._DEH_DECL_PORT,
				this._DEH_TRADE_AREA_CODE,
				this._DEH_OWNER_CODE_SCC,
				this._DEH_AGENT_CODE_SCC,
				this._DEH_EDI_NO,
				this._DEH_CUSTOMS_DECLARATION,
				this._DEH_TRADE_CO_EI,
				this._DEH_SOURCE,
				this._DEH_IF_CHECK,
				this._DEH_UES_FTP_TM,
				this._DEH_ENTRY_ID,
				this._DEH_FIX_NO,
				this._DEH_MS_NODERECEIPT_STATUS,
				this._DEH_SEND_STATUS,
				this._DEH_IMPORT_STATUS,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DC_EP_DEC_HEAD");
            /// <summary>
			/// 主键
			/// </summary>
			public readonly static Field DEH_ID = new Field("DEH_ID", "DC_EP_DEC_HEAD", "主键");
            /// <summary>
			/// 预录入编号(与H2000库一致，修改日期2017-03-22)
			/// </summary>
			public readonly static Field DEH_ENTRY_NO = new Field("DEH_ENTRY_NO", "DC_EP_DEC_HEAD", "预录入编号(与H2000库一致，修改日期2017-03-22)");
            /// <summary>
			/// 收发货人编号,企业10位编码;该报关单的实际经营单位代码
			/// </summary>
			public readonly static Field DEH_TRADE_CO = new Field("DEH_TRADE_CO", "DC_EP_DEC_HEAD", "收发货人编号,企业10位编码;该报关单的实际经营单位代码");
            /// <summary>
			/// 收发货人名称
			/// </summary>
			public readonly static Field DEH_TRADE_NAME = new Field("DEH_TRADE_NAME", "DC_EP_DEC_HEAD", "收发货人名称");
            /// <summary>
			/// 货主单位地区代码
			/// </summary>
			public readonly static Field DEH_DISTRICT_CODE = new Field("DEH_DISTRICT_CODE", "DC_EP_DEC_HEAD", "货主单位地区代码");
            /// <summary>
			/// 货主单位代码,企业10位编码
			/// </summary>
			public readonly static Field DEH_OWNER_CODE = new Field("DEH_OWNER_CODE", "DC_EP_DEC_HEAD", "货主单位代码,企业10位编码");
            /// <summary>
			/// 货主单位名称,企业名称
			/// </summary>
			public readonly static Field DEH_OWNER_NAME = new Field("DEH_OWNER_NAME", "DC_EP_DEC_HEAD", "货主单位名称,企业名称");
            /// <summary>
			/// 申报单位代码,企业10位编码
			/// </summary>
			public readonly static Field DEH_AGENT_CODE = new Field("DEH_AGENT_CODE", "DC_EP_DEC_HEAD", "申报单位代码,企业10位编码");
            /// <summary>
			/// 申报单位名称,企业名称
			/// </summary>
			public readonly static Field DEH_AGENT_NAME = new Field("DEH_AGENT_NAME", "DC_EP_DEC_HEAD", "申报单位名称,企业名称");
            /// <summary>
			/// 运输方式,对应海关参数库中运输方式代码表(TRANSF)中的字段TRAF_CODE
			/// </summary>
			public readonly static Field DEH_TRAF_MODE = new Field("DEH_TRAF_MODE", "DC_EP_DEC_HEAD", "运输方式,对应海关参数库中运输方式代码表(TRANSF)中的字段TRAF_CODE");
            /// <summary>
			/// 进出口岸,对应海关参数库中关区代码表(CUSTOMS)中的CUSTOMS_CO字段
			/// </summary>
			public readonly static Field DEH_I_E_PORT = new Field("DEH_I_E_PORT", "DC_EP_DEC_HEAD", "进出口岸,对应海关参数库中关区代码表(CUSTOMS)中的CUSTOMS_CO字段");
            /// <summary>
			/// 指运港,对应海关参数库中港口代码表(PORT)中的PORT_CODE字段
			/// </summary>
			public readonly static Field DEH_DISTINATE_PORT = new Field("DEH_DISTINATE_PORT", "DC_EP_DEC_HEAD", "指运港,对应海关参数库中港口代码表(PORT)中的PORT_CODE字段");
            /// <summary>
			/// 运输工具代码及名称
			/// </summary>
			public readonly static Field DEH_TRAF_NAME = new Field("DEH_TRAF_NAME", "DC_EP_DEC_HEAD", "运输工具代码及名称");
            /// <summary>
			/// 合同号
			/// </summary>
			public readonly static Field DEH_CONTR_NO = new Field("DEH_CONTR_NO", "DC_EP_DEC_HEAD", "合同号");
            /// <summary>
			/// 内销比率
			/// </summary>
			public readonly static Field DEH_IN_RATIO = new Field("DEH_IN_RATIO", "DC_EP_DEC_HEAD", "内销比率");
            /// <summary>
			/// 提单或运单号
			/// </summary>
			public readonly static Field DEH_BILL_NO = new Field("DEH_BILL_NO", "DC_EP_DEC_HEAD", "提单或运单号");
            /// <summary>
			/// 贸易国(地区),对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段
			/// </summary>
			public readonly static Field DEH_TRADE_COUNTRY = new Field("DEH_TRADE_COUNTRY", "DC_EP_DEC_HEAD", "贸易国(地区),对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段");
            /// <summary>
			/// 监管方式,对应海关参数库中贸易方式代码表(TRADE)中的TRADE_MODE字段
			/// </summary>
			public readonly static Field DEH_TRADE_MODE = new Field("DEH_TRADE_MODE", "DC_EP_DEC_HEAD", "监管方式,对应海关参数库中贸易方式代码表(TRADE)中的TRADE_MODE字段");
            /// <summary>
			/// 征免性质,对应海关参数库中征免性质代码表(LEVYTYPE)中的CUT_MODE字段
			/// </summary>
			public readonly static Field DEH_CUT_MODE = new Field("DEH_CUT_MODE", "DC_EP_DEC_HEAD", "征免性质,对应海关参数库中征免性质代码表(LEVYTYPE)中的CUT_MODE字段");
            /// <summary>
			/// 纳税方式
			/// </summary>
			public readonly static Field DEH_PAY_MODE = new Field("DEH_PAY_MODE", "DC_EP_DEC_HEAD", "纳税方式");
            /// <summary>
			/// 成交方式
			/// </summary>
			public readonly static Field DEH_TRANS_MODE = new Field("DEH_TRANS_MODE", "DC_EP_DEC_HEAD", "成交方式");
            /// <summary>
			/// 收结汇方式
			/// </summary>
			public readonly static Field DEH_PAY_WAY = new Field("DEH_PAY_WAY", "DC_EP_DEC_HEAD", "收结汇方式");
            /// <summary>
			/// 运费标记1=率(百分比),2=单价,3=总价
			/// </summary>
			public readonly static Field DEH_FEE_MARK = new Field("DEH_FEE_MARK", "DC_EP_DEC_HEAD", "运费标记1=率(百分比),2=单价,3=总价");
            /// <summary>
			/// 运费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
			/// </summary>
			public readonly static Field DEH_FEE_CURR = new Field("DEH_FEE_CURR", "DC_EP_DEC_HEAD", "运费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段");
            /// <summary>
			/// 运费/率
			/// </summary>
			public readonly static Field DEH_FEE_RATE = new Field("DEH_FEE_RATE", "DC_EP_DEC_HEAD", "运费/率");
            /// <summary>
			/// 杂费标记,1=率(百分比),2=单价,3=总价
			/// </summary>
			public readonly static Field DEH_OTHER_MARK = new Field("DEH_OTHER_MARK", "DC_EP_DEC_HEAD", "杂费标记,1=率(百分比),2=单价,3=总价");
            /// <summary>
			/// 杂费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
			/// </summary>
			public readonly static Field DEH_OTHER_CURR = new Field("DEH_OTHER_CURR", "DC_EP_DEC_HEAD", "杂费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段");
            /// <summary>
			/// 杂费/率
			/// </summary>
			public readonly static Field DEH_OTHER_RATE = new Field("DEH_OTHER_RATE", "DC_EP_DEC_HEAD", "杂费/率");
            /// <summary>
			/// 保险费标记,1=率(百分比),2=单价,3=总价
			/// </summary>
			public readonly static Field DEH_INSUR_MARK = new Field("DEH_INSUR_MARK", "DC_EP_DEC_HEAD", "保险费标记,1=率(百分比),2=单价,3=总价");
            /// <summary>
			/// 保险费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段
			/// </summary>
			public readonly static Field DEH_INSUR_CURR = new Field("DEH_INSUR_CURR", "DC_EP_DEC_HEAD", "保险费币制,对应海关参数库中币制代码表(CURR)中的CURR_CODE字段");
            /// <summary>
			/// 保险费/率
			/// </summary>
			public readonly static Field DEH_INSUR_RATE = new Field("DEH_INSUR_RATE", "DC_EP_DEC_HEAD", "保险费/率");
            /// <summary>
			/// 件数
			/// </summary>
			public readonly static Field DEH_PACK_NO = new Field("DEH_PACK_NO", "DC_EP_DEC_HEAD", "件数");
            /// <summary>
			/// 毛重
			/// </summary>
			public readonly static Field DEH_GROSS_WT = new Field("DEH_GROSS_WT", "DC_EP_DEC_HEAD", "毛重");
            /// <summary>
			/// 净重
			/// </summary>
			public readonly static Field DEH_NET_WT = new Field("DEH_NET_WT", "DC_EP_DEC_HEAD", "净重");
            /// <summary>
			/// 许可证编号
			/// </summary>
			public readonly static Field DEH_LICENSE_NO = new Field("DEH_LICENSE_NO", "DC_EP_DEC_HEAD", "许可证编号");
            /// <summary>
			/// 批准文号
			/// </summary>
			public readonly static Field DEH_APPR_NO = new Field("DEH_APPR_NO", "DC_EP_DEC_HEAD", "批准文号");
            /// <summary>
			/// 备案号
			/// </summary>
			public readonly static Field DEH_MANUAL_NO = new Field("DEH_MANUAL_NO", "DC_EP_DEC_HEAD", "备案号");
            /// <summary>
			/// 进出日期
			/// </summary>
			public readonly static Field DEH_I_E_DATE = new Field("DEH_I_E_DATE", "DC_EP_DEC_HEAD", "进出日期");
            /// <summary>
			/// 包装种类,对应海关参数库中包装类型(Wrap_type)中的WRAP_CODE字段
			/// </summary>
			public readonly static Field DEH_WRAP_TYPE = new Field("DEH_WRAP_TYPE", "DC_EP_DEC_HEAD", "包装种类,对应海关参数库中包装类型(Wrap_type)中的WRAP_CODE字段");
            /// <summary>
			/// 备注,报关单表头的备注内容+规范申报中商品规格型号剩余的内容
			/// </summary>
			public readonly static Field DEH_NOTE_S = new Field("DEH_NOTE_S", "DC_EP_DEC_HEAD", "备注,报关单表头的备注内容+规范申报中商品规格型号剩余的内容");
            /// <summary>
			/// 申报日期
			/// </summary>
			public readonly static Field DEH_D_DATE = new Field("DEH_D_DATE", "DC_EP_DEC_HEAD", "申报日期");
            /// <summary>
			/// 外汇来源
			/// </summary>
			public readonly static Field DEH_EX_SOURCE = new Field("DEH_EX_SOURCE", "DC_EP_DEC_HEAD", "外汇来源");
            /// <summary>
			/// 航次号
			/// </summary>
			public readonly static Field DEH_VOYAGE_NO = new Field("DEH_VOYAGE_NO", "DC_EP_DEC_HEAD", "航次号");
            /// <summary>
			/// 进出口标志
			/// </summary>
			public readonly static Field DEH_IE_FLAG = new Field("DEH_IE_FLAG", "DC_EP_DEC_HEAD", "进出口标志");
            /// <summary>
			/// 货场代码
			/// </summary>
			public readonly static Field DEH_PRDTID = new Field("DEH_PRDTID", "DC_EP_DEC_HEAD", "货场代码");
            /// <summary>
			/// 保税/监管场所
			/// </summary>
			public readonly static Field DEH_STORENO = new Field("DEH_STORENO", "DC_EP_DEC_HEAD", "保税/监管场所");
            /// <summary>
			/// 关联备案号
			/// </summary>
			public readonly static Field DEH_RAMANUALNO = new Field("DEH_RAMANUALNO", "DC_EP_DEC_HEAD", "关联备案号");
            /// <summary>
			/// 关联报关单号
			/// </summary>
			public readonly static Field DEH_RADECLNO = new Field("DEH_RADECLNO", "DC_EP_DEC_HEAD", "关联报关单号");
            /// <summary>
			/// 报文状态
			/// </summary>
			public readonly static Field DEH_STATUS = new Field("DEH_STATUS", "DC_EP_DEC_HEAD", "报文状态");
            /// <summary>
			/// 备注,用户自己填写的备注,可为空
			/// </summary>
			public readonly static Field DEH_MEMO = new Field("DEH_MEMO", "DC_EP_DEC_HEAD", "备注,用户自己填写的备注,可为空");
            /// <summary>
			/// 接单表主键
			/// </summary>
			public readonly static Field DEH_DPA_ID = new Field("DEH_DPA_ID", "DC_EP_DEC_HEAD", "接单表主键");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field INPUTER = new Field("INPUTER", "DC_EP_DEC_HEAD", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field INPUT_TM = new Field("INPUT_TM", "DC_EP_DEC_HEAD", "录入时间");
            /// <summary>
			/// 更新人
			/// </summary>
			public readonly static Field UPDATER = new Field("UPDATER", "DC_EP_DEC_HEAD", "更新人");
            /// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UPDATE_TM = new Field("UPDATE_TM", "DC_EP_DEC_HEAD", "更新时间");
            /// <summary>
			/// 系统代码
			/// </summary>
			public readonly static Field SYS_CUSTOMER_CD = new Field("SYS_CUSTOMER_CD", "DC_EP_DEC_HEAD", "系统代码");
            /// <summary>
			/// 申报口岸(同报文decl_port字段对应海关参数库中关区代码表(customs)中的customs_co字段)
			/// </summary>
			public readonly static Field DEH_APPLY_PORT = new Field("DEH_APPLY_PORT", "DC_EP_DEC_HEAD", "申报口岸(同报文decl_port字段对应海关参数库中关区代码表(customs)中的customs_co字段)");
            /// <summary>
			/// 年份
			/// </summary>
			public readonly static Field DEH_YEAR = new Field("DEH_YEAR", "DC_EP_DEC_HEAD", "年份");
            /// <summary>
			/// 进出口标志(1为进口,0为出口)
			/// </summary>
			public readonly static Field DEH_IE_TYPE = new Field("DEH_IE_TYPE", "DC_EP_DEC_HEAD", "进出口标志(1为进口,0为出口)");
            /// <summary>
			/// 报关单号/海关编号
			/// </summary>
			public readonly static Field DEH_CH_NO = new Field("DEH_CH_NO", "DC_EP_DEC_HEAD", "报关单号/海关编号");
            /// <summary>
			/// 境地内货源地
			/// </summary>
			public readonly static Field DEH_EUROPE = new Field("DEH_EUROPE", "DC_EP_DEC_HEAD", "境地内货源地");
            /// <summary>
			/// 删除
			/// </summary>
			public readonly static Field DEH_IS_DEL = new Field("DEH_IS_DEL", "DC_EP_DEC_HEAD", "删除");
            /// <summary>
			/// 打印人
			/// </summary>
			public readonly static Field DEH_PRdoubleER = new Field("DEH_PRdoubleER", "DC_EP_DEC_HEAD", "打印人");
            /// <summary>
			/// 审核人
			/// </summary>
			public readonly static Field DEH_CHECKER = new Field("DEH_CHECKER", "DC_EP_DEC_HEAD", "审核人");
            /// <summary>
			/// 单证类型
			/// </summary>
			public readonly static Field DEH_DEC_TYPE = new Field("DEH_DEC_TYPE", "DC_EP_DEC_HEAD", "单证类型");
            /// <summary>
			/// 复核人
			/// </summary>
			public readonly static Field DEH_RE_CHECKER = new Field("DEH_RE_CHECKER", "DC_EP_DEC_HEAD", "复核人");
            /// <summary>
			/// 是否审核
			/// </summary>
			public readonly static Field DEH_IS_CHECK = new Field("DEH_IS_CHECK", "DC_EP_DEC_HEAD", "是否审核");
            /// <summary>
			/// 是否收到提货单
			/// </summary>
			public readonly static Field DEH_IS_RECEIVE = new Field("DEH_IS_RECEIVE", "DC_EP_DEC_HEAD", "是否收到提货单");
            /// <summary>
			/// 是否集齐单据
			/// </summary>
			public readonly static Field DEH_IS_DOCUMENTS = new Field("DEH_IS_DOCUMENTS", "DC_EP_DEC_HEAD", "是否集齐单据");
            /// <summary>
			/// 放行日期
			/// </summary>
			public readonly static Field DEH_PASS_TM = new Field("DEH_PASS_TM", "DC_EP_DEC_HEAD", "放行日期");
            /// <summary>
			/// 是否担保验放
			/// </summary>
			public readonly static Field DEH_SECURITY_CLEARANCE = new Field("DEH_SECURITY_CLEARANCE", "DC_EP_DEC_HEAD", "是否担保验放");
            /// <summary>
			/// 是否电子手册报关申报
			/// </summary>
			public readonly static Field DEH_ELECTRONIC_DECLARATION = new Field("DEH_ELECTRONIC_DECLARATION", "DC_EP_DEC_HEAD", "是否电子手册报关申报");
            /// <summary>
			/// 清单类型(10:普通备案清单,20:先进区后报关)
			/// </summary>
			public readonly static Field DEH_LIST_TYPE = new Field("DEH_LIST_TYPE", "DC_EP_DEC_HEAD", "清单类型(10:普通备案清单,20:先进区后报关)");
            /// <summary>
			/// 票据类型(10:汇总征税)
			/// </summary>
			public readonly static Field DEH_NOTE_TYPE = new Field("DEH_NOTE_TYPE", "DC_EP_DEC_HEAD", "票据类型(10:汇总征税)");
            /// <summary>
			/// 税费
			/// </summary>
			public readonly static Field DEH_TAXATION = new Field("DEH_TAXATION", "DC_EP_DEC_HEAD", "税费");
            /// <summary>
			/// 是否有税单无纸化
			/// </summary>
			public readonly static Field DEH_PAPERLESS_TAX = new Field("DEH_PAPERLESS_TAX", "DC_EP_DEC_HEAD", "是否有税单无纸化");
            /// <summary>
			/// 是否特殊关系确认
			/// </summary>
			public readonly static Field DEH_SPEC_REL_CONFIR = new Field("DEH_SPEC_REL_CONFIR", "DC_EP_DEC_HEAD", "是否特殊关系确认");
            /// <summary>
			/// 是否价格影响确认
			/// </summary>
			public readonly static Field DEH_PRICE_CONFIR = new Field("DEH_PRICE_CONFIR", "DC_EP_DEC_HEAD", "是否价格影响确认");
            /// <summary>
			/// 是否支付特许权使用费确认
			/// </summary>
			public readonly static Field DEH_PAY_OF_LICEN_FEES = new Field("DEH_PAY_OF_LICEN_FEES", "DC_EP_DEC_HEAD", "是否支付特许权使用费确认");
            /// <summary>
			/// 经营单位统一编码
			/// </summary>
			public readonly static Field DEH_TRADE_CO_SCC = new Field("DEH_TRADE_CO_SCC", "DC_EP_DEC_HEAD", "经营单位统一编码");
            /// <summary>
			/// 申报地海关
			/// </summary>
			public readonly static Field DEH_DECL_PORT = new Field("DEH_DECL_PORT", "DC_EP_DEC_HEAD", "申报地海关");
            /// <summary>
			/// 贸易国别(对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段)
			/// </summary>
			public readonly static Field DEH_TRADE_AREA_CODE = new Field("DEH_TRADE_AREA_CODE", "DC_EP_DEC_HEAD", "贸易国别(对应海关参数库中国别(地区)代码表(COUNTRY)中的COUNTRY_CO字段)");
            /// <summary>
			/// 货主单位统一编码
			/// </summary>
			public readonly static Field DEH_OWNER_CODE_SCC = new Field("DEH_OWNER_CODE_SCC", "DC_EP_DEC_HEAD", "货主单位统一编码");
            /// <summary>
			/// 申报代码统一编码
			/// </summary>
			public readonly static Field DEH_AGENT_CODE_SCC = new Field("DEH_AGENT_CODE_SCC", "DC_EP_DEC_HEAD", "申报代码统一编码");
            /// <summary>
			/// EDI单据编号
			/// </summary>
			public readonly static Field DEH_EDI_NO = new Field("DEH_EDI_NO", "DC_EP_DEC_HEAD", "EDI单据编号");
            /// <summary>
			/// 属地申报(1属地申报口岸验放2属地申报属地验放)
			/// </summary>
			public readonly static Field DEH_CUSTOMS_DECLARATION = new Field("DEH_CUSTOMS_DECLARATION", "DC_EP_DEC_HEAD", "属地申报(1属地申报口岸验放2属地申报属地验放)");
            /// <summary>
			/// 收发货人18位编码
			/// </summary>
			public readonly static Field DEH_TRADE_CO_EI = new Field("DEH_TRADE_CO_EI", "DC_EP_DEC_HEAD", "收发货人18位编码");
            /// <summary>
			/// 来源;0:本地1:edi,美设:2
			/// </summary>
			public readonly static Field DEH_SOURCE = new Field("DEH_SOURCE", "DC_EP_DEC_HEAD", "来源;0:本地1:edi,美设:2");
            /// <summary>
			/// 校验通过10,校验不通过20
			/// </summary>
			public readonly static Field DEH_IF_CHECK = new Field("DEH_IF_CHECK", "DC_EP_DEC_HEAD", "校验通过10,校验不通过20");
            /// <summary>
			/// 上传时间
			/// </summary>
			public readonly static Field DEH_UES_FTP_TM = new Field("DEH_UES_FTP_TM", "DC_EP_DEC_HEAD", "上传时间");
            /// <summary>
			/// 新增字段-报关ID
			/// </summary>
			public readonly static Field DEH_ENTRY_ID = new Field("DEH_ENTRY_ID", "DC_EP_DEC_HEAD", "新增字段-报关ID");
            /// <summary>
			/// 新增字段-集箱号
			/// </summary>
			public readonly static Field DEH_FIX_NO = new Field("DEH_FIX_NO", "DC_EP_DEC_HEAD", "新增字段-集箱号");
            /// <summary>
			/// 新增字段-0,未发送节点回执;1,已发送节点回执----美设节点回执
			/// </summary>
			public readonly static Field DEH_MS_NODERECEIPT_STATUS = new Field("DEH_MS_NODERECEIPT_STATUS", "DC_EP_DEC_HEAD", "新增字段-0,未发送节点回执;1,已发送节点回执----美设节点回执");
            /// <summary>
			/// 新增-H2000发送是否成功;0-未发送,1-已发送,2-发送失败
			/// </summary>
			public readonly static Field DEH_SEND_STATUS = new Field("DEH_SEND_STATUS", "DC_EP_DEC_HEAD", "新增-H2000发送是否成功;0-未发送,1-已发送,2-发送失败");
            /// <summary>
			/// 新增-报关数据导入H2000状态;0-未导入;1-已导
			/// </summary>
			public readonly static Field DEH_IMPORT_STATUS = new Field("DEH_IMPORT_STATUS", "DC_EP_DEC_HEAD", "新增-报关数据导入H2000状态;0-未导入;1-已导");
        }
        #endregion
	}
}