//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类Form_List。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Form_List")]
    [Serializable]
    public partial class Form_List : Entity
    {
        #region Model
		private string _pre_entry_id;
		private string _g_no;
		private string _code_t;
		private string _code_s;
		private string _g_name;
		private string _g_model;
		private string _qty_1;
		private string _g_unit;
		private string _decl_price;
		private string _trade_total;
		private string _trade_curr;
		private string _qty_conv;
		private string _unit_1;
		private string _ver_no;
		private string _prdt_no;
		private string _use_to;
		private string _origin_country;
		private string _contr_item;
		private string _qty_2;
		private string _unit_2;
		private string _duty_mode;
		private string _work_usd;
		private string _create_date;
		private string _entry_group;
		private string _FORM_LIST_GUID;
		private string _SUP_TYPE;
		private string _DESTINATION_COUNTRY;

		/// <summary>
		/// 
		/// </summary>
		[Field("pre_entry_id")]
		public string pre_entry_id
		{
			get{ return _pre_entry_id; }
			set
			{
				this.OnPropertyValueChange("pre_entry_id");
				this._pre_entry_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("g_no")]
		public string g_no
		{
			get{ return _g_no; }
			set
			{
				this.OnPropertyValueChange("g_no");
				this._g_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("code_t")]
		public string code_t
		{
			get{ return _code_t; }
			set
			{
				this.OnPropertyValueChange("code_t");
				this._code_t = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("code_s")]
		public string code_s
		{
			get{ return _code_s; }
			set
			{
				this.OnPropertyValueChange("code_s");
				this._code_s = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("g_name")]
		public string g_name
		{
			get{ return _g_name; }
			set
			{
				this.OnPropertyValueChange("g_name");
				this._g_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("g_model")]
		public string g_model
		{
			get{ return _g_model; }
			set
			{
				this.OnPropertyValueChange("g_model");
				this._g_model = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("qty_1")]
		public string qty_1
		{
			get{ return _qty_1; }
			set
			{
				this.OnPropertyValueChange("qty_1");
				this._qty_1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("g_unit")]
		public string g_unit
		{
			get{ return _g_unit; }
			set
			{
				this.OnPropertyValueChange("g_unit");
				this._g_unit = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("decl_price")]
		public string decl_price
		{
			get{ return _decl_price; }
			set
			{
				this.OnPropertyValueChange("decl_price");
				this._decl_price = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("trade_total")]
		public string trade_total
		{
			get{ return _trade_total; }
			set
			{
				this.OnPropertyValueChange("trade_total");
				this._trade_total = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("trade_curr")]
		public string trade_curr
		{
			get{ return _trade_curr; }
			set
			{
				this.OnPropertyValueChange("trade_curr");
				this._trade_curr = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("qty_conv")]
		public string qty_conv
		{
			get{ return _qty_conv; }
			set
			{
				this.OnPropertyValueChange("qty_conv");
				this._qty_conv = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("unit_1")]
		public string unit_1
		{
			get{ return _unit_1; }
			set
			{
				this.OnPropertyValueChange("unit_1");
				this._unit_1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ver_no")]
		public string ver_no
		{
			get{ return _ver_no; }
			set
			{
				this.OnPropertyValueChange("ver_no");
				this._ver_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("prdt_no")]
		public string prdt_no
		{
			get{ return _prdt_no; }
			set
			{
				this.OnPropertyValueChange("prdt_no");
				this._prdt_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("use_to")]
		public string use_to
		{
			get{ return _use_to; }
			set
			{
				this.OnPropertyValueChange("use_to");
				this._use_to = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("origin_country")]
		public string origin_country
		{
			get{ return _origin_country; }
			set
			{
				this.OnPropertyValueChange("origin_country");
				this._origin_country = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("contr_item")]
		public string contr_item
		{
			get{ return _contr_item; }
			set
			{
				this.OnPropertyValueChange("contr_item");
				this._contr_item = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("qty_2")]
		public string qty_2
		{
			get{ return _qty_2; }
			set
			{
				this.OnPropertyValueChange("qty_2");
				this._qty_2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("unit_2")]
		public string unit_2
		{
			get{ return _unit_2; }
			set
			{
				this.OnPropertyValueChange("unit_2");
				this._unit_2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("duty_mode")]
		public string duty_mode
		{
			get{ return _duty_mode; }
			set
			{
				this.OnPropertyValueChange("duty_mode");
				this._duty_mode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("work_usd")]
		public string work_usd
		{
			get{ return _work_usd; }
			set
			{
				this.OnPropertyValueChange("work_usd");
				this._work_usd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_date")]
		public string create_date
		{
			get{ return _create_date; }
			set
			{
				this.OnPropertyValueChange("create_date");
				this._create_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("entry_group")]
		public string entry_group
		{
			get{ return _entry_group; }
			set
			{
				this.OnPropertyValueChange("entry_group");
				this._entry_group = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FORM_LIST_GUID")]
		public string FORM_LIST_GUID
		{
			get{ return _FORM_LIST_GUID; }
			set
			{
				this.OnPropertyValueChange("FORM_LIST_GUID");
				this._FORM_LIST_GUID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUP_TYPE")]
		public string SUP_TYPE
		{
			get{ return _SUP_TYPE; }
			set
			{
				this.OnPropertyValueChange("SUP_TYPE");
				this._SUP_TYPE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DESTINATION_COUNTRY")]
		public string DESTINATION_COUNTRY
		{
			get{ return _DESTINATION_COUNTRY; }
			set
			{
				this.OnPropertyValueChange("DESTINATION_COUNTRY");
				this._DESTINATION_COUNTRY = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.pre_entry_id,
				_.g_no,
				_.code_t,
				_.code_s,
				_.g_name,
				_.g_model,
				_.qty_1,
				_.g_unit,
				_.decl_price,
				_.trade_total,
				_.trade_curr,
				_.qty_conv,
				_.unit_1,
				_.ver_no,
				_.prdt_no,
				_.use_to,
				_.origin_country,
				_.contr_item,
				_.qty_2,
				_.unit_2,
				_.duty_mode,
				_.work_usd,
				_.create_date,
				_.entry_group,
				_.FORM_LIST_GUID,
				_.SUP_TYPE,
				_.DESTINATION_COUNTRY,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._pre_entry_id,
				this._g_no,
				this._code_t,
				this._code_s,
				this._g_name,
				this._g_model,
				this._qty_1,
				this._g_unit,
				this._decl_price,
				this._trade_total,
				this._trade_curr,
				this._qty_conv,
				this._unit_1,
				this._ver_no,
				this._prdt_no,
				this._use_to,
				this._origin_country,
				this._contr_item,
				this._qty_2,
				this._unit_2,
				this._duty_mode,
				this._work_usd,
				this._create_date,
				this._entry_group,
				this._FORM_LIST_GUID,
				this._SUP_TYPE,
				this._DESTINATION_COUNTRY,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Form_List");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field pre_entry_id = new Field("pre_entry_id", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field g_no = new Field("g_no", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field code_t = new Field("code_t", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field code_s = new Field("code_s", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field g_name = new Field("g_name", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field g_model = new Field("g_model", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field qty_1 = new Field("qty_1", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field g_unit = new Field("g_unit", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field decl_price = new Field("decl_price", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field trade_total = new Field("trade_total", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field trade_curr = new Field("trade_curr", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field qty_conv = new Field("qty_conv", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field unit_1 = new Field("unit_1", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ver_no = new Field("ver_no", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field prdt_no = new Field("prdt_no", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field use_to = new Field("use_to", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field origin_country = new Field("origin_country", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field contr_item = new Field("contr_item", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field qty_2 = new Field("qty_2", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field unit_2 = new Field("unit_2", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field duty_mode = new Field("duty_mode", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field work_usd = new Field("work_usd", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field create_date = new Field("create_date", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field entry_group = new Field("entry_group", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FORM_LIST_GUID = new Field("FORM_LIST_GUID", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SUP_TYPE = new Field("SUP_TYPE", "Form_List", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DESTINATION_COUNTRY = new Field("DESTINATION_COUNTRY", "Form_List", "");
        }
        #endregion
	}
}