//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3662
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace Hxj.Model.ServiceAccess
{

    /// <summary>
    /// 实体类Form_Head 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public class Form_Head : Entity
    {
        public Form_Head() : base("Form_Head") { }

        #region Model
        private string _ie_flag;
        private string _pre_entry_id;
        private string _customs_id;
        private string _manual_no;
        private string _contr_no;
        private string _i_e_date;
        private string _d_date;
        private string _trade_co;
        private string _trade_name;
        private string _owner_code;
        private string _owner_name;
        private string _agent_code;
        private string _agent_name;
        private string _traf_mode;
        private string _traf_name;
        private string _voyage_no;
        private string _bill_no;
        private string _trade_mode;
        private string _cut_mode;
        private string _in_ratio;
        private string _pay_way;
        private string _lisence_no;
        private string _trade_country;
        private string _distinate_port;
        private string _district_code;
        private string _appr_no;
        private string _trans_mode;
        private string _fee_mark;
        private string _fee_rate;
        private string _fee_curr;
        private string _insur_mark;
        private string _insur_rate;
        private string _insur_curr;
        private string _other_mark;
        private string _other_rate;
        private string _other_curr;
        private string _pack_no;
        private string _wrap_type;
        private string _gross_wt;
        private string _net_wt;
        private string _ex_source;
        private string _type_er;
        private string _entry_group;
        private string _is_status;
        private string _username;
        private string _create_date;
        private string _del_flag;
        private string _RaDeclNo;
        private string _RaManualNo;
        private string _StoreNo;
        private string _PrdtID;
        private string _i_e_port;
        private string _note_s;
        private string _print_date;
        private string _SUP_FLAG;
        private string _CollectTax;
        private string _Two_Audit;
        private string _chk_surety;
        private string _BILL_TYPE;
        private string _PaperLessTax;
        private string _Tax_Amount;
        private string _is_status_old;
        private string _Tax_No;
        private string _CBE;
        private string _TRADE_CO_SCC;
        private string _AGENT_CODE_SCC;
        private string _OWNER_CODE_SCC;
        private string _PROMISE_ITMES;
        private string _TRADE_AREA_CODE;
        private string _EDI_REMARK_2;
        private string _EDI_NO;
        private string _COP_NO;
        private string _DECL_PORT;
        private string _IS_EXPORT;
        private string _IS_IMPORT;
        private string _JOB_NO;
        private string _CLIENT_NO;
        private string _CheckFlow;
        private string _ENTRY_ID;
        /// <summary>
        /// 
        /// </summary>
        public string ie_flag
        {
            get { return _ie_flag; }
            set
            {
                this.OnPropertyValueChange(_.ie_flag, _ie_flag, value);
                this._ie_flag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string pre_entry_id
        {
            get { return _pre_entry_id; }
            set
            {
                this.OnPropertyValueChange(_.pre_entry_id, _pre_entry_id, value);
                this._pre_entry_id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string customs_id
        {
            get { return _customs_id; }
            set
            {
                this.OnPropertyValueChange(_.customs_id, _customs_id, value);
                this._customs_id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string manual_no
        {
            get { return _manual_no; }
            set
            {
                this.OnPropertyValueChange(_.manual_no, _manual_no, value);
                this._manual_no = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string contr_no
        {
            get { return _contr_no; }
            set
            {
                this.OnPropertyValueChange(_.contr_no, _contr_no, value);
                this._contr_no = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string i_e_date
        {
            get { return _i_e_date; }
            set
            {
                this.OnPropertyValueChange(_.i_e_date, _i_e_date, value);
                this._i_e_date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string d_date
        {
            get { return _d_date; }
            set
            {
                this.OnPropertyValueChange(_.d_date, _d_date, value);
                this._d_date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string trade_co
        {
            get { return _trade_co; }
            set
            {
                this.OnPropertyValueChange(_.trade_co, _trade_co, value);
                this._trade_co = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string trade_name
        {
            get { return _trade_name; }
            set
            {
                this.OnPropertyValueChange(_.trade_name, _trade_name, value);
                this._trade_name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string owner_code
        {
            get { return _owner_code; }
            set
            {
                this.OnPropertyValueChange(_.owner_code, _owner_code, value);
                this._owner_code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string owner_name
        {
            get { return _owner_name; }
            set
            {
                this.OnPropertyValueChange(_.owner_name, _owner_name, value);
                this._owner_name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string agent_code
        {
            get { return _agent_code; }
            set
            {
                this.OnPropertyValueChange(_.agent_code, _agent_code, value);
                this._agent_code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string agent_name
        {
            get { return _agent_name; }
            set
            {
                this.OnPropertyValueChange(_.agent_name, _agent_name, value);
                this._agent_name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string traf_mode
        {
            get { return _traf_mode; }
            set
            {
                this.OnPropertyValueChange(_.traf_mode, _traf_mode, value);
                this._traf_mode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string traf_name
        {
            get { return _traf_name; }
            set
            {
                this.OnPropertyValueChange(_.traf_name, _traf_name, value);
                this._traf_name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string voyage_no
        {
            get { return _voyage_no; }
            set
            {
                this.OnPropertyValueChange(_.voyage_no, _voyage_no, value);
                this._voyage_no = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string bill_no
        {
            get { return _bill_no; }
            set
            {
                this.OnPropertyValueChange(_.bill_no, _bill_no, value);
                this._bill_no = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string trade_mode
        {
            get { return _trade_mode; }
            set
            {
                this.OnPropertyValueChange(_.trade_mode, _trade_mode, value);
                this._trade_mode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string cut_mode
        {
            get { return _cut_mode; }
            set
            {
                this.OnPropertyValueChange(_.cut_mode, _cut_mode, value);
                this._cut_mode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string in_ratio
        {
            get { return _in_ratio; }
            set
            {
                this.OnPropertyValueChange(_.in_ratio, _in_ratio, value);
                this._in_ratio = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string pay_way
        {
            get { return _pay_way; }
            set
            {
                this.OnPropertyValueChange(_.pay_way, _pay_way, value);
                this._pay_way = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string lisence_no
        {
            get { return _lisence_no; }
            set
            {
                this.OnPropertyValueChange(_.lisence_no, _lisence_no, value);
                this._lisence_no = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string trade_country
        {
            get { return _trade_country; }
            set
            {
                this.OnPropertyValueChange(_.trade_country, _trade_country, value);
                this._trade_country = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string distinate_port
        {
            get { return _distinate_port; }
            set
            {
                this.OnPropertyValueChange(_.distinate_port, _distinate_port, value);
                this._distinate_port = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string district_code
        {
            get { return _district_code; }
            set
            {
                this.OnPropertyValueChange(_.district_code, _district_code, value);
                this._district_code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string appr_no
        {
            get { return _appr_no; }
            set
            {
                this.OnPropertyValueChange(_.appr_no, _appr_no, value);
                this._appr_no = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string trans_mode
        {
            get { return _trans_mode; }
            set
            {
                this.OnPropertyValueChange(_.trans_mode, _trans_mode, value);
                this._trans_mode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string fee_mark
        {
            get { return _fee_mark; }
            set
            {
                this.OnPropertyValueChange(_.fee_mark, _fee_mark, value);
                this._fee_mark = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string fee_rate
        {
            get { return _fee_rate; }
            set
            {
                this.OnPropertyValueChange(_.fee_rate, _fee_rate, value);
                this._fee_rate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string fee_curr
        {
            get { return _fee_curr; }
            set
            {
                this.OnPropertyValueChange(_.fee_curr, _fee_curr, value);
                this._fee_curr = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string insur_mark
        {
            get { return _insur_mark; }
            set
            {
                this.OnPropertyValueChange(_.insur_mark, _insur_mark, value);
                this._insur_mark = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string insur_rate
        {
            get { return _insur_rate; }
            set
            {
                this.OnPropertyValueChange(_.insur_rate, _insur_rate, value);
                this._insur_rate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string insur_curr
        {
            get { return _insur_curr; }
            set
            {
                this.OnPropertyValueChange(_.insur_curr, _insur_curr, value);
                this._insur_curr = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string other_mark
        {
            get { return _other_mark; }
            set
            {
                this.OnPropertyValueChange(_.other_mark, _other_mark, value);
                this._other_mark = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string other_rate
        {
            get { return _other_rate; }
            set
            {
                this.OnPropertyValueChange(_.other_rate, _other_rate, value);
                this._other_rate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string other_curr
        {
            get { return _other_curr; }
            set
            {
                this.OnPropertyValueChange(_.other_curr, _other_curr, value);
                this._other_curr = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string pack_no
        {
            get { return _pack_no; }
            set
            {
                this.OnPropertyValueChange(_.pack_no, _pack_no, value);
                this._pack_no = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string wrap_type
        {
            get { return _wrap_type; }
            set
            {
                this.OnPropertyValueChange(_.wrap_type, _wrap_type, value);
                this._wrap_type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string gross_wt
        {
            get { return _gross_wt; }
            set
            {
                this.OnPropertyValueChange(_.gross_wt, _gross_wt, value);
                this._gross_wt = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string net_wt
        {
            get { return _net_wt; }
            set
            {
                this.OnPropertyValueChange(_.net_wt, _net_wt, value);
                this._net_wt = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ex_source
        {
            get { return _ex_source; }
            set
            {
                this.OnPropertyValueChange(_.ex_source, _ex_source, value);
                this._ex_source = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string type_er
        {
            get { return _type_er; }
            set
            {
                this.OnPropertyValueChange(_.type_er, _type_er, value);
                this._type_er = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string entry_group
        {
            get { return _entry_group; }
            set
            {
                this.OnPropertyValueChange(_.entry_group, _entry_group, value);
                this._entry_group = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string is_status
        {
            get { return _is_status; }
            set
            {
                this.OnPropertyValueChange(_.is_status, _is_status, value);
                this._is_status = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string username
        {
            get { return _username; }
            set
            {
                this.OnPropertyValueChange(_.username, _username, value);
                this._username = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string create_date
        {
            get { return _create_date; }
            set
            {
                this.OnPropertyValueChange(_.create_date, _create_date, value);
                this._create_date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string del_flag
        {
            get { return _del_flag; }
            set
            {
                this.OnPropertyValueChange(_.del_flag, _del_flag, value);
                this._del_flag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string RaDeclNo
        {
            get { return _RaDeclNo; }
            set
            {
                this.OnPropertyValueChange(_.RaDeclNo, _RaDeclNo, value);
                this._RaDeclNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string RaManualNo
        {
            get { return _RaManualNo; }
            set
            {
                this.OnPropertyValueChange(_.RaManualNo, _RaManualNo, value);
                this._RaManualNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNo
        {
            get { return _StoreNo; }
            set
            {
                this.OnPropertyValueChange(_.StoreNo, _StoreNo, value);
                this._StoreNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PrdtID
        {
            get { return _PrdtID; }
            set
            {
                this.OnPropertyValueChange(_.PrdtID, _PrdtID, value);
                this._PrdtID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string i_e_port
        {
            get { return _i_e_port; }
            set
            {
                this.OnPropertyValueChange(_.i_e_port, _i_e_port, value);
                this._i_e_port = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string note_s
        {
            get { return _note_s; }
            set
            {
                this.OnPropertyValueChange(_.note_s, _note_s, value);
                this._note_s = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string print_date
        {
            get { return _print_date; }
            set
            {
                this.OnPropertyValueChange(_.print_date, _print_date, value);
                this._print_date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SUP_FLAG
        {
            get { return _SUP_FLAG; }
            set
            {
                this.OnPropertyValueChange(_.SUP_FLAG, _SUP_FLAG, value);
                this._SUP_FLAG = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CollectTax
        {
            get { return _CollectTax; }
            set
            {
                this.OnPropertyValueChange(_.CollectTax, _CollectTax, value);
                this._CollectTax = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Two_Audit
        {
            get { return _Two_Audit; }
            set
            {
                this.OnPropertyValueChange(_.Two_Audit, _Two_Audit, value);
                this._Two_Audit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string chk_surety
        {
            get { return _chk_surety; }
            set
            {
                this.OnPropertyValueChange(_.chk_surety, _chk_surety, value);
                this._chk_surety = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string BILL_TYPE
        {
            get { return _BILL_TYPE; }
            set
            {
                this.OnPropertyValueChange(_.BILL_TYPE, _BILL_TYPE, value);
                this._BILL_TYPE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PaperLessTax
        {
            get { return _PaperLessTax; }
            set
            {
                this.OnPropertyValueChange(_.PaperLessTax, _PaperLessTax, value);
                this._PaperLessTax = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Tax_Amount
        {
            get { return _Tax_Amount; }
            set
            {
                this.OnPropertyValueChange(_.Tax_Amount, _Tax_Amount, value);
                this._Tax_Amount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string is_status_old
        {
            get { return _is_status_old; }
            set
            {
                this.OnPropertyValueChange(_.is_status_old, _is_status_old, value);
                this._is_status_old = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Tax_No
        {
            get { return _Tax_No; }
            set
            {
                this.OnPropertyValueChange(_.Tax_No, _Tax_No, value);
                this._Tax_No = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CBE
        {
            get { return _CBE; }
            set
            {
                this.OnPropertyValueChange(_.CBE, _CBE, value);
                this._CBE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string TRADE_CO_SCC
        {
            get { return _TRADE_CO_SCC; }
            set
            {
                this.OnPropertyValueChange(_.TRADE_CO_SCC, _TRADE_CO_SCC, value);
                this._TRADE_CO_SCC = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string AGENT_CODE_SCC
        {
            get { return _AGENT_CODE_SCC; }
            set
            {
                this.OnPropertyValueChange(_.AGENT_CODE_SCC, _AGENT_CODE_SCC, value);
                this._AGENT_CODE_SCC = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OWNER_CODE_SCC
        {
            get { return _OWNER_CODE_SCC; }
            set
            {
                this.OnPropertyValueChange(_.OWNER_CODE_SCC, _OWNER_CODE_SCC, value);
                this._OWNER_CODE_SCC = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PROMISE_ITMES
        {
            get { return _PROMISE_ITMES; }
            set
            {
                this.OnPropertyValueChange(_.PROMISE_ITMES, _PROMISE_ITMES, value);
                this._PROMISE_ITMES = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string TRADE_AREA_CODE
        {
            get { return _TRADE_AREA_CODE; }
            set
            {
                this.OnPropertyValueChange(_.TRADE_AREA_CODE, _TRADE_AREA_CODE, value);
                this._TRADE_AREA_CODE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EDI_REMARK_2
        {
            get { return _EDI_REMARK_2; }
            set
            {
                this.OnPropertyValueChange(_.EDI_REMARK_2, _EDI_REMARK_2, value);
                this._EDI_REMARK_2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EDI_NO
        {
            get { return _EDI_NO; }
            set
            {
                this.OnPropertyValueChange(_.EDI_NO, _EDI_NO, value);
                this._EDI_NO = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string COP_NO
        {
            get { return _COP_NO; }
            set
            {
                this.OnPropertyValueChange(_.COP_NO, _COP_NO, value);
                this._COP_NO = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DECL_PORT
        {
            get { return _DECL_PORT; }
            set
            {
                this.OnPropertyValueChange(_.DECL_PORT, _DECL_PORT, value);
                this._DECL_PORT = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string IS_EXPORT
        {
            get { return _IS_EXPORT; }
            set
            {
                this.OnPropertyValueChange(_.IS_EXPORT, _IS_EXPORT, value);
                this._IS_EXPORT = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string IS_IMPORT
        {
            get { return _IS_IMPORT; }
            set
            {
                this.OnPropertyValueChange(_.IS_IMPORT, _IS_IMPORT, value);
                this._IS_IMPORT = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string JOB_NO
        {
            get { return _JOB_NO; }
            set
            {
                this.OnPropertyValueChange(_.JOB_NO, _JOB_NO, value);
                this._JOB_NO = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CLIENT_NO
        {
            get { return _CLIENT_NO; }
            set
            {
                this.OnPropertyValueChange(_.CLIENT_NO, _CLIENT_NO, value);
                this._CLIENT_NO = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CheckFlow
        {
            get { return _CheckFlow; }
            set
            {
                this.OnPropertyValueChange(_.CheckFlow, _CheckFlow, value);
                this._CheckFlow = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ENTRY_ID
        {
            get { return _ENTRY_ID; }
            set
            {
                this.OnPropertyValueChange(_.ENTRY_ID, _ENTRY_ID, value);
                this._ENTRY_ID = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ie_flag,
                _.pre_entry_id,
                _.customs_id,
                _.manual_no,
                _.contr_no,
                _.i_e_date,
                _.d_date,
                _.trade_co,
                _.trade_name,
                _.owner_code,
                _.owner_name,
                _.agent_code,
                _.agent_name,
                _.traf_mode,
                _.traf_name,
                _.voyage_no,
                _.bill_no,
                _.trade_mode,
                _.cut_mode,
                _.in_ratio,
                _.pay_way,
                _.lisence_no,
                _.trade_country,
                _.distinate_port,
                _.district_code,
                _.appr_no,
                _.trans_mode,
                _.fee_mark,
                _.fee_rate,
                _.fee_curr,
                _.insur_mark,
                _.insur_rate,
                _.insur_curr,
                _.other_mark,
                _.other_rate,
                _.other_curr,
                _.pack_no,
                _.wrap_type,
                _.gross_wt,
                _.net_wt,
                _.ex_source,
                _.type_er,
                _.entry_group,
                _.is_status,
                _.username,
                _.create_date,
                _.del_flag,
                _.RaDeclNo,
                _.RaManualNo,
                _.StoreNo,
                _.PrdtID,
                _.i_e_port,
                _.note_s,
                _.print_date,
                _.SUP_FLAG,
                _.CollectTax,
                _.Two_Audit,
                _.chk_surety,
                _.BILL_TYPE,
                _.PaperLessTax,
                _.Tax_Amount,
                _.is_status_old,
                _.Tax_No,
                _.CBE,
                _.TRADE_CO_SCC,
                _.AGENT_CODE_SCC,
                _.OWNER_CODE_SCC,
                _.PROMISE_ITMES,
                _.TRADE_AREA_CODE,
                _.EDI_REMARK_2,
                _.EDI_NO,
                _.COP_NO,
                _.DECL_PORT,
                _.IS_EXPORT,
                _.IS_IMPORT,
                _.JOB_NO,
                _.CLIENT_NO,
                _.CheckFlow,
                _.ENTRY_ID};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ie_flag,
                this._pre_entry_id,
                this._customs_id,
                this._manual_no,
                this._contr_no,
                this._i_e_date,
                this._d_date,
                this._trade_co,
                this._trade_name,
                this._owner_code,
                this._owner_name,
                this._agent_code,
                this._agent_name,
                this._traf_mode,
                this._traf_name,
                this._voyage_no,
                this._bill_no,
                this._trade_mode,
                this._cut_mode,
                this._in_ratio,
                this._pay_way,
                this._lisence_no,
                this._trade_country,
                this._distinate_port,
                this._district_code,
                this._appr_no,
                this._trans_mode,
                this._fee_mark,
                this._fee_rate,
                this._fee_curr,
                this._insur_mark,
                this._insur_rate,
                this._insur_curr,
                this._other_mark,
                this._other_rate,
                this._other_curr,
                this._pack_no,
                this._wrap_type,
                this._gross_wt,
                this._net_wt,
                this._ex_source,
                this._type_er,
                this._entry_group,
                this._is_status,
                this._username,
                this._create_date,
                this._del_flag,
                this._RaDeclNo,
                this._RaManualNo,
                this._StoreNo,
                this._PrdtID,
                this._i_e_port,
                this._note_s,
                this._print_date,
                this._SUP_FLAG,
                this._CollectTax,
                this._Two_Audit,
                this._chk_surety,
                this._BILL_TYPE,
                this._PaperLessTax,
                this._Tax_Amount,
                this._is_status_old,
                this._Tax_No,
                this._CBE,
                this._TRADE_CO_SCC,
                this._AGENT_CODE_SCC,
                this._OWNER_CODE_SCC,
                this._PROMISE_ITMES,
                this._TRADE_AREA_CODE,
                this._EDI_REMARK_2,
                this._EDI_NO,
                this._COP_NO,
                this._DECL_PORT,
                this._IS_EXPORT,
                this._IS_IMPORT,
                this._JOB_NO,
                this._CLIENT_NO,
                this._CheckFlow,
                this._ENTRY_ID};
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(IDataReader reader)
        {
            this._ie_flag = DataUtils.ConvertValue<string>(reader["ie_flag"]);
            this._pre_entry_id = DataUtils.ConvertValue<string>(reader["pre_entry_id"]);
            this._customs_id = DataUtils.ConvertValue<string>(reader["customs_id"]);
            this._manual_no = DataUtils.ConvertValue<string>(reader["manual_no"]);
            this._contr_no = DataUtils.ConvertValue<string>(reader["contr_no"]);
            this._i_e_date = DataUtils.ConvertValue<string>(reader["i_e_date"]);
            this._d_date = DataUtils.ConvertValue<string>(reader["d_date"]);
            this._trade_co = DataUtils.ConvertValue<string>(reader["trade_co"]);
            this._trade_name = DataUtils.ConvertValue<string>(reader["trade_name"]);
            this._owner_code = DataUtils.ConvertValue<string>(reader["owner_code"]);
            this._owner_name = DataUtils.ConvertValue<string>(reader["owner_name"]);
            this._agent_code = DataUtils.ConvertValue<string>(reader["agent_code"]);
            this._agent_name = DataUtils.ConvertValue<string>(reader["agent_name"]);
            this._traf_mode = DataUtils.ConvertValue<string>(reader["traf_mode"]);
            this._traf_name = DataUtils.ConvertValue<string>(reader["traf_name"]);
            this._voyage_no = DataUtils.ConvertValue<string>(reader["voyage_no"]);
            this._bill_no = DataUtils.ConvertValue<string>(reader["bill_no"]);
            this._trade_mode = DataUtils.ConvertValue<string>(reader["trade_mode"]);
            this._cut_mode = DataUtils.ConvertValue<string>(reader["cut_mode"]);
            this._in_ratio = DataUtils.ConvertValue<string>(reader["in_ratio"]);
            this._pay_way = DataUtils.ConvertValue<string>(reader["pay_way"]);
            this._lisence_no = DataUtils.ConvertValue<string>(reader["lisence_no"]);
            this._trade_country = DataUtils.ConvertValue<string>(reader["trade_country"]);
            this._distinate_port = DataUtils.ConvertValue<string>(reader["distinate_port"]);
            this._district_code = DataUtils.ConvertValue<string>(reader["district_code"]);
            this._appr_no = DataUtils.ConvertValue<string>(reader["appr_no"]);
            this._trans_mode = DataUtils.ConvertValue<string>(reader["trans_mode"]);
            this._fee_mark = DataUtils.ConvertValue<string>(reader["fee_mark"]);
            this._fee_rate = DataUtils.ConvertValue<string>(reader["fee_rate"]);
            this._fee_curr = DataUtils.ConvertValue<string>(reader["fee_curr"]);
            this._insur_mark = DataUtils.ConvertValue<string>(reader["insur_mark"]);
            this._insur_rate = DataUtils.ConvertValue<string>(reader["insur_rate"]);
            this._insur_curr = DataUtils.ConvertValue<string>(reader["insur_curr"]);
            this._other_mark = DataUtils.ConvertValue<string>(reader["other_mark"]);
            this._other_rate = DataUtils.ConvertValue<string>(reader["other_rate"]);
            this._other_curr = DataUtils.ConvertValue<string>(reader["other_curr"]);
            this._pack_no = DataUtils.ConvertValue<string>(reader["pack_no"]);
            this._wrap_type = DataUtils.ConvertValue<string>(reader["wrap_type"]);
            this._gross_wt = DataUtils.ConvertValue<string>(reader["gross_wt"]);
            this._net_wt = DataUtils.ConvertValue<string>(reader["net_wt"]);
            this._ex_source = DataUtils.ConvertValue<string>(reader["ex_source"]);
            this._type_er = DataUtils.ConvertValue<string>(reader["type_er"]);
            this._entry_group = DataUtils.ConvertValue<string>(reader["entry_group"]);
            this._is_status = DataUtils.ConvertValue<string>(reader["is_status"]);
            this._username = DataUtils.ConvertValue<string>(reader["username"]);
            this._create_date = DataUtils.ConvertValue<string>(reader["create_date"]);
            this._del_flag = DataUtils.ConvertValue<string>(reader["del_flag"]);
            this._RaDeclNo = DataUtils.ConvertValue<string>(reader["RaDeclNo"]);
            this._RaManualNo = DataUtils.ConvertValue<string>(reader["RaManualNo"]);
            this._StoreNo = DataUtils.ConvertValue<string>(reader["StoreNo"]);
            this._PrdtID = DataUtils.ConvertValue<string>(reader["PrdtID"]);
            this._i_e_port = DataUtils.ConvertValue<string>(reader["i_e_port"]);
            this._note_s = DataUtils.ConvertValue<string>(reader["note_s"]);
            this._print_date = DataUtils.ConvertValue<string>(reader["print_date"]);
            this._SUP_FLAG = DataUtils.ConvertValue<string>(reader["SUP_FLAG"]);
            this._CollectTax = DataUtils.ConvertValue<string>(reader["CollectTax"]);
            this._Two_Audit = DataUtils.ConvertValue<string>(reader["Two_Audit"]);
            this._chk_surety = DataUtils.ConvertValue<string>(reader["chk_surety"]);
            this._BILL_TYPE = DataUtils.ConvertValue<string>(reader["BILL_TYPE"]);
            this._PaperLessTax = DataUtils.ConvertValue<string>(reader["PaperLessTax"]);
            this._Tax_Amount = DataUtils.ConvertValue<string>(reader["Tax_Amount"]);
            this._is_status_old = DataUtils.ConvertValue<string>(reader["is_status_old"]);
            this._Tax_No = DataUtils.ConvertValue<string>(reader["Tax_No"]);
            this._CBE = DataUtils.ConvertValue<string>(reader["CBE"]);
            this._TRADE_CO_SCC = DataUtils.ConvertValue<string>(reader["TRADE_CO_SCC"]);
            this._AGENT_CODE_SCC = DataUtils.ConvertValue<string>(reader["AGENT_CODE_SCC"]);
            this._OWNER_CODE_SCC = DataUtils.ConvertValue<string>(reader["OWNER_CODE_SCC"]);
            this._PROMISE_ITMES = DataUtils.ConvertValue<string>(reader["PROMISE_ITMES"]);
            this._TRADE_AREA_CODE = DataUtils.ConvertValue<string>(reader["TRADE_AREA_CODE"]);
            this._EDI_REMARK_2 = DataUtils.ConvertValue<string>(reader["EDI_REMARK_2"]);
            this._EDI_NO = DataUtils.ConvertValue<string>(reader["EDI_NO"]);
            this._COP_NO = DataUtils.ConvertValue<string>(reader["COP_NO"]);
            this._DECL_PORT = DataUtils.ConvertValue<string>(reader["DECL_PORT"]);
            this._IS_EXPORT = DataUtils.ConvertValue<string>(reader["IS_EXPORT"]);
            this._IS_IMPORT = DataUtils.ConvertValue<string>(reader["IS_IMPORT"]);
            this._JOB_NO = DataUtils.ConvertValue<string>(reader["JOB_NO"]);
            this._CLIENT_NO = DataUtils.ConvertValue<string>(reader["CLIENT_NO"]);
            this._CheckFlow = DataUtils.ConvertValue<string>(reader["CheckFlow"]);
            this._ENTRY_ID = DataUtils.ConvertValue<string>(reader["ENTRY_ID"]);
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(DataRow row)
        {
            this._ie_flag = DataUtils.ConvertValue<string>(row["ie_flag"]);
            this._pre_entry_id = DataUtils.ConvertValue<string>(row["pre_entry_id"]);
            this._customs_id = DataUtils.ConvertValue<string>(row["customs_id"]);
            this._manual_no = DataUtils.ConvertValue<string>(row["manual_no"]);
            this._contr_no = DataUtils.ConvertValue<string>(row["contr_no"]);
            this._i_e_date = DataUtils.ConvertValue<string>(row["i_e_date"]);
            this._d_date = DataUtils.ConvertValue<string>(row["d_date"]);
            this._trade_co = DataUtils.ConvertValue<string>(row["trade_co"]);
            this._trade_name = DataUtils.ConvertValue<string>(row["trade_name"]);
            this._owner_code = DataUtils.ConvertValue<string>(row["owner_code"]);
            this._owner_name = DataUtils.ConvertValue<string>(row["owner_name"]);
            this._agent_code = DataUtils.ConvertValue<string>(row["agent_code"]);
            this._agent_name = DataUtils.ConvertValue<string>(row["agent_name"]);
            this._traf_mode = DataUtils.ConvertValue<string>(row["traf_mode"]);
            this._traf_name = DataUtils.ConvertValue<string>(row["traf_name"]);
            this._voyage_no = DataUtils.ConvertValue<string>(row["voyage_no"]);
            this._bill_no = DataUtils.ConvertValue<string>(row["bill_no"]);
            this._trade_mode = DataUtils.ConvertValue<string>(row["trade_mode"]);
            this._cut_mode = DataUtils.ConvertValue<string>(row["cut_mode"]);
            this._in_ratio = DataUtils.ConvertValue<string>(row["in_ratio"]);
            this._pay_way = DataUtils.ConvertValue<string>(row["pay_way"]);
            this._lisence_no = DataUtils.ConvertValue<string>(row["lisence_no"]);
            this._trade_country = DataUtils.ConvertValue<string>(row["trade_country"]);
            this._distinate_port = DataUtils.ConvertValue<string>(row["distinate_port"]);
            this._district_code = DataUtils.ConvertValue<string>(row["district_code"]);
            this._appr_no = DataUtils.ConvertValue<string>(row["appr_no"]);
            this._trans_mode = DataUtils.ConvertValue<string>(row["trans_mode"]);
            this._fee_mark = DataUtils.ConvertValue<string>(row["fee_mark"]);
            this._fee_rate = DataUtils.ConvertValue<string>(row["fee_rate"]);
            this._fee_curr = DataUtils.ConvertValue<string>(row["fee_curr"]);
            this._insur_mark = DataUtils.ConvertValue<string>(row["insur_mark"]);
            this._insur_rate = DataUtils.ConvertValue<string>(row["insur_rate"]);
            this._insur_curr = DataUtils.ConvertValue<string>(row["insur_curr"]);
            this._other_mark = DataUtils.ConvertValue<string>(row["other_mark"]);
            this._other_rate = DataUtils.ConvertValue<string>(row["other_rate"]);
            this._other_curr = DataUtils.ConvertValue<string>(row["other_curr"]);
            this._pack_no = DataUtils.ConvertValue<string>(row["pack_no"]);
            this._wrap_type = DataUtils.ConvertValue<string>(row["wrap_type"]);
            this._gross_wt = DataUtils.ConvertValue<string>(row["gross_wt"]);
            this._net_wt = DataUtils.ConvertValue<string>(row["net_wt"]);
            this._ex_source = DataUtils.ConvertValue<string>(row["ex_source"]);
            this._type_er = DataUtils.ConvertValue<string>(row["type_er"]);
            this._entry_group = DataUtils.ConvertValue<string>(row["entry_group"]);
            this._is_status = DataUtils.ConvertValue<string>(row["is_status"]);
            this._username = DataUtils.ConvertValue<string>(row["username"]);
            this._create_date = DataUtils.ConvertValue<string>(row["create_date"]);
            this._del_flag = DataUtils.ConvertValue<string>(row["del_flag"]);
            this._RaDeclNo = DataUtils.ConvertValue<string>(row["RaDeclNo"]);
            this._RaManualNo = DataUtils.ConvertValue<string>(row["RaManualNo"]);
            this._StoreNo = DataUtils.ConvertValue<string>(row["StoreNo"]);
            this._PrdtID = DataUtils.ConvertValue<string>(row["PrdtID"]);
            this._i_e_port = DataUtils.ConvertValue<string>(row["i_e_port"]);
            this._note_s = DataUtils.ConvertValue<string>(row["note_s"]);
            this._print_date = DataUtils.ConvertValue<string>(row["print_date"]);
            this._SUP_FLAG = DataUtils.ConvertValue<string>(row["SUP_FLAG"]);
            this._CollectTax = DataUtils.ConvertValue<string>(row["CollectTax"]);
            this._Two_Audit = DataUtils.ConvertValue<string>(row["Two_Audit"]);
            this._chk_surety = DataUtils.ConvertValue<string>(row["chk_surety"]);
            this._BILL_TYPE = DataUtils.ConvertValue<string>(row["BILL_TYPE"]);
            this._PaperLessTax = DataUtils.ConvertValue<string>(row["PaperLessTax"]);
            this._Tax_Amount = DataUtils.ConvertValue<string>(row["Tax_Amount"]);
            this._is_status_old = DataUtils.ConvertValue<string>(row["is_status_old"]);
            this._Tax_No = DataUtils.ConvertValue<string>(row["Tax_No"]);
            this._CBE = DataUtils.ConvertValue<string>(row["CBE"]);
            this._TRADE_CO_SCC = DataUtils.ConvertValue<string>(row["TRADE_CO_SCC"]);
            this._AGENT_CODE_SCC = DataUtils.ConvertValue<string>(row["AGENT_CODE_SCC"]);
            this._OWNER_CODE_SCC = DataUtils.ConvertValue<string>(row["OWNER_CODE_SCC"]);
            this._PROMISE_ITMES = DataUtils.ConvertValue<string>(row["PROMISE_ITMES"]);
            this._TRADE_AREA_CODE = DataUtils.ConvertValue<string>(row["TRADE_AREA_CODE"]);
            this._EDI_REMARK_2 = DataUtils.ConvertValue<string>(row["EDI_REMARK_2"]);
            this._EDI_NO = DataUtils.ConvertValue<string>(row["EDI_NO"]);
            this._COP_NO = DataUtils.ConvertValue<string>(row["COP_NO"]);
            this._DECL_PORT = DataUtils.ConvertValue<string>(row["DECL_PORT"]);
            this._IS_EXPORT = DataUtils.ConvertValue<string>(row["IS_EXPORT"]);
            this._IS_IMPORT = DataUtils.ConvertValue<string>(row["IS_IMPORT"]);
            this._JOB_NO = DataUtils.ConvertValue<string>(row["JOB_NO"]);
            this._CLIENT_NO = DataUtils.ConvertValue<string>(row["CLIENT_NO"]);
            this._CheckFlow = DataUtils.ConvertValue<string>(row["CheckFlow"]);
            this._ENTRY_ID = DataUtils.ConvertValue<string>(row["ENTRY_ID"]);
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Form_Head");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ie_flag = new Field("ie_flag", "Form_Head", "ie_flag");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field pre_entry_id = new Field("pre_entry_id", "Form_Head", "pre_entry_id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field customs_id = new Field("customs_id", "Form_Head", "customs_id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field manual_no = new Field("manual_no", "Form_Head", "manual_no");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field contr_no = new Field("contr_no", "Form_Head", "contr_no");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field i_e_date = new Field("i_e_date", "Form_Head", "i_e_date");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field d_date = new Field("d_date", "Form_Head", "d_date");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field trade_co = new Field("trade_co", "Form_Head", "trade_co");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field trade_name = new Field("trade_name", "Form_Head", "trade_name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field owner_code = new Field("owner_code", "Form_Head", "owner_code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field owner_name = new Field("owner_name", "Form_Head", "owner_name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field agent_code = new Field("agent_code", "Form_Head", "agent_code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field agent_name = new Field("agent_name", "Form_Head", "agent_name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field traf_mode = new Field("traf_mode", "Form_Head", "traf_mode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field traf_name = new Field("traf_name", "Form_Head", "traf_name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field voyage_no = new Field("voyage_no", "Form_Head", "voyage_no");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field bill_no = new Field("bill_no", "Form_Head", "bill_no");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field trade_mode = new Field("trade_mode", "Form_Head", "trade_mode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field cut_mode = new Field("cut_mode", "Form_Head", "cut_mode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field in_ratio = new Field("in_ratio", "Form_Head", "in_ratio");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field pay_way = new Field("pay_way", "Form_Head", "pay_way");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field lisence_no = new Field("lisence_no", "Form_Head", "lisence_no");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field trade_country = new Field("trade_country", "Form_Head", "trade_country");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field distinate_port = new Field("distinate_port", "Form_Head", "distinate_port");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field district_code = new Field("district_code", "Form_Head", "district_code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field appr_no = new Field("appr_no", "Form_Head", "appr_no");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field trans_mode = new Field("trans_mode", "Form_Head", "trans_mode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field fee_mark = new Field("fee_mark", "Form_Head", "fee_mark");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field fee_rate = new Field("fee_rate", "Form_Head", "fee_rate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field fee_curr = new Field("fee_curr", "Form_Head", "fee_curr");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field insur_mark = new Field("insur_mark", "Form_Head", "insur_mark");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field insur_rate = new Field("insur_rate", "Form_Head", "insur_rate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field insur_curr = new Field("insur_curr", "Form_Head", "insur_curr");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field other_mark = new Field("other_mark", "Form_Head", "other_mark");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field other_rate = new Field("other_rate", "Form_Head", "other_rate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field other_curr = new Field("other_curr", "Form_Head", "other_curr");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field pack_no = new Field("pack_no", "Form_Head", "pack_no");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field wrap_type = new Field("wrap_type", "Form_Head", "wrap_type");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field gross_wt = new Field("gross_wt", "Form_Head", "gross_wt");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field net_wt = new Field("net_wt", "Form_Head", "net_wt");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ex_source = new Field("ex_source", "Form_Head", "ex_source");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field type_er = new Field("type_er", "Form_Head", "type_er");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field entry_group = new Field("entry_group", "Form_Head", "entry_group");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field is_status = new Field("is_status", "Form_Head", "is_status");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field username = new Field("username", "Form_Head", "username");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field create_date = new Field("create_date", "Form_Head", "create_date");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field del_flag = new Field("del_flag", "Form_Head", "del_flag");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RaDeclNo = new Field("RaDeclNo", "Form_Head", "RaDeclNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RaManualNo = new Field("RaManualNo", "Form_Head", "RaManualNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field StoreNo = new Field("StoreNo", "Form_Head", "StoreNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PrdtID = new Field("PrdtID", "Form_Head", "PrdtID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field i_e_port = new Field("i_e_port", "Form_Head", "i_e_port");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field note_s = new Field("note_s", "Form_Head", "note_s");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field print_date = new Field("print_date", "Form_Head", "print_date");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SUP_FLAG = new Field("SUP_FLAG", "Form_Head", "SUP_FLAG");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CollectTax = new Field("CollectTax", "Form_Head", "CollectTax");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Two_Audit = new Field("Two_Audit", "Form_Head", "Two_Audit");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field chk_surety = new Field("chk_surety", "Form_Head", "chk_surety");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BILL_TYPE = new Field("BILL_TYPE", "Form_Head", "BILL_TYPE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PaperLessTax = new Field("PaperLessTax", "Form_Head", "PaperLessTax");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Tax_Amount = new Field("Tax_Amount", "Form_Head", "Tax_Amount");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field is_status_old = new Field("is_status_old", "Form_Head", "is_status_old");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Tax_No = new Field("Tax_No", "Form_Head", "Tax_No");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CBE = new Field("CBE", "Form_Head", "CBE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TRADE_CO_SCC = new Field("TRADE_CO_SCC", "Form_Head", "TRADE_CO_SCC");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AGENT_CODE_SCC = new Field("AGENT_CODE_SCC", "Form_Head", "AGENT_CODE_SCC");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OWNER_CODE_SCC = new Field("OWNER_CODE_SCC", "Form_Head", "OWNER_CODE_SCC");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PROMISE_ITMES = new Field("PROMISE_ITMES", "Form_Head", "PROMISE_ITMES");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TRADE_AREA_CODE = new Field("TRADE_AREA_CODE", "Form_Head", "TRADE_AREA_CODE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field EDI_REMARK_2 = new Field("EDI_REMARK_2", "Form_Head", "EDI_REMARK_2");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field EDI_NO = new Field("EDI_NO", "Form_Head", "EDI_NO");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field COP_NO = new Field("COP_NO", "Form_Head", "COP_NO");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DECL_PORT = new Field("DECL_PORT", "Form_Head", "DECL_PORT");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IS_EXPORT = new Field("IS_EXPORT", "Form_Head", "IS_EXPORT");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IS_IMPORT = new Field("IS_IMPORT", "Form_Head", "IS_IMPORT");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field JOB_NO = new Field("JOB_NO", "Form_Head", "JOB_NO");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CLIENT_NO = new Field("CLIENT_NO", "Form_Head", "CLIENT_NO");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CheckFlow = new Field("CheckFlow", "Form_Head", "CheckFlow");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ENTRY_ID = new Field("ENTRY_ID", "Form_Head", "ENTRY_ID");
        }
        #endregion


    }
}

