//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类documentsattached。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("documentsattached")]
    [Serializable]
    public partial class documentsattached : Entity
    {
        #region Model
		private int _PId;
		private string _method;
		private string _gotoFlag;
		private string _id;
		private string _dataStatus;
		private string _status;
		private string _groupId;
		private string _fileDigest;
		private string _signCert;
		private string _fileSign;
		private string _fileInfo;
		private string _fileInfoStr;
		private string _filePath;
		private string _signTime;
		private string _tradeFileName;
		private string _lockFlag;
		private string _tradeCode;
		private string _formatType;
		private string _preEntryId;
		private string _entryId;
		private string _declCode;
		private string _declName;
		private string _fileTypeCN;
		private string _fileType;
		private string _fileTypeSign;
		private string _customsCode;
		private string _signUnit;
		private string _fileName;
		private string _opNote;
		private string _edocOwnerCode;
		private string _edocOwnerName;
		private string _uploadFileName;
		private string _cookie;

		/// <summary>
		/// 
		/// </summary>
		[Field("PId")]
		public int PId
		{
			get{ return _PId; }
			set
			{
				this.OnPropertyValueChange("PId");
				this._PId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("method")]
		public string method
		{
			get{ return _method; }
			set
			{
				this.OnPropertyValueChange("method");
				this._method = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("gotoFlag")]
		public string gotoFlag
		{
			get{ return _gotoFlag; }
			set
			{
				this.OnPropertyValueChange("gotoFlag");
				this._gotoFlag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public string id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("dataStatus")]
		public string dataStatus
		{
			get{ return _dataStatus; }
			set
			{
				this.OnPropertyValueChange("dataStatus");
				this._dataStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("status")]
		public string status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange("status");
				this._status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("groupId")]
		public string groupId
		{
			get{ return _groupId; }
			set
			{
				this.OnPropertyValueChange("groupId");
				this._groupId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileDigest")]
		public string fileDigest
		{
			get{ return _fileDigest; }
			set
			{
				this.OnPropertyValueChange("fileDigest");
				this._fileDigest = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("signCert")]
		public string signCert
		{
			get{ return _signCert; }
			set
			{
				this.OnPropertyValueChange("signCert");
				this._signCert = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileSign")]
		public string fileSign
		{
			get{ return _fileSign; }
			set
			{
				this.OnPropertyValueChange("fileSign");
				this._fileSign = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileInfo")]
		public string fileInfo
		{
			get{ return _fileInfo; }
			set
			{
				this.OnPropertyValueChange("fileInfo");
				this._fileInfo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileInfoStr")]
		public string fileInfoStr
		{
			get{ return _fileInfoStr; }
			set
			{
				this.OnPropertyValueChange("fileInfoStr");
				this._fileInfoStr = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("filePath")]
		public string filePath
		{
			get{ return _filePath; }
			set
			{
				this.OnPropertyValueChange("filePath");
				this._filePath = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("signTime")]
		public string signTime
		{
			get{ return _signTime; }
			set
			{
				this.OnPropertyValueChange("signTime");
				this._signTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("tradeFileName")]
		public string tradeFileName
		{
			get{ return _tradeFileName; }
			set
			{
				this.OnPropertyValueChange("tradeFileName");
				this._tradeFileName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("lockFlag")]
		public string lockFlag
		{
			get{ return _lockFlag; }
			set
			{
				this.OnPropertyValueChange("lockFlag");
				this._lockFlag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("tradeCode")]
		public string tradeCode
		{
			get{ return _tradeCode; }
			set
			{
				this.OnPropertyValueChange("tradeCode");
				this._tradeCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("formatType")]
		public string formatType
		{
			get{ return _formatType; }
			set
			{
				this.OnPropertyValueChange("formatType");
				this._formatType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("preEntryId")]
		public string preEntryId
		{
			get{ return _preEntryId; }
			set
			{
				this.OnPropertyValueChange("preEntryId");
				this._preEntryId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("entryId")]
		public string entryId
		{
			get{ return _entryId; }
			set
			{
				this.OnPropertyValueChange("entryId");
				this._entryId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("declCode")]
		public string declCode
		{
			get{ return _declCode; }
			set
			{
				this.OnPropertyValueChange("declCode");
				this._declCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("declName")]
		public string declName
		{
			get{ return _declName; }
			set
			{
				this.OnPropertyValueChange("declName");
				this._declName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileTypeCN")]
		public string fileTypeCN
		{
			get{ return _fileTypeCN; }
			set
			{
				this.OnPropertyValueChange("fileTypeCN");
				this._fileTypeCN = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileType")]
		public string fileType
		{
			get{ return _fileType; }
			set
			{
				this.OnPropertyValueChange("fileType");
				this._fileType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileTypeSign")]
		public string fileTypeSign
		{
			get{ return _fileTypeSign; }
			set
			{
				this.OnPropertyValueChange("fileTypeSign");
				this._fileTypeSign = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("customsCode")]
		public string customsCode
		{
			get{ return _customsCode; }
			set
			{
				this.OnPropertyValueChange("customsCode");
				this._customsCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("signUnit")]
		public string signUnit
		{
			get{ return _signUnit; }
			set
			{
				this.OnPropertyValueChange("signUnit");
				this._signUnit = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fileName")]
		public string fileName
		{
			get{ return _fileName; }
			set
			{
				this.OnPropertyValueChange("fileName");
				this._fileName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("opNote")]
		public string opNote
		{
			get{ return _opNote; }
			set
			{
				this.OnPropertyValueChange("opNote");
				this._opNote = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("edocOwnerCode")]
		public string edocOwnerCode
		{
			get{ return _edocOwnerCode; }
			set
			{
				this.OnPropertyValueChange("edocOwnerCode");
				this._edocOwnerCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("edocOwnerName")]
		public string edocOwnerName
		{
			get{ return _edocOwnerName; }
			set
			{
				this.OnPropertyValueChange("edocOwnerName");
				this._edocOwnerName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uploadFileName")]
		public string uploadFileName
		{
			get{ return _uploadFileName; }
			set
			{
				this.OnPropertyValueChange("uploadFileName");
				this._uploadFileName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("cookie")]
		public string cookie
		{
			get{ return _cookie; }
			set
			{
				this.OnPropertyValueChange("cookie");
				this._cookie = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.PId,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.PId,
				_.method,
				_.gotoFlag,
				_.id,
				_.dataStatus,
				_.status,
				_.groupId,
				_.fileDigest,
				_.signCert,
				_.fileSign,
				_.fileInfo,
				_.fileInfoStr,
				_.filePath,
				_.signTime,
				_.tradeFileName,
				_.lockFlag,
				_.tradeCode,
				_.formatType,
				_.preEntryId,
				_.entryId,
				_.declCode,
				_.declName,
				_.fileTypeCN,
				_.fileType,
				_.fileTypeSign,
				_.customsCode,
				_.signUnit,
				_.fileName,
				_.opNote,
				_.edocOwnerCode,
				_.edocOwnerName,
				_.uploadFileName,
				_.cookie,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._PId,
				this._method,
				this._gotoFlag,
				this._id,
				this._dataStatus,
				this._status,
				this._groupId,
				this._fileDigest,
				this._signCert,
				this._fileSign,
				this._fileInfo,
				this._fileInfoStr,
				this._filePath,
				this._signTime,
				this._tradeFileName,
				this._lockFlag,
				this._tradeCode,
				this._formatType,
				this._preEntryId,
				this._entryId,
				this._declCode,
				this._declName,
				this._fileTypeCN,
				this._fileType,
				this._fileTypeSign,
				this._customsCode,
				this._signUnit,
				this._fileName,
				this._opNote,
				this._edocOwnerCode,
				this._edocOwnerName,
				this._uploadFileName,
				this._cookie,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "documentsattached");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PId = new Field("PId", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field method = new Field("method", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field gotoFlag = new Field("gotoFlag", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field dataStatus = new Field("dataStatus", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field status = new Field("status", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field groupId = new Field("groupId", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileDigest = new Field("fileDigest", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field signCert = new Field("signCert", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileSign = new Field("fileSign", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileInfo = new Field("fileInfo", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileInfoStr = new Field("fileInfoStr", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field filePath = new Field("filePath", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field signTime = new Field("signTime", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field tradeFileName = new Field("tradeFileName", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field lockFlag = new Field("lockFlag", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field tradeCode = new Field("tradeCode", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field formatType = new Field("formatType", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field preEntryId = new Field("preEntryId", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field entryId = new Field("entryId", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field declCode = new Field("declCode", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field declName = new Field("declName", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileTypeCN = new Field("fileTypeCN", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileType = new Field("fileType", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileTypeSign = new Field("fileTypeSign", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field customsCode = new Field("customsCode", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field signUnit = new Field("signUnit", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fileName = new Field("fileName", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field opNote = new Field("opNote", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field edocOwnerCode = new Field("edocOwnerCode", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field edocOwnerName = new Field("edocOwnerName", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uploadFileName = new Field("uploadFileName", "documentsattached", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field cookie = new Field("cookie", "documentsattached", "");
        }
        #endregion
	}
}