//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类pdf。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("pdf")]
    [Serializable]
    public partial class pdf : Entity
    {
        #region Model
		private long _Id;
		private string _Titile;
		private DateTime? _PDF_Update_Tm;
		private DateTime? _Update_Tm;
		private string _Updater;
		private DateTime? _Input_Tm;
		private string _Inputer;
		private string _En_Nm;
		private string _Ch_Nm;
		private string _Resource_Format;
		private string _Version;
		private DateTime? _Release_Tm;
		private string _Production_Distribution;
		private string _Language;
		private string _Brief_Introduction;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Titile")]
		public string Titile
		{
			get{ return _Titile; }
			set
			{
				this.OnPropertyValueChange("Titile");
				this._Titile = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PDF_Update_Tm")]
		public DateTime? PDF_Update_Tm
		{
			get{ return _PDF_Update_Tm; }
			set
			{
				this.OnPropertyValueChange("PDF_Update_Tm");
				this._PDF_Update_Tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Update_Tm")]
		public DateTime? Update_Tm
		{
			get{ return _Update_Tm; }
			set
			{
				this.OnPropertyValueChange("Update_Tm");
				this._Update_Tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Updater")]
		public string Updater
		{
			get{ return _Updater; }
			set
			{
				this.OnPropertyValueChange("Updater");
				this._Updater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Input_Tm")]
		public DateTime? Input_Tm
		{
			get{ return _Input_Tm; }
			set
			{
				this.OnPropertyValueChange("Input_Tm");
				this._Input_Tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Inputer")]
		public string Inputer
		{
			get{ return _Inputer; }
			set
			{
				this.OnPropertyValueChange("Inputer");
				this._Inputer = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("En_Nm")]
		public string En_Nm
		{
			get{ return _En_Nm; }
			set
			{
				this.OnPropertyValueChange("En_Nm");
				this._En_Nm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Ch_Nm")]
		public string Ch_Nm
		{
			get{ return _Ch_Nm; }
			set
			{
				this.OnPropertyValueChange("Ch_Nm");
				this._Ch_Nm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Resource_Format")]
		public string Resource_Format
		{
			get{ return _Resource_Format; }
			set
			{
				this.OnPropertyValueChange("Resource_Format");
				this._Resource_Format = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Version")]
		public string Version
		{
			get{ return _Version; }
			set
			{
				this.OnPropertyValueChange("Version");
				this._Version = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Release_Tm")]
		public DateTime? Release_Tm
		{
			get{ return _Release_Tm; }
			set
			{
				this.OnPropertyValueChange("Release_Tm");
				this._Release_Tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Production_Distribution")]
		public string Production_Distribution
		{
			get{ return _Production_Distribution; }
			set
			{
				this.OnPropertyValueChange("Production_Distribution");
				this._Production_Distribution = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Language")]
		public string Language
		{
			get{ return _Language; }
			set
			{
				this.OnPropertyValueChange("Language");
				this._Language = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Brief_Introduction")]
		public string Brief_Introduction
		{
			get{ return _Brief_Introduction; }
			set
			{
				this.OnPropertyValueChange("Brief_Introduction");
				this._Brief_Introduction = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.Titile,
				_.PDF_Update_Tm,
				_.Update_Tm,
				_.Updater,
				_.Input_Tm,
				_.Inputer,
				_.En_Nm,
				_.Ch_Nm,
				_.Resource_Format,
				_.Version,
				_.Release_Tm,
				_.Production_Distribution,
				_.Language,
				_.Brief_Introduction,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._Titile,
				this._PDF_Update_Tm,
				this._Update_Tm,
				this._Updater,
				this._Input_Tm,
				this._Inputer,
				this._En_Nm,
				this._Ch_Nm,
				this._Resource_Format,
				this._Version,
				this._Release_Tm,
				this._Production_Distribution,
				this._Language,
				this._Brief_Introduction,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "pdf");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Titile = new Field("Titile", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PDF_Update_Tm = new Field("PDF_Update_Tm", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Update_Tm = new Field("Update_Tm", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Updater = new Field("Updater", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Input_Tm = new Field("Input_Tm", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Inputer = new Field("Inputer", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field En_Nm = new Field("En_Nm", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Ch_Nm = new Field("Ch_Nm", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Resource_Format = new Field("Resource_Format", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Version = new Field("Version", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Release_Tm = new Field("Release_Tm", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Production_Distribution = new Field("Production_Distribution", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Language = new Field("Language", "pdf", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Brief_Introduction = new Field("Brief_Introduction", "pdf", "");
        }
        #endregion
	}
}