//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类pdf_dtl。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("pdf_dtl")]
    [Serializable]
    public partial class pdf_dtl : Entity
    {
        #region Model
		private long _pd_id;
		private string _File_Nm;
		private string _FIle_Type;
		private string _File_Size;
		private string _File_Src;
        private long? _id;
		private string _File_Url;

		/// <summary>
		/// 
		/// </summary>
		[Field("pd_id")]
        public long pd_id
		{
			get{ return _pd_id; }
			set
			{
				this.OnPropertyValueChange("pd_id");
				this._pd_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("File_Nm")]
		public string File_Nm
		{
			get{ return _File_Nm; }
			set
			{
				this.OnPropertyValueChange("File_Nm");
				this._File_Nm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FIle_Type")]
		public string FIle_Type
		{
			get{ return _FIle_Type; }
			set
			{
				this.OnPropertyValueChange("FIle_Type");
				this._FIle_Type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("File_Size")]
		public string File_Size
		{
			get{ return _File_Size; }
			set
			{
				this.OnPropertyValueChange("File_Size");
				this._File_Size = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("File_Src")]
		public string File_Src
		{
			get{ return _File_Src; }
			set
			{
				this.OnPropertyValueChange("File_Src");
				this._File_Src = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public long? id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("File_Url")]
		public string File_Url
		{
			get{ return _File_Url; }
			set
			{
				this.OnPropertyValueChange("File_Url");
				this._File_Url = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.pd_id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.pd_id,
				_.File_Nm,
				_.FIle_Type,
				_.File_Size,
				_.File_Src,
				_.id,
				_.File_Url,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._pd_id,
				this._File_Nm,
				this._FIle_Type,
				this._File_Size,
				this._File_Src,
				this._id,
				this._File_Url,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "pdf_dtl");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field pd_id = new Field("pd_id", "pdf_dtl", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field File_Nm = new Field("File_Nm", "pdf_dtl", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FIle_Type = new Field("FIle_Type", "pdf_dtl", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field File_Size = new Field("File_Size", "pdf_dtl", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field File_Src = new Field("File_Src", "pdf_dtl", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "pdf_dtl", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field File_Url = new Field("File_Url", "pdf_dtl", "");
        }
        #endregion
	}
}