//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类top200。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("top200")]
    [Serializable]
    public partial class top200 : Entity
    {
        #region Model
		private decimal _deh_id;
		private string _deh_entry_no;
		private string _deh_trade_co;
		private string _deh_trade_name;
		private string _deh_district_code;
		private string _deh_owner_code;
		private string _deh_owner_name;
		private string _deh_agent_code;
		private string _deh_agent_name;
		private string _deh_traf_mode;
		private string _deh_i_e_port;
		private string _deh_distinate_port;
		private string _deh_traf_name;
		private string _deh_contr_no;
		private decimal? _deh_in_ratio;
		private string _deh_bill_no;
		private string _deh_trade_country;
		private string _deh_trade_mode;
		private string _deh_cut_mode;
		private string _deh_pay_mode;
		private string _deh_trans_mode;
		private string _deh_pay_way;
		private string _deh_fee_mark;
		private string _deh_fee_curr;
		private decimal? _deh_fee_rate;
		private string _deh_other_mark;
		private string _deh_other_curr;
		private decimal? _deh_other_rate;
		private string _deh_insur_mark;
		private string _deh_insur_curr;
		private decimal? _deh_insur_rate;
		private decimal? _deh_pack_no;
		private decimal? _deh_gross_wt;
		private decimal? _deh_net_wt;
		private string _deh_license_no;
		private string _deh_appr_no;
		private string _deh_manual_no;
		private DateTime? _deh_i_e_date;
		private string _deh_wrap_type;
		private string _deh_note_s;
		private DateTime? _deh_d_date;
		private string _deh_ex_source;
		private string _deh_voyage_no;
		private string _deh_ie_flag;
		private string _deh_prdtid;
		private string _deh_storeno;
		private string _deh_ramanualno;
		private string _deh_radeclno;
		private string _deh_status;
		private string _deh_memo;
		private decimal? _deh_dpa_id;
		private string _inputer;
		private DateTime _input_tm;
		private string _updater;
		private DateTime? _update_tm;
		private string _sys_customer_cd;
		private string _deh_apply_port;
		private string _deh_year;
		private decimal? _deh_ie_type;
		private string _deh_ch_no;
		private string _deh_europe;
		private decimal _deh_is_del;
		private string _deh_printer;
		private string _deh_checker;
		private string _deh_dec_type;
		private string _deh_re_checker;
		private decimal _deh_is_check;
		private decimal _deh_is_receive;
		private decimal _deh_is_documents;
		private DateTime? _deh_pass_tm;
		private decimal _deh_security_clearance;
		private decimal _deh_electronic_declaration;
		private decimal? _deh_list_type;
		private decimal? _deh_note_type;
		private string _deh_taxation;
		private decimal _deh_paperless_tax;
		private decimal _deh_spec_rel_confir;
		private decimal _deh_price_confir;
		private decimal _deh_pay_of_licen_fees;
		private string _deh_trade_co_scc;
		private string _deh_decl_port;
		private string _deh_trade_area_code;
		private string _deh_owner_code_scc;
		private string _deh_agent_code_scc;
		private string _deh_edi_no;
		private decimal? _deh_customs_declaration;
		private string _deh_trade_co_ei;
		private decimal? _deh_source;
		private decimal? _deh_if_check;
		private DateTime? _deh_ues_ftp_tm;
		private string _deh_entry_id;
		private string _deh_fix_no;
		private decimal? _deh_ms_nodereceipt_status;
		private decimal? _deh_send_status;
		private decimal? _deh_import_status;

		/// <summary>
		/// 
		/// </summary>
		[Field("deh_id")]
		public decimal deh_id
		{
			get{ return _deh_id; }
			set
			{
				this.OnPropertyValueChange("deh_id");
				this._deh_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_entry_no")]
		public string deh_entry_no
		{
			get{ return _deh_entry_no; }
			set
			{
				this.OnPropertyValueChange("deh_entry_no");
				this._deh_entry_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trade_co")]
		public string deh_trade_co
		{
			get{ return _deh_trade_co; }
			set
			{
				this.OnPropertyValueChange("deh_trade_co");
				this._deh_trade_co = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trade_name")]
		public string deh_trade_name
		{
			get{ return _deh_trade_name; }
			set
			{
				this.OnPropertyValueChange("deh_trade_name");
				this._deh_trade_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_district_code")]
		public string deh_district_code
		{
			get{ return _deh_district_code; }
			set
			{
				this.OnPropertyValueChange("deh_district_code");
				this._deh_district_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_owner_code")]
		public string deh_owner_code
		{
			get{ return _deh_owner_code; }
			set
			{
				this.OnPropertyValueChange("deh_owner_code");
				this._deh_owner_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_owner_name")]
		public string deh_owner_name
		{
			get{ return _deh_owner_name; }
			set
			{
				this.OnPropertyValueChange("deh_owner_name");
				this._deh_owner_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_agent_code")]
		public string deh_agent_code
		{
			get{ return _deh_agent_code; }
			set
			{
				this.OnPropertyValueChange("deh_agent_code");
				this._deh_agent_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_agent_name")]
		public string deh_agent_name
		{
			get{ return _deh_agent_name; }
			set
			{
				this.OnPropertyValueChange("deh_agent_name");
				this._deh_agent_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_traf_mode")]
		public string deh_traf_mode
		{
			get{ return _deh_traf_mode; }
			set
			{
				this.OnPropertyValueChange("deh_traf_mode");
				this._deh_traf_mode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_i_e_port")]
		public string deh_i_e_port
		{
			get{ return _deh_i_e_port; }
			set
			{
				this.OnPropertyValueChange("deh_i_e_port");
				this._deh_i_e_port = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_distinate_port")]
		public string deh_distinate_port
		{
			get{ return _deh_distinate_port; }
			set
			{
				this.OnPropertyValueChange("deh_distinate_port");
				this._deh_distinate_port = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_traf_name")]
		public string deh_traf_name
		{
			get{ return _deh_traf_name; }
			set
			{
				this.OnPropertyValueChange("deh_traf_name");
				this._deh_traf_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_contr_no")]
		public string deh_contr_no
		{
			get{ return _deh_contr_no; }
			set
			{
				this.OnPropertyValueChange("deh_contr_no");
				this._deh_contr_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_in_ratio")]
		public decimal? deh_in_ratio
		{
			get{ return _deh_in_ratio; }
			set
			{
				this.OnPropertyValueChange("deh_in_ratio");
				this._deh_in_ratio = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_bill_no")]
		public string deh_bill_no
		{
			get{ return _deh_bill_no; }
			set
			{
				this.OnPropertyValueChange("deh_bill_no");
				this._deh_bill_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trade_country")]
		public string deh_trade_country
		{
			get{ return _deh_trade_country; }
			set
			{
				this.OnPropertyValueChange("deh_trade_country");
				this._deh_trade_country = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trade_mode")]
		public string deh_trade_mode
		{
			get{ return _deh_trade_mode; }
			set
			{
				this.OnPropertyValueChange("deh_trade_mode");
				this._deh_trade_mode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_cut_mode")]
		public string deh_cut_mode
		{
			get{ return _deh_cut_mode; }
			set
			{
				this.OnPropertyValueChange("deh_cut_mode");
				this._deh_cut_mode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_pay_mode")]
		public string deh_pay_mode
		{
			get{ return _deh_pay_mode; }
			set
			{
				this.OnPropertyValueChange("deh_pay_mode");
				this._deh_pay_mode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trans_mode")]
		public string deh_trans_mode
		{
			get{ return _deh_trans_mode; }
			set
			{
				this.OnPropertyValueChange("deh_trans_mode");
				this._deh_trans_mode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_pay_way")]
		public string deh_pay_way
		{
			get{ return _deh_pay_way; }
			set
			{
				this.OnPropertyValueChange("deh_pay_way");
				this._deh_pay_way = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_fee_mark")]
		public string deh_fee_mark
		{
			get{ return _deh_fee_mark; }
			set
			{
				this.OnPropertyValueChange("deh_fee_mark");
				this._deh_fee_mark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_fee_curr")]
		public string deh_fee_curr
		{
			get{ return _deh_fee_curr; }
			set
			{
				this.OnPropertyValueChange("deh_fee_curr");
				this._deh_fee_curr = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_fee_rate")]
		public decimal? deh_fee_rate
		{
			get{ return _deh_fee_rate; }
			set
			{
				this.OnPropertyValueChange("deh_fee_rate");
				this._deh_fee_rate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_other_mark")]
		public string deh_other_mark
		{
			get{ return _deh_other_mark; }
			set
			{
				this.OnPropertyValueChange("deh_other_mark");
				this._deh_other_mark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_other_curr")]
		public string deh_other_curr
		{
			get{ return _deh_other_curr; }
			set
			{
				this.OnPropertyValueChange("deh_other_curr");
				this._deh_other_curr = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_other_rate")]
		public decimal? deh_other_rate
		{
			get{ return _deh_other_rate; }
			set
			{
				this.OnPropertyValueChange("deh_other_rate");
				this._deh_other_rate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_insur_mark")]
		public string deh_insur_mark
		{
			get{ return _deh_insur_mark; }
			set
			{
				this.OnPropertyValueChange("deh_insur_mark");
				this._deh_insur_mark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_insur_curr")]
		public string deh_insur_curr
		{
			get{ return _deh_insur_curr; }
			set
			{
				this.OnPropertyValueChange("deh_insur_curr");
				this._deh_insur_curr = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_insur_rate")]
		public decimal? deh_insur_rate
		{
			get{ return _deh_insur_rate; }
			set
			{
				this.OnPropertyValueChange("deh_insur_rate");
				this._deh_insur_rate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_pack_no")]
		public decimal? deh_pack_no
		{
			get{ return _deh_pack_no; }
			set
			{
				this.OnPropertyValueChange("deh_pack_no");
				this._deh_pack_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_gross_wt")]
		public decimal? deh_gross_wt
		{
			get{ return _deh_gross_wt; }
			set
			{
				this.OnPropertyValueChange("deh_gross_wt");
				this._deh_gross_wt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_net_wt")]
		public decimal? deh_net_wt
		{
			get{ return _deh_net_wt; }
			set
			{
				this.OnPropertyValueChange("deh_net_wt");
				this._deh_net_wt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_license_no")]
		public string deh_license_no
		{
			get{ return _deh_license_no; }
			set
			{
				this.OnPropertyValueChange("deh_license_no");
				this._deh_license_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_appr_no")]
		public string deh_appr_no
		{
			get{ return _deh_appr_no; }
			set
			{
				this.OnPropertyValueChange("deh_appr_no");
				this._deh_appr_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_manual_no")]
		public string deh_manual_no
		{
			get{ return _deh_manual_no; }
			set
			{
				this.OnPropertyValueChange("deh_manual_no");
				this._deh_manual_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_i_e_date")]
		public DateTime? deh_i_e_date
		{
			get{ return _deh_i_e_date; }
			set
			{
				this.OnPropertyValueChange("deh_i_e_date");
				this._deh_i_e_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_wrap_type")]
		public string deh_wrap_type
		{
			get{ return _deh_wrap_type; }
			set
			{
				this.OnPropertyValueChange("deh_wrap_type");
				this._deh_wrap_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_note_s")]
		public string deh_note_s
		{
			get{ return _deh_note_s; }
			set
			{
				this.OnPropertyValueChange("deh_note_s");
				this._deh_note_s = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_d_date")]
		public DateTime? deh_d_date
		{
			get{ return _deh_d_date; }
			set
			{
				this.OnPropertyValueChange("deh_d_date");
				this._deh_d_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_ex_source")]
		public string deh_ex_source
		{
			get{ return _deh_ex_source; }
			set
			{
				this.OnPropertyValueChange("deh_ex_source");
				this._deh_ex_source = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_voyage_no")]
		public string deh_voyage_no
		{
			get{ return _deh_voyage_no; }
			set
			{
				this.OnPropertyValueChange("deh_voyage_no");
				this._deh_voyage_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_ie_flag")]
		public string deh_ie_flag
		{
			get{ return _deh_ie_flag; }
			set
			{
				this.OnPropertyValueChange("deh_ie_flag");
				this._deh_ie_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_prdtid")]
		public string deh_prdtid
		{
			get{ return _deh_prdtid; }
			set
			{
				this.OnPropertyValueChange("deh_prdtid");
				this._deh_prdtid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_storeno")]
		public string deh_storeno
		{
			get{ return _deh_storeno; }
			set
			{
				this.OnPropertyValueChange("deh_storeno");
				this._deh_storeno = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_ramanualno")]
		public string deh_ramanualno
		{
			get{ return _deh_ramanualno; }
			set
			{
				this.OnPropertyValueChange("deh_ramanualno");
				this._deh_ramanualno = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_radeclno")]
		public string deh_radeclno
		{
			get{ return _deh_radeclno; }
			set
			{
				this.OnPropertyValueChange("deh_radeclno");
				this._deh_radeclno = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_status")]
		public string deh_status
		{
			get{ return _deh_status; }
			set
			{
				this.OnPropertyValueChange("deh_status");
				this._deh_status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_memo")]
		public string deh_memo
		{
			get{ return _deh_memo; }
			set
			{
				this.OnPropertyValueChange("deh_memo");
				this._deh_memo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_dpa_id")]
		public decimal? deh_dpa_id
		{
			get{ return _deh_dpa_id; }
			set
			{
				this.OnPropertyValueChange("deh_dpa_id");
				this._deh_dpa_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("inputer")]
		public string inputer
		{
			get{ return _inputer; }
			set
			{
				this.OnPropertyValueChange("inputer");
				this._inputer = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("input_tm")]
		public DateTime input_tm
		{
			get{ return _input_tm; }
			set
			{
				this.OnPropertyValueChange("input_tm");
				this._input_tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("updater")]
		public string updater
		{
			get{ return _updater; }
			set
			{
				this.OnPropertyValueChange("updater");
				this._updater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_tm")]
		public DateTime? update_tm
		{
			get{ return _update_tm; }
			set
			{
				this.OnPropertyValueChange("update_tm");
				this._update_tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("sys_customer_cd")]
		public string sys_customer_cd
		{
			get{ return _sys_customer_cd; }
			set
			{
				this.OnPropertyValueChange("sys_customer_cd");
				this._sys_customer_cd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_apply_port")]
		public string deh_apply_port
		{
			get{ return _deh_apply_port; }
			set
			{
				this.OnPropertyValueChange("deh_apply_port");
				this._deh_apply_port = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_year")]
		public string deh_year
		{
			get{ return _deh_year; }
			set
			{
				this.OnPropertyValueChange("deh_year");
				this._deh_year = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_ie_type")]
		public decimal? deh_ie_type
		{
			get{ return _deh_ie_type; }
			set
			{
				this.OnPropertyValueChange("deh_ie_type");
				this._deh_ie_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_ch_no")]
		public string deh_ch_no
		{
			get{ return _deh_ch_no; }
			set
			{
				this.OnPropertyValueChange("deh_ch_no");
				this._deh_ch_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_europe")]
		public string deh_europe
		{
			get{ return _deh_europe; }
			set
			{
				this.OnPropertyValueChange("deh_europe");
				this._deh_europe = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_is_del")]
		public decimal deh_is_del
		{
			get{ return _deh_is_del; }
			set
			{
				this.OnPropertyValueChange("deh_is_del");
				this._deh_is_del = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_printer")]
		public string deh_printer
		{
			get{ return _deh_printer; }
			set
			{
				this.OnPropertyValueChange("deh_printer");
				this._deh_printer = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_checker")]
		public string deh_checker
		{
			get{ return _deh_checker; }
			set
			{
				this.OnPropertyValueChange("deh_checker");
				this._deh_checker = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_dec_type")]
		public string deh_dec_type
		{
			get{ return _deh_dec_type; }
			set
			{
				this.OnPropertyValueChange("deh_dec_type");
				this._deh_dec_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_re_checker")]
		public string deh_re_checker
		{
			get{ return _deh_re_checker; }
			set
			{
				this.OnPropertyValueChange("deh_re_checker");
				this._deh_re_checker = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_is_check")]
		public decimal deh_is_check
		{
			get{ return _deh_is_check; }
			set
			{
				this.OnPropertyValueChange("deh_is_check");
				this._deh_is_check = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_is_receive")]
		public decimal deh_is_receive
		{
			get{ return _deh_is_receive; }
			set
			{
				this.OnPropertyValueChange("deh_is_receive");
				this._deh_is_receive = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_is_documents")]
		public decimal deh_is_documents
		{
			get{ return _deh_is_documents; }
			set
			{
				this.OnPropertyValueChange("deh_is_documents");
				this._deh_is_documents = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_pass_tm")]
		public DateTime? deh_pass_tm
		{
			get{ return _deh_pass_tm; }
			set
			{
				this.OnPropertyValueChange("deh_pass_tm");
				this._deh_pass_tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_security_clearance")]
		public decimal deh_security_clearance
		{
			get{ return _deh_security_clearance; }
			set
			{
				this.OnPropertyValueChange("deh_security_clearance");
				this._deh_security_clearance = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_electronic_declaration")]
		public decimal deh_electronic_declaration
		{
			get{ return _deh_electronic_declaration; }
			set
			{
				this.OnPropertyValueChange("deh_electronic_declaration");
				this._deh_electronic_declaration = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_list_type")]
		public decimal? deh_list_type
		{
			get{ return _deh_list_type; }
			set
			{
				this.OnPropertyValueChange("deh_list_type");
				this._deh_list_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_note_type")]
		public decimal? deh_note_type
		{
			get{ return _deh_note_type; }
			set
			{
				this.OnPropertyValueChange("deh_note_type");
				this._deh_note_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_taxation")]
		public string deh_taxation
		{
			get{ return _deh_taxation; }
			set
			{
				this.OnPropertyValueChange("deh_taxation");
				this._deh_taxation = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_paperless_tax")]
		public decimal deh_paperless_tax
		{
			get{ return _deh_paperless_tax; }
			set
			{
				this.OnPropertyValueChange("deh_paperless_tax");
				this._deh_paperless_tax = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_spec_rel_confir")]
		public decimal deh_spec_rel_confir
		{
			get{ return _deh_spec_rel_confir; }
			set
			{
				this.OnPropertyValueChange("deh_spec_rel_confir");
				this._deh_spec_rel_confir = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_price_confir")]
		public decimal deh_price_confir
		{
			get{ return _deh_price_confir; }
			set
			{
				this.OnPropertyValueChange("deh_price_confir");
				this._deh_price_confir = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_pay_of_licen_fees")]
		public decimal deh_pay_of_licen_fees
		{
			get{ return _deh_pay_of_licen_fees; }
			set
			{
				this.OnPropertyValueChange("deh_pay_of_licen_fees");
				this._deh_pay_of_licen_fees = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trade_co_scc")]
		public string deh_trade_co_scc
		{
			get{ return _deh_trade_co_scc; }
			set
			{
				this.OnPropertyValueChange("deh_trade_co_scc");
				this._deh_trade_co_scc = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_decl_port")]
		public string deh_decl_port
		{
			get{ return _deh_decl_port; }
			set
			{
				this.OnPropertyValueChange("deh_decl_port");
				this._deh_decl_port = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trade_area_code")]
		public string deh_trade_area_code
		{
			get{ return _deh_trade_area_code; }
			set
			{
				this.OnPropertyValueChange("deh_trade_area_code");
				this._deh_trade_area_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_owner_code_scc")]
		public string deh_owner_code_scc
		{
			get{ return _deh_owner_code_scc; }
			set
			{
				this.OnPropertyValueChange("deh_owner_code_scc");
				this._deh_owner_code_scc = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_agent_code_scc")]
		public string deh_agent_code_scc
		{
			get{ return _deh_agent_code_scc; }
			set
			{
				this.OnPropertyValueChange("deh_agent_code_scc");
				this._deh_agent_code_scc = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_edi_no")]
		public string deh_edi_no
		{
			get{ return _deh_edi_no; }
			set
			{
				this.OnPropertyValueChange("deh_edi_no");
				this._deh_edi_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_customs_declaration")]
		public decimal? deh_customs_declaration
		{
			get{ return _deh_customs_declaration; }
			set
			{
				this.OnPropertyValueChange("deh_customs_declaration");
				this._deh_customs_declaration = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_trade_co_ei")]
		public string deh_trade_co_ei
		{
			get{ return _deh_trade_co_ei; }
			set
			{
				this.OnPropertyValueChange("deh_trade_co_ei");
				this._deh_trade_co_ei = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_source")]
		public decimal? deh_source
		{
			get{ return _deh_source; }
			set
			{
				this.OnPropertyValueChange("deh_source");
				this._deh_source = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_if_check")]
		public decimal? deh_if_check
		{
			get{ return _deh_if_check; }
			set
			{
				this.OnPropertyValueChange("deh_if_check");
				this._deh_if_check = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_ues_ftp_tm")]
		public DateTime? deh_ues_ftp_tm
		{
			get{ return _deh_ues_ftp_tm; }
			set
			{
				this.OnPropertyValueChange("deh_ues_ftp_tm");
				this._deh_ues_ftp_tm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_entry_id")]
		public string deh_entry_id
		{
			get{ return _deh_entry_id; }
			set
			{
				this.OnPropertyValueChange("deh_entry_id");
				this._deh_entry_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_fix_no")]
		public string deh_fix_no
		{
			get{ return _deh_fix_no; }
			set
			{
				this.OnPropertyValueChange("deh_fix_no");
				this._deh_fix_no = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_ms_nodereceipt_status")]
		public decimal? deh_ms_nodereceipt_status
		{
			get{ return _deh_ms_nodereceipt_status; }
			set
			{
				this.OnPropertyValueChange("deh_ms_nodereceipt_status");
				this._deh_ms_nodereceipt_status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_send_status")]
		public decimal? deh_send_status
		{
			get{ return _deh_send_status; }
			set
			{
				this.OnPropertyValueChange("deh_send_status");
				this._deh_send_status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("deh_import_status")]
		public decimal? deh_import_status
		{
			get{ return _deh_import_status; }
			set
			{
				this.OnPropertyValueChange("deh_import_status");
				this._deh_import_status = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.deh_id,
				_.deh_entry_no,
				_.deh_trade_co,
				_.deh_trade_name,
				_.deh_district_code,
				_.deh_owner_code,
				_.deh_owner_name,
				_.deh_agent_code,
				_.deh_agent_name,
				_.deh_traf_mode,
				_.deh_i_e_port,
				_.deh_distinate_port,
				_.deh_traf_name,
				_.deh_contr_no,
				_.deh_in_ratio,
				_.deh_bill_no,
				_.deh_trade_country,
				_.deh_trade_mode,
				_.deh_cut_mode,
				_.deh_pay_mode,
				_.deh_trans_mode,
				_.deh_pay_way,
				_.deh_fee_mark,
				_.deh_fee_curr,
				_.deh_fee_rate,
				_.deh_other_mark,
				_.deh_other_curr,
				_.deh_other_rate,
				_.deh_insur_mark,
				_.deh_insur_curr,
				_.deh_insur_rate,
				_.deh_pack_no,
				_.deh_gross_wt,
				_.deh_net_wt,
				_.deh_license_no,
				_.deh_appr_no,
				_.deh_manual_no,
				_.deh_i_e_date,
				_.deh_wrap_type,
				_.deh_note_s,
				_.deh_d_date,
				_.deh_ex_source,
				_.deh_voyage_no,
				_.deh_ie_flag,
				_.deh_prdtid,
				_.deh_storeno,
				_.deh_ramanualno,
				_.deh_radeclno,
				_.deh_status,
				_.deh_memo,
				_.deh_dpa_id,
				_.inputer,
				_.input_tm,
				_.updater,
				_.update_tm,
				_.sys_customer_cd,
				_.deh_apply_port,
				_.deh_year,
				_.deh_ie_type,
				_.deh_ch_no,
				_.deh_europe,
				_.deh_is_del,
				_.deh_printer,
				_.deh_checker,
				_.deh_dec_type,
				_.deh_re_checker,
				_.deh_is_check,
				_.deh_is_receive,
				_.deh_is_documents,
				_.deh_pass_tm,
				_.deh_security_clearance,
				_.deh_electronic_declaration,
				_.deh_list_type,
				_.deh_note_type,
				_.deh_taxation,
				_.deh_paperless_tax,
				_.deh_spec_rel_confir,
				_.deh_price_confir,
				_.deh_pay_of_licen_fees,
				_.deh_trade_co_scc,
				_.deh_decl_port,
				_.deh_trade_area_code,
				_.deh_owner_code_scc,
				_.deh_agent_code_scc,
				_.deh_edi_no,
				_.deh_customs_declaration,
				_.deh_trade_co_ei,
				_.deh_source,
				_.deh_if_check,
				_.deh_ues_ftp_tm,
				_.deh_entry_id,
				_.deh_fix_no,
				_.deh_ms_nodereceipt_status,
				_.deh_send_status,
				_.deh_import_status,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._deh_id,
				this._deh_entry_no,
				this._deh_trade_co,
				this._deh_trade_name,
				this._deh_district_code,
				this._deh_owner_code,
				this._deh_owner_name,
				this._deh_agent_code,
				this._deh_agent_name,
				this._deh_traf_mode,
				this._deh_i_e_port,
				this._deh_distinate_port,
				this._deh_traf_name,
				this._deh_contr_no,
				this._deh_in_ratio,
				this._deh_bill_no,
				this._deh_trade_country,
				this._deh_trade_mode,
				this._deh_cut_mode,
				this._deh_pay_mode,
				this._deh_trans_mode,
				this._deh_pay_way,
				this._deh_fee_mark,
				this._deh_fee_curr,
				this._deh_fee_rate,
				this._deh_other_mark,
				this._deh_other_curr,
				this._deh_other_rate,
				this._deh_insur_mark,
				this._deh_insur_curr,
				this._deh_insur_rate,
				this._deh_pack_no,
				this._deh_gross_wt,
				this._deh_net_wt,
				this._deh_license_no,
				this._deh_appr_no,
				this._deh_manual_no,
				this._deh_i_e_date,
				this._deh_wrap_type,
				this._deh_note_s,
				this._deh_d_date,
				this._deh_ex_source,
				this._deh_voyage_no,
				this._deh_ie_flag,
				this._deh_prdtid,
				this._deh_storeno,
				this._deh_ramanualno,
				this._deh_radeclno,
				this._deh_status,
				this._deh_memo,
				this._deh_dpa_id,
				this._inputer,
				this._input_tm,
				this._updater,
				this._update_tm,
				this._sys_customer_cd,
				this._deh_apply_port,
				this._deh_year,
				this._deh_ie_type,
				this._deh_ch_no,
				this._deh_europe,
				this._deh_is_del,
				this._deh_printer,
				this._deh_checker,
				this._deh_dec_type,
				this._deh_re_checker,
				this._deh_is_check,
				this._deh_is_receive,
				this._deh_is_documents,
				this._deh_pass_tm,
				this._deh_security_clearance,
				this._deh_electronic_declaration,
				this._deh_list_type,
				this._deh_note_type,
				this._deh_taxation,
				this._deh_paperless_tax,
				this._deh_spec_rel_confir,
				this._deh_price_confir,
				this._deh_pay_of_licen_fees,
				this._deh_trade_co_scc,
				this._deh_decl_port,
				this._deh_trade_area_code,
				this._deh_owner_code_scc,
				this._deh_agent_code_scc,
				this._deh_edi_no,
				this._deh_customs_declaration,
				this._deh_trade_co_ei,
				this._deh_source,
				this._deh_if_check,
				this._deh_ues_ftp_tm,
				this._deh_entry_id,
				this._deh_fix_no,
				this._deh_ms_nodereceipt_status,
				this._deh_send_status,
				this._deh_import_status,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "top200");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_id = new Field("deh_id", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_entry_no = new Field("deh_entry_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trade_co = new Field("deh_trade_co", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trade_name = new Field("deh_trade_name", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_district_code = new Field("deh_district_code", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_owner_code = new Field("deh_owner_code", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_owner_name = new Field("deh_owner_name", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_agent_code = new Field("deh_agent_code", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_agent_name = new Field("deh_agent_name", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_traf_mode = new Field("deh_traf_mode", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_i_e_port = new Field("deh_i_e_port", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_distinate_port = new Field("deh_distinate_port", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_traf_name = new Field("deh_traf_name", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_contr_no = new Field("deh_contr_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_in_ratio = new Field("deh_in_ratio", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_bill_no = new Field("deh_bill_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trade_country = new Field("deh_trade_country", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trade_mode = new Field("deh_trade_mode", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_cut_mode = new Field("deh_cut_mode", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_pay_mode = new Field("deh_pay_mode", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trans_mode = new Field("deh_trans_mode", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_pay_way = new Field("deh_pay_way", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_fee_mark = new Field("deh_fee_mark", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_fee_curr = new Field("deh_fee_curr", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_fee_rate = new Field("deh_fee_rate", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_other_mark = new Field("deh_other_mark", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_other_curr = new Field("deh_other_curr", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_other_rate = new Field("deh_other_rate", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_insur_mark = new Field("deh_insur_mark", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_insur_curr = new Field("deh_insur_curr", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_insur_rate = new Field("deh_insur_rate", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_pack_no = new Field("deh_pack_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_gross_wt = new Field("deh_gross_wt", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_net_wt = new Field("deh_net_wt", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_license_no = new Field("deh_license_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_appr_no = new Field("deh_appr_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_manual_no = new Field("deh_manual_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_i_e_date = new Field("deh_i_e_date", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_wrap_type = new Field("deh_wrap_type", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_note_s = new Field("deh_note_s", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_d_date = new Field("deh_d_date", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_ex_source = new Field("deh_ex_source", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_voyage_no = new Field("deh_voyage_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_ie_flag = new Field("deh_ie_flag", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_prdtid = new Field("deh_prdtid", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_storeno = new Field("deh_storeno", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_ramanualno = new Field("deh_ramanualno", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_radeclno = new Field("deh_radeclno", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_status = new Field("deh_status", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_memo = new Field("deh_memo", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_dpa_id = new Field("deh_dpa_id", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field inputer = new Field("inputer", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field input_tm = new Field("input_tm", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field updater = new Field("updater", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field update_tm = new Field("update_tm", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field sys_customer_cd = new Field("sys_customer_cd", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_apply_port = new Field("deh_apply_port", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_year = new Field("deh_year", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_ie_type = new Field("deh_ie_type", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_ch_no = new Field("deh_ch_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_europe = new Field("deh_europe", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_is_del = new Field("deh_is_del", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_printer = new Field("deh_printer", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_checker = new Field("deh_checker", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_dec_type = new Field("deh_dec_type", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_re_checker = new Field("deh_re_checker", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_is_check = new Field("deh_is_check", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_is_receive = new Field("deh_is_receive", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_is_documents = new Field("deh_is_documents", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_pass_tm = new Field("deh_pass_tm", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_security_clearance = new Field("deh_security_clearance", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_electronic_declaration = new Field("deh_electronic_declaration", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_list_type = new Field("deh_list_type", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_note_type = new Field("deh_note_type", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_taxation = new Field("deh_taxation", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_paperless_tax = new Field("deh_paperless_tax", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_spec_rel_confir = new Field("deh_spec_rel_confir", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_price_confir = new Field("deh_price_confir", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_pay_of_licen_fees = new Field("deh_pay_of_licen_fees", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trade_co_scc = new Field("deh_trade_co_scc", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_decl_port = new Field("deh_decl_port", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trade_area_code = new Field("deh_trade_area_code", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_owner_code_scc = new Field("deh_owner_code_scc", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_agent_code_scc = new Field("deh_agent_code_scc", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_edi_no = new Field("deh_edi_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_customs_declaration = new Field("deh_customs_declaration", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_trade_co_ei = new Field("deh_trade_co_ei", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_source = new Field("deh_source", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_if_check = new Field("deh_if_check", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_ues_ftp_tm = new Field("deh_ues_ftp_tm", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_entry_id = new Field("deh_entry_id", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_fix_no = new Field("deh_fix_no", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_ms_nodereceipt_status = new Field("deh_ms_nodereceipt_status", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_send_status = new Field("deh_send_status", "top200", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field deh_import_status = new Field("deh_import_status", "top200", "");
        }
        #endregion
	}
}